### PR TITLE
experiment(nm): Not for merging! Use zip in JS implementation for nm linker

### PR DESCRIPTION
**Pull request by larixer**
**What's the problem this PR addresses?**

We are using wasm libzip for processing zip archives. Are we losing much perfs because of this, will we have better perfs with zip in JS implementation? This PR carries out an experiment on whether zip in JS boosts runtime PnP performance and nm linker linking phase performance.

Relevant discussion:
https://github.com/yarnpkg/berry/discussions/2757

**How did you fix it?**

I have added `unzipper` and use it for nm linker linking phase, to check whether this will improve performance thanks to avoiding wasm libzip. Since nm linker processes zip archives during the linking phase intensively, it is a reasonable measurement to answer the question.

From my measurement of running nm linker on Storybook repo with build scripts disabled, the answer is that wasm libzip is faster than unzipper zip in JS implementation:
  - With libzip wasm, link time: 47 secs
  - With unzipper, link time: 53 secs

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

**Comment by 101arrowz** [comment]
Interesting, even though a JS implementation of unzip seemed to perform better on individual files it doesn't seem to be the case overall. Maybe the use of streams is causing overhead issues when the files are very small? It's possible that non-streaming unzip would be faster.

**Comment by larixer** [comment]
> Interesting, even though a JS implementation of unzip seemed to perform better on individual files it doesn't seem to be the case overall. Maybe the use of streams is causing overhead issues when the files are very small? It's possible that non-streaming unzip would be faster.

@101arrowz  Do you know unzip implementation in JS which is not using streams?

**Comment by 101arrowz** [comment]
There are many, `fflate` and `UZIP` are the ones I am most familiar with. You can try the demo code provided in the original issue.

**Comment by larixer** [comment]
> There are many, `fflate` and `UZIP` are the ones I am most familiar with. You can try the demo code provided in the original issue.

@101arrowz I have switched implementation to `UZIP`, its indeed faster by 10% - 15% compared to wasm libzip, but the gains are still very low, jitter during measurements is typically at these levels too.

**Comment by andreialecu** [comment]
Is the test with compression enabled or disabled? 

If compression is enabled, does the js implementation use the node zlib for decompression?

**Comment by larixer** [comment]
@andreialecu 

> Is the test with compression enabled or disabled?
> 
> If compression is enabled, does the js implementation use the node zlib for decompression?

I have tested with `compressionLevel: 0`, so no - not enabled.

**Pull request closed without merging**
