### PR TITLE
Add an existing dev dependency as peer dependency when using --peer (…

### LINKED ISSUE #652: [Bug] yarn add --peer after --dev doesn't add peer dependency
- [ ] I'd be willing to implement a fix

**Describe the bug**

I have a library that depends on `rxjs` as a peer dependency, but it also has tests inside it. 

If I add `rxjs` as a normal dependency, tests run properly. If instead I run:

`yarn add --peer --dev rxjs`

My tests will complain about: `Cannot find module 'rxjs' from '...'`

Note that I'm also using typescript and `ts-jest`. 

Ideally, the dependency should be available to both peer and dev dependencies.

**To Reproduce**

```js repro
const {promises: {readFile}} = require(`fs`);

await packageJsonAndInstall({
  devDependencies: {},
});

await yarn(`add`, `--dev`, `rxjs`);
await yarn(`add`, `--peer`, `rxjs`);

const pkgJson = JSON.parse(await readFile(`package.json`, `utf8`));
expect(pkgJson).toHaveProperty(`peerDependencies`);
expect(pkgJson).toHaveProperty(`devDependencies`);
expect(pkgJson.peerDependencies).toHaveProperty(`rxjs`);
expect(pkgJson.devDependencies).toHaveProperty(`rxjs`);
```

**Additional context**

This is also a bug in yarn v1: https://github.com/yarnpkg/yarn/issues/5287

### PR DESCRIPTION
**Pull request by ngryman**
**What's the problem this PR addresses?**

This PR resolves #652.

**How did you fix it?**

As suggested by @arcanis, I've given CLI flags precedence over the detection heuristic.

### CODE REVIEW

**Comment by arcanis** [comment]
Looks good! Can you run `yarn version check -i` and mark the essentials + CLI for prerelease? The others can be set to "decline". Thanks!

**Comment by ngryman** [comment]
@arcanis Thanks. Out of curiosity, why did it created a new YML file in `.yarn/versions`? I'm not yet very familiar with Berry 😄

**Comment by arcanis** [comment]
It's part of a new feature described here: [Release Workflow](https://next.yarnpkg.com/features/release-workflow).

Basically, Yarn is able to generate one such yml file for each PR indicating which packages will need to be re-released given the changes in the PR. Then once it's release time, I just have to run `yarn version apply` for Yarn to aggregate all the deferred releases and apply them in a single pass (skipping over duplicates).

Note that the test is failing because you didn't mark the remaining packages as "decline", so Yarn doesn't know whether you meant that the other packages shouldn't be released or whether you forgot to specify a release strategy.

**Comment by arcanis** [comment]
Thanks 🌟

**Comment by ngryman** [comment]
🎉 Thanks for the insights @arcanis

**Pull request merged**
