### PR TITLE
fix(core): use binjumper to work-around 'Terminate batch job' prompts on Windows

### LINKED ISSUE #1592: [Bug] Terminate batch job (Y/N)?
- [ ] I'd be willing to implement a fix

**Describe the bug**

”Terminate batch jobs (Y / N)“ will be encountered multiple times when ending a script on Microsoft Windows. but npm run can end immediately

**To Reproduce**

```
$ yarn create vite-app <project-name>
$ cd <project-name>
$ yarn
$ yarn dev
```

ctrl+c

```
❯ yarn dev
vite v1.0.0-beta.11

  Dev server running at:
  > Local:    http://localhost:3000/

^CTerminate batch job (Y/N)? Y
Terminate batch job (Y/N)? Y
```

**Environment if relevant (please complete the following information):**

 - OS: Windows
 - Node version: v14.4.0
 - Yarn version 2.1.1

**Additional context**

### PR DESCRIPTION
**Pull request by merceyz**
**What's the problem this PR addresses?**

Due to the use of cmd jumper-files to spawn binaries, terminating scripts on Windows is horrendously annoying since CMD provides no way to disable the `Terminate batch job (Y/N)` prompt

Fixes #1592

**How did you fix it?**

Create the jumper files using https://github.com/merceyz/binjumper to avoid the prompts

**Checklist**
- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).
- [x] I have set the packages that need to be released for my changes to be effective.
- [x] I have verified that all automated PR checks pass.

### CODE REVIEW

**Comment by arcanis** [comment]
> since CMD provides no way to disable the `Terminate batch job (Y/N)` prompt

Would creating a Powershell script instead of CMD work? The builtin binaries approach is a bit magical, I'm slightly worry it would open us to weird differences between spawning a binary from a script versus from a shellscript spawned by a script 🤔

**Comment by merceyz** [comment]
> Would creating a Powershell script instead of CMD work?

While Powershell doesn't create the prompt it seems `cross-spawn` doesn't know how to handle them, I added `.ps1` to the `PATHEXT` but it just opens the file in Visual Studio.

> The builtin binaries approach is a bit magical, I'm slightly worry it would open us to weird differences between spawning a binary from a script versus from a shellscript spawned by a script

The difference would be the prompt, otherwise it shouldn't be noticable :thinking:

**Comment by arcanis** [comment]
Related: https://github.com/microsoft/terminal/issues/217

**Comment by cowboyd** [comment]
Can we backport this to 1.x? I'd be happy to give it a shot.

**Comment by arcanis** [comment]
@cowboyd 1.x is in feature freeze, only security issues will be addressed. I suggest you take a look at the [migration guide](https://yarnpkg.com/getting-started/migration) if you need features introduced in the 2.x.

**Pull request merged**
