### PR TITLE
fix(cli): fix getPluginConfiguration not working when plugins are active

### LINKED ISSUE #841: [Bug] @yarnpkg/doctor fails after adding a yarn plugin
- [ ] I'd be willing to implement a fix

**Describe the bug**

After install a yarn plugin, `yarn dlx @yarnpkg/doctor` will fail to execute with the following:

```
yarn dlx @yarnpkg/doctor

➤ YN0000: ┌ Resolution step
➤ YN0002: │ @yarnpkg/plugin-version@npm:2.0.0-rc.20 [10f20] doesn't provide @types/react@>=16.8.0 requested by ink@npm:2.6.0
➤ YN0000: └ Completed in 2.42s
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0.2s
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 0.42s
➤ YN0000: Done with warnings in 3.06s

➤ YN0000: Found 3 package(s) to process
➤ YN0000: For a grand total of 14 file(s) to validate

➤ YN0000: ┌ /Users/josh0.05spackage.json
➤ YN0001: │ UsageError: This plugin cannot access the package referenced via @yarnpkg/cli which is neither a builtin, nor an exposed entry (when initializing @yarnpkg/plugin-workspace-tools, defined in /Users/josh/project/.yarnrc.yml)
    at pluginRequire (/Users/josh/.yarn/berry/cache/@yarnpkg-core-npm-2.0.0-rc.22-22619c9c59-1.zip/node_modules/@yarnpkg/core/lib/Configuration.js:536:31)
    at Object.<anonymous> (/Users/josh/project/.yarn/plugins/@yarnpkg/plugin-workspace-tools.js:448:20)
    at __webpack_require__ (/Users/josh/project/.yarn/plugins/@yarnpkg/plugin-workspace-tools.js:25:32)
    at Object.<anonymous> (/Users/josh/project/.yarn/plugins/@yarnpkg/plugin-workspace-tools.js:150:17)
    at __webpack_require__ (/Users/josh/project/.yarn/plugins/@yarnpkg/plugin-workspace-tools.js:25:32)
    at Object.<anonymous> (/Users/josh/project/.yarn/plugins/@yarnpkg/plugin-workspace-tools.js:109:37)
    at __webpack_require__ (/Users/josh/project/.yarn/plugins/@yarnpkg/plugin-workspace-tools.js:25:32)
    at /Users/josh/project/.yarn/plugins/@yarnpkg/plugin-workspace-tools.js:89:20
    at factory (/Users/josh/project/.yarn/plugins/@yarnpkg/plugin-workspace-tools.js:92:12)
    at /Users/josh/.yarn/berry/cache/@yarnpkg-core-npm-2.0.0-rc.22-22619c9c59-1.zip/node_modules/@yarnpkg/core/lib/Configuration.js:540:39
➤ YN0000: └ Completed in 0.05s
```

**To Reproduce**

```
yarn plugin import workspace-tools
yarn dlx @yarnpkg/doctor
```

Works as expected if plugins are removed from `.yarnrc.yml`

**Environment if relevant (please complete the following information):**

 - OS: OSX
 - Node version: 13.7.0
 - Yarn version: 2.0.0-rc.27

### PR DESCRIPTION
**Pull request by paul-soporan**
**What's the problem this PR addresses?**

This PR fixes #841.

**How did you fix it?**

The problem wasn't in `@yarnpkg/doctor`, but in `@yarnpkg/cli`.
`getPluginConfiguration` was failing when plugins were active because it didn't expose `@yarnpkg/core` when run through Node.

### CODE REVIEW

**Comment by paul-soporan** [comment]
Is there a reason for not exposing [all of these packages](https://github.com/yarnpkg/berry/blob/20a3fdfe6ef88bf611a5b3af21abe24c86add204/packages/yarnpkg-builder/sources/data/dynamicLibs.ts#L1) as modules when running through Node?

**Comment by arcanis** [comment]
No, they probably should - at the moment they aren't because the list is in a different package, so the CLI doesn't know which ones to expose (and it doesn't depend on all of them, which is another problem 🤔).

**Comment by paul-soporan** [comment]
From what I can see, `@yarnpkg/cli` currently depends on all of the libs listed [in `@yarnpkg/builder`](https://github.com/yarnpkg/berry/blob/20a3fdfe6ef88bf611a5b3af21abe24c86add204/packages/yarnpkg-builder/sources/data/dynamicLibs.ts#L1). What do you think about moving the list to `@yarnpkg/cli` and extending it in `@yarnpkg/builder` if necessary?

**Comment by arcanis** [comment]
Yep, I think it makes sense. I've pushed a commit in this direction, let's see if the tests are happy.

**Pull request merged**
