### PR TITLE
fix(pnp): esm - return undefined source for commonjs

### PR DESCRIPTION
**Pull request by merceyz**
**What's the problem this PR addresses?**

The ESM loader always returns a source which after https://github.com/nodejs/node/pull/47999 landed causes stuff to break.

**How did you fix it?**

Return undefined source for commonjs modules

**Checklist**
- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).
- [x] I have set the packages that need to be released for my changes to be effective.
- [x] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

**Comment by merceyz** [comment]
Use Node.js nightly and run `yarn` in this repo, I've added a test so we can validate it regardless of what this repo uses in the future.

**Comment by arcanis** [comment]
That's what I did, but as of 62b2cf30f2d1326dde9d4bc047f5611f17c4a20f I couldn't repro 🤔

**Comment by merceyz** [comment]
I tested with https://github.com/nodejs/node/commit/2557932db2392e05d684905155123fac224c9cc9 on Windows if that helps.

**Comment by arcanis** [comment]
Indeed; a minimal repro is:

```
node --loader ./loader.mjs <(echo '!!console.log(require.cache)')
```

```ts
import fs from 'fs';
import {fileURLToPath} from 'url';

export async function load(urlString, context, nextLoad) {
  return {
    format: `commonjs`,
    source: fs.readFileSync(fileURLToPath(urlString), `utf8`),
    shortCircuit: true
  };
}
```

**Comment by arcanis** [comment]
Relevant thread: https://openjs-foundation.slack.com/archives/C053UCCP940/p1692798777127519

**Pull request merged**
