### PR TITLE
fix: set timestamp to a higher value to handle timezones

### PR DESCRIPTION
**Pull request by merceyz**
**What's the problem this PR addresses?**

The timestamp we use for packing is the minimum value zip can store, but due to timezone shenanigans the value is either valid or invalid depending on which timezone you reside in.

See https://github.com/babel/babel/issues/12125#issuecomment-708689209 for more details

Fixes https://github.com/yarnpkg/berry/issues/1882
ref https://github.com/yarnpkg/berry/pull/1885

cc @nicolo-ribaudo @JLHwung

**How did you fix it?**

Move the timestamp away from the minimum value and regenerate the cache.
The timestamp is now `1984-06-22T21:50:00.000Z` (456789000 Unix Timestamp)

**Checklist**
- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).
- [x] I have set the packages that need to be released for my changes to be effective.
- [x] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

**Comment by andreialecu** [comment]
Question: seems like this would invalidate the local cache, and essentially replace the cached packages with an identical copy with a different file name?

Does it explode the git repo storage size, or is git smart enough to see these as renames for push/pull purposes?

I'm concerned of effects to my own repositories which are already pretty huge because of caching the deps, especially in relation with https://github.com/yarnpkg/berry/issues/180

**Comment by Larry1123** [comment]
@andreialecu it should not invalidate anything already in the cache. Git store objects by their content hash, if the file is changed it has a new hash, if the path is changed it is the same hash, as the content is the same. This change will create new hashes as the timestamp value in the zip has changed. Yarn tries it best to reuse what it in the cache and only update if it would be replacing the file as it is.

**Comment by andreialecu** [comment]
Are the zips the same though or is the timestamp applied to files within the zip, hence changing the binary data itself?

**Comment by larixer** [comment]
@andreialecu Don't you see that 5000 files changed in this PR? :)

**Comment by arcanis** [comment]
As for any bugfix related to the tarball generation, this will cause all packages that would be covered by this change to be regenerated (and the cache to be updated). That said, it's already fairly rare, and will be even more so as the time passes and we fix annoying issues like this one, which affect *all* packages (rather than a very small subset as is usually the case).

In any case, this isn't a blocker (it'll transparently update the cache), so we can merge once the tests pass.

**Comment by andreialecu** [comment]
Could the timestamp be applied on unzip/by the virtual filesystem as a custom "hack" around this and not change the zip contents?

**Comment by nicolo-ribaudo** [comment]
> Could the timestamp be applied on unzip/by the virtual filesystem as a custom "hack" around this and not change the zip contents?

No, because yarn can't control the unzipping process of every published packages. Even if I publish with yarn, my users could be using `pnpm`, `npm` or others.

**Pull request closed without merging**
