### PR TITLE
Updates the patch and bump TS

### LINKED ISSUE #1278: [Bug] @yarnpkg/core definitions uses ../../yarnpkg-fslib/sources
- [ ] I'd be willing to implement a fix

**Describe the bug**

I'm trying to implement yarn 2 in renovate: https://github.com/renovatebot/renovate/pull/6045
Importing @yarnpkg/core throws these errors:
##[error]node_modules/@yarnpkg/core/lib/MultiFetcher.d.ts(7,64): error TS2307: Cannot find module '../../yarnpkg-fslib/sources'.
##[error]node_modules/@yarnpkg/core/lib/VirtualFetcher.d.ts(6,64): error TS2307: Cannot find module '../../yarnpkg-fslib/sources'.
##[error]node_modules/@yarnpkg/core/lib/VirtualFetcher.d.ts(8,35): error TS2307: Cannot find module '../../yarnpkg-fslib/sources'.
##[error]node_modules/@yarnpkg/core/lib/VirtualFetcher.d.ts(10,28): error TS2307: Cannot find module '../../yarnpkg-fslib/sources'.
##[error]node_modules/@yarnpkg/core/lib/VirtualFetcher.d.ts(11,28): error TS2307: Cannot find module '../../yarnpkg-fslib/sources'.
##[error]node_modules/@yarnpkg/core/lib/VirtualFetcher.d.ts(15,50): error TS2307: Cannot find module '../../yarnpkg-fslib/sources'.
##[error]node_modules/@yarnpkg/core/lib/structUtils.d.ts(91,66): error TS2307: Cannot find module '../../yarnpkg-fslib/sources'.

You can also see the build here: https://github.com/renovatebot/renovate/pull/6045/checks?check_run_id=636048215

**To Reproduce**

The _minimal_ information needed to reproduce your issue (ideally a package.json with a single dep). Note that bugs without minimal reproductions might be closed.

IMPORTANT: We strongly prefer reproductions that use Sherlock. Please check our documentation for more information: https://yarnpkg.com/advanced/sherlock

No reproduction, sorry

### PR DESCRIPTION
**Pull request by arcanis**
**What's the problem this PR addresses?**

Fixes #1278

**How did you fix it?**

Implementation here:
[https://github.com/microsoft/TypeScript/compare/v3.9.2...arcanis:mael/pnp-dev#diff-aa86ac6315ba3e1d25a9a1789f7f5a78R318-R398](https://github.com/microsoft/TypeScript/compare/v3.9.2...arcanis:mael/pnp-dev#diff-aa86ac6315ba3e1d25a9a1789f7f5a78R318-R398)

We now query the PnP API when the path doesn't contain a `node_modules`. This way, we can obtain the package name even for workspaces, links, and portals.

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [ ] I have verified that all automated PR checks pass.

### CODE REVIEW

**Comment by regevbr** [comment]
I confirm this PR fixes the issue!

**Comment by regevbr** [comment]
@arcanis do i need to test again?

**Comment by arcanis** [comment]
Nope, I'm just trying to find out why the tests aren't passing on Windows 🙂

**Comment by regevbr** [comment]
Oh, bummer... Didn't look at the CI but maybe it is related to the path separator difference and the patch you introduced?

**Comment by arcanis** [comment]
Done - there's one interesting side-effect to my diff, I'm not sure whether it should be considered as intended or not: take `RunInstallPleaseResolver.ts` and add a line like `export type Foo = Configuration`. Since `Configuration` isn't imported yet, VSCode will suggest to import it from `@yarnpkg/core`, instead of what was previously `./Configuration`.

**Comment by arcanis** [comment]
Of note, to fix this we would need to know who's asking for the package name (so that we could use the relative path when it comes from the same workspace). It seems difficult to implement with minimal changes given how TS is currently designed though, so I think it'll be wontfix until TS gets native support for PnP.

**Comment by regevbr** [comment]
won't fix on the main issue or what you just described?

**Comment by arcanis** [comment]
What I described. I'll fix this PR shortly.

**Comment by regevbr** [comment]
I see that the 2nd parmater to tryGetModuleNameAsNodeModule ocntains the source directory... Mabye we can use it to see if we should not interfer?

**Comment by regevbr** [comment]
@arcanis you want me to look into the issue later tonight?

**Comment by arcanis** [comment]
No it should be fine, thanks, I have a fix in the pipeline 👍

**Pull request merged**
