### PR TITLE
feat: minify plugins

### LINKED ISSUE #1013: [Feature] .yarn/{plugins, releases} stored compressed/minified
**Describe the user story**

So, this may be a "wontfix", but asking anyway... Currently we are required (or rather recommended) to check in the `.yarn/{plugin. releases}` folders. The negative side effect of this is -

- we are adding a lot of lines on each single commit (90K+ when adding berry + 2 plugins in my case)
- it hurts my OCD since my nice TypeScript-only repos are now showing up as "JS" due to the large number of lines of code (all caused by the plugins)

**Describe the solution you'd like**

There are 2 things that can happen -

- like the `.yarn/cache` these files can be added compressed (execution can uncompress with a small step)
- at the very least the massive plugins can be minified, they show up with something like this -

```js
/* eslint-disable*/
module.exports = {
  name: "@yarnpkg/plugin-interactive-tools",
  factory: function (require) {
                          var plugin =
  /******/ (function(modules) { // webpackBootstrap
  /******/ 	// The module cache
  /******/ 	var installedModules = {};
  /******/
  /******/ 	// The require function
  /******/ 	function __webpack_require__(moduleId) {
  /******/
  /******/ 		// Check if module is in cache
  /******/ 		if(installedModules[moduleId]) {
  /******/ 			return installedModules[moduleId].exports;
...
```

**Describe the drawbacks of your solution**

For compression, I see drawbacks in that it will add a slight delay in execution, and the actual engine may not support it out of the box.

When looking at just minifying the plugins, I don't see drawbacks - `.yarn/releases/yarn-berry.js` is nicely cleaned up from all the import gunk.

**Describe alternatives you've considered**

No alternative that I thought of, 2 approaches mentioned here. As a manual work-around have minified the plugins myself. (And then tested if they still work - some normality restored. Not scalable to all users, but solves my immediate issue)

**Additional context**

None.

### PR DESCRIPTION
**Pull request by paul-soporan**
**What's the problem this PR addresses?**

Plugins aren't currently stored minified. This means that `yarn plugin import <plugin>` sometimes produces diffs of 36000+ lines and takes up 1.4 MB+. 

Closes #1013.

**How did you fix it?**

I added a transpilation / minification step to `yarn plugin import`. The minification can be prevented by using `--no-minify`.

**Backstory**:

0) I'm going to compare sizes and execution time using `yarn plugin import version`. Before this PR: size - `1.4 MB`, execution time `➤ YN0000: Done in 1.64s`.
1) As @arcanis pointed out in https://github.com/arcanis/clipanion/pull/19, we can't just minify plugins when we build them, since we can't un-minify them for debugging purposes. It also would only apply to our plugins / other plugins build using `@yarnpkg/builder`, but not to other third-party plugins that we just download. Conclusion: The minification step **has** to be inside the `yarn plugin import` command. 
2) I initially tried using [`terser`](https://github.com/terser/terser), a popular minifier and the solution we currently use when building the bundle. Simply importing it and running `terser.minify` on the downloaded source code of the plugin proved to be a very inefficient solution: `yarn plugin import version` - `➤ YN0000: Done in 8.04s`. Conclusion: We can't rely on conventional JS-based solutions. They are very slow and inefficient.
3) I then remembered that I had stumbled upon [`esbuild`](https://github.com/evanw/esbuild) a few days ago, for reasons unrelated to this PR. It is a very fast javascript bundler and minifier written in Go. Simply looking at the [benchmarks](https://github.com/evanw/esbuild#benchmarks) blew my mind. I decided to try it instead of terser, to see the speed improvements for myself:
- Speed: esbuild: `➤ YN0000: Done in 1.74s`; nothing: `➤ YN0000: Done in 1.64s`
- Size (minified): esbuild: `628 KB`; nothing: `1.4 MB` (Keep in mind that `plugin-version` uses `@yarnpkg/libui`, so it bundles React and Redux)
The thing is, these stats weren't obtained by using esbuild's `JS` loader, but its `TSX` loader, with `target: 'es2017'`. This means that we would now be able to natively import plugins written in `JS/JSX/TS/TSX` without any noticeable performance downgrade. How cool is that!

Final conclusion:
- `esbuild` is the best solution for the minification / transpilation problem. It can just be run on the downloaded source code of the plugins without any significant performance downgrades.
This enables us to
  - 1) Minify plugins, greatly reducing their size
  - 2) Import plugins written in TypeScript (+ JSX)

### CODE REVIEW

**Comment by arcanis** [comment]
> * As @arcanis pointed out in [arcanis/clipanion#19](https://github.com/arcanis/clipanion/pull/19), we can't just minify plugins when we build them, since we can't un-minify them for debugging purposes. It also would only apply to our plugins / other plugins build using `@yarnpkg/builder`, but not to other third-party plugins that we just download. Conclusion: The minification step **has** to be inside the `yarn plugin import` command.

I was thinking about this - maybe we could have the plugins minified by default by the build, and implement something like `yarn import plugin from sources --no-minify exec` that would build the relevant plugin without minification? It would also be useful for people who want to use the bleeding edge plugins, since they currently require to use `from sources` with a special `--plugin` parameter 🤔

**Comment by paul-soporan** [comment]
🤔 That still wouldn't solve the problem of minifying third-party plugins. It worked for `set version` because there's a single bundle that can be built - ours. Plugins can come from many different places, and we can't control how they are built before we download them. I believe it would be better to have a consistent way of dealing with all of them, not only ours.

Can you detail a bit about what you think about my solution? I feel that my solution would open the door to many possibilities with the fast transpilation / minification and it could make the build step for some third party plugins optional, so I don't currently understand why your solution would be worth it over mine. What do you think?

**Comment by arcanis** [comment]
Things I want to check:

- How much size does it add to the main bundle?
- What happens if users use syntax that ESBuild doesn't understand?

For the first one it seems fairly lightweight judging by the zip size, but better check the bundle itself (since we won't benefit from compression). For the second one, we'll at least need to try/catch the minification process and write a line to indicate whether it ran or not.

> Can you detail a bit about what you think about my solution? I feel that my solution would open the door to many possibilities with the fast transpilation / minification and it could make the build step for some third party plugins optional, so I don't currently understand why your solution would be worth it over mine. What do you think?

It's a good solution - I'm always worried when adding a minifier to a package manager, though, it feels conceptually dangerous / a slippery slope 😛

**Comment by paul-soporan** [comment]
So, after failing to get `esbuild` to work and discussing more with @arcanis on Discord, we decided to scrap this idea. There are quite a few problems with it, and I didn't realize that from the start, unfortunately:
- `esbuild` uses native dependencies, which means that it can't be bundled with Webpack
- There's `esbuild-wasm`, but it still can't be bundled with Webpack, since it's just a wrapper around a CLI written in Go and shipped in Wasm. Yarn is distributed as a single binary, so we can't ship additional Wasm files that the binary would execute.
- The only other possibility would be if `esbuild` exposed a Wasm API that we could bundle with `wasm-loader` and use. We stopped here, as the `esbuild.wasm` file that `esbuild-wasm` ships with is already 4.5 MB, so it would increase our bundle size significantly.

In the end, using `esbuild` really was too good to be true. It would have been awesome to be able to transpile and minify plugins directly when importing them with an additional 0.1 seconds. Even if we used the Wasm build and it would be 10 times slower, that would still be only 1 second, compared to the 7 seconds terser takes to just minify a plugin's source.

We'll probably just minify our own plugins by default when building them with Webpack, but, unfortunately, we won't be able to minify third-party plugins ourselves when importing them.
I'll close this PR for now (as I'd have to revert everything) and open another one when I have a working solution ready.

**Pull request closed without merging**
