### PR TITLE
fix(compat): update patch for `typescript@5.0.1-rc`

### PR DESCRIPTION
**Pull request by merceyz**
**What's the problem this PR addresses?**

The PnP compatibility patch for TypeScript doesn't apply to `typescript@5.0.1-rc`.

Ref https://github.com/microsoft/TypeScript/pull/35206

**How did you fix it?**

Rebased https://github.com/yarnpkg/berry/pull/5210 onto the `5.0.1-rc` release.

**Checklist**
- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).
- [x] I have set the packages that need to be released for my changes to be effective.
- [x] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

**Comment by chentsulin** [comment]
@merceyz Is there any plan to port this patch back to v3 release?

**Comment by merceyz** [comment]
I've already backported it, it's the commit you can see above your comment, and prepared the next release, it's waiting on @arcanis to have time to create the release.

**Comment by chentsulin** [comment]
@arcanis TS 5 will be released at 3/16 (very soon). Good to see if it works with Yarn 3.

https://github.com/microsoft/TypeScript/issues/51362

**Comment by wegry** [comment]
TS 5 has been released. https://github.com/microsoft/TypeScript/issues/51362#issuecomment-1472435340

**Comment by merceyz** [comment]
Yarn v3.5.0 has been released
```sh
yarn set version berry
```

**Pull request merged**
