### PR TITLE
build: use more explicit node version

### PR DESCRIPTION
**Pull request by paul-soporan**
**What's the problem this PR addresses?**

When building things, we set the ESBuild target to `node14`, which requires the output to be compatible with all Node versions `>=14.0.0`, but we only support Node `>=14.15.0`.

**How did you fix it?**

Changed the target to `node14.15.0`.

This makes ESBuild stop transpiling optional chaining and nullish coalescing, improving the bundle size.

CLI bundle size:
- Before: `2813589 bytes`
- After: `2808903 bytes` 
- Improvement: `-4.57 KiB` / `0.16%`

**Checklist**

- [X] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [X] I have set the packages that need to be released for my changes to be effective.

- [X] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

**Comment by merceyz** [comment]
> This makes ESBuild stop transpiling optional chaining and nullish coalescing

It's odd that it transpiled them in the first place since both of those has been supported since [Node.js 14.0.0](https://node.green/#ES2020)

**Comment by paul-soporan** [comment]
:thinking: Indeed, didn't know that. Since searching for `?.(...` doesn't yield anything in the codebase I'd just consider this ESBuild bug a feature for now and avoid updating for now. :sweat_smile:

Or perhaps ESBuild could detect optional function calls followed by the spread operator separately and only transpile those (I'll open a feature request later).

**Comment by arcanis** [comment]
Could we keep this version in a single place? Perhaps a `.node-build-version` at the root?

**Comment by merceyz** [comment]
I'll close this since the output is identical in `esbuild@0.15.15`.

**Pull request closed without merging**
