### PR TITLE
Add mention of `prepare`

### PR DESCRIPTION
**Pull request by RobertLowe**
🚀 🚀 🚀 

**What's the problem this PR addresses?**
Add mention of `prepare`

...

**How did you fix it?**
Add mention of `prepare`

...

**Checklist**
- [X] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).
- [X] I have set the packages that need to be released for my changes to be effective.
- [X] I have verified that all automated PR checks pass.

### CODE REVIEW

**Comment by arcanis** [comment]
Hi, thanks for the contribution! However, we don't support `prepare`. Instead, as the documentation suggests, package artifacts should be created in the `prepack` script, which is called when cloning a repository. From the documentation:

> Note that we don't support every single lifecycle script originally present in npm. This is a deliberate decision based on the observation that too many lifecycle scripts make it difficult to know which one to use in which circumstances, leading to confusion and mistakes. We are open to add the missing ones on a case-by-case basis if compelling use cases are provided.

**Comment by RobertLowe** [comment]
@arcanis 1.x supports it https://github.com/yarnpkg/yarn/pull/3004 ... `prepack` just seems to be a renamed `prepare` then no?

**Comment by arcanis** [comment]
No, `prepack` has always existed (cf the [npm doc](https://docs.npmjs.com/misc/scripts)).

> It also feels weird that the public docs would be for 2.x, when 1.x is what's stable on npm...?

Yarn 2 is the latest stable. We simply don't use npm to distribute it (or rather, it's more complex than this, cf our [install docs](https://yarnpkg.com/getting-started/install#global-install)).

**Comment by RobertLowe** [comment]
I'll close this, hopefully it will help someone in the future

**Pull request closed without merging**
