### PR TITLE
Fix pnpify sdk version number

### PR DESCRIPTION
**Pull request by deini**
Now generating proper version number.

### CODE REVIEW

**Comment by arcanis** [comment]
Thanks! Can you also add the missing `typescript` peer dependency?

**Comment by deini** [comment]
Sure, will add 💃

**Comment by deini** [comment]
Interesting, looks like adding the peer dependency is causing an infinite loop 🤔

**Comment by arcanis** [comment]
Oh no 😮 

On the top of my head the most likely culprit for any kind of infinite loop related to peer dependencies would be the resolver, and particularly [this function](https://github.com/yarnpkg/berry/blob/master/packages/berry-core/sources/Project.ts#L648-L768). I can take a look at it next week!

**Comment by arcanis** [comment]
👌

**Pull request merged**
