### PR TITLE
Add baseline text to selected packages in upgrade-interactive script

### PR DESCRIPTION
**Pull request by darthtrevino**
**What's the problem this PR addresses?**
One of the issues with the upgrade-interactive script is that it can be difficult to track the selected library and what versions are recommended for it. I suspect that this difficulty is amplified for users with impaired vision. 

~~One thing that I'm thinking about with this PR is sending the baseline underline through the version candidates area as well. I'll probably work on that next.~~ The latest commits implement baselines through all version labels

**How did you fix it?**
I added some padding text to update line-items and used the `dimColor` attribute to modulate it's brightness in response to the `active` prop. This required updating the `ink` library.
...

**Checklist**
- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).
- [x] I have set the packages that need to be released for my changes to be effective.
- [x] I will check that all automated PR checks pass before the PR gets reviewed.
upgrade-baselines-2

### CODE REVIEW

**Comment by darthtrevino** [comment]
Here's how it looks with the baseline expanded through the version tags

upgrade-baselines-allthrough

**Comment by darthtrevino** [comment]
It won't break my heart if you don't end up using this particular PR, but I thought I would at least try to convey what I thought would be a useful improvement. Hopefully something like this can land in the future

**Comment by arcanis** [comment]
I wasn't convinced with the gif, but after trying it out it's a really nice improvement! I think my main question is regarding Ink: is it necessary to update it? It seems to have quite a bunch of breaking changes, and I think I would prefer if it was done in a separate PR 🤔

In particular, the `keypress` change seems impractical as it impacts a lot of files...

**Comment by darthtrevino** [comment]
The main benefit I got from upgrading Ink was the 'dimColor' prop on the baseline pieces of text.

I agree on the keypress library not being ideal, including it was a bit of a hack. 

I'll take another crack at this idea without upgrading Ink

**Comment by arcanis** [comment]
Sounds good! If it turns out to be too difficult, at least I think it would be worth it to abstract in a `useKeypress` hook.

**Pull request closed without merging**
