### PR TITLE
fix(shell): string syntax compatible

### LINKED ISSUE #1356: [Bug] Backslashes shouldn't escape characters in shell strings
- [ ] I'd be willing to implement a fix

**Describe the bug**

`@yarnpkg/shell` doesn't handle escaped characters

**To Reproduce**

```js repro
await packageJsonAndInstall({
	scripts: {
		echo: "node -e \"console.log('\\u001b[35m\\u001b[1mLove Swiper? Support Vladimir\\'s work by donating or pledging on patreon:\\u001b[22m\\u001b[39m\\n > \\u001b[32mhttps://patreon.com/vladimirkharlampidi\\u001b[0m\\n')\"",
	},
});

await expect(yarn('echo')).resolves.not.toContain('Invalid or unexpected token');

```

**Environment if relevant (please complete the following information):**

 - OS: Microsoft Windows [Version 10.0.18362.628]
 - Node version v12.16.1
 - Yarn version 3.0.1-git.20210818.hash-5a27c83b8

### LINKED ISSUE #3657: [Bug?]: regression in 3.1.0 with packages that do a postinstall with escape characters (guess)
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Regression: 3.0.2 -> 3.1.0 installing package `zapatos`

Zapatos has a postinstall that returns a console.warn with some escape codes. I have attached this output to additional context. FYI, this version has been installing successfully until 3.1.0.

### To reproduce

```js
await expect(packageJsonAndInstall({
    dependencies:   {[`zapatos`]: `5.0.0`}
})).resolves.toBeTruthy();
```

### Environment

```shell
System:
    OS: macOS 12.0.1
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 16.11.1 - /private/var/folders/nr/ql7059057gl192wskv8v87c40000gn/T/xfs-6ca04ea8/node
    Yarn: 3.1.0 - /private/var/folders/nr/ql7059057gl192wskv8v87c40000gn/T/xfs-6ca04ea8/yarn
    npm: 8.0.0 - /opt/homebrew/bin/npm
  npmPackages:
    jest: 26.6.0 => 26.6.0
```

### Additional context

```
# This file contains the result of Yarn building a package (zapatos@virtual:6bb548c6ce5c7b1d385a1cd6255b9a8c4c3a66b489e768fa7174cd7d21190aa0a09dd35c4325bf553909a061c971e468803ae79b67c6517473809c4f3c186e27#npm:5.0.0)
# Script name: postinstall

[eval]:1
console.warn('>>> [1;33mZapatos was installed or upgraded. Please (re-)run [1;32mnpx zapatos[1;33m.[0m <<<
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Invalid or unexpected token
    at new Script (node:vm:100:7)
    at createScript (node:vm:257:10)
    at Object.runInThisContext (node:vm:305:10)
    at node:internal/process/execution:81:19
    at [eval]-wrapper:6:22
    at evalScript (node:internal/process/execution:80:60)
    at node:internal/main/eval_string:27:3
```

### PR DESCRIPTION
**Pull request by cuyl**
**What's the problem this PR addresses?**

The shell parser is still not compatible with bash in some cases.

Closes #1356
Closes #3657

**How did you fix it?**

Make the parser behave like bash by reducing escape characters of single-quote and double-quote that bash does not do.

**Checklist**
- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [ ] I have set the packages that need to be released for my changes to be effective.

- [x] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

**Comment by cuyl** [comment]
Some times the process exit before the stdout data received, maybe we should wait stdout close but I found the stdout  never end in this case.

**Comment by cuyl** [comment]
stdoutLock close ignored 
https://github.com/yarnpkg/berry/blob/e95a1df42f6b94fc7a308af1b038e43c7278ac5a/packages/yarnpkg-shell/sources/pipe.ts#L275-L278
https://github.com/yarnpkg/berry/blob/e95a1df42f6b94fc7a308af1b038e43c7278ac5a/packages/yarnpkg-shell/sources/pipe.ts#L144-L154

**Comment by arcanis** [comment]
@cuyl Node streams are hell; if I remember correctly, the `ProtectedStream` are intended to avoid closing the streams because 1/ the execution code will do it (I don't remember where...) 2/ we don't want to actually close the real stdin/out/err if they reach this place. But it's very possible there's a bug somewhere - would be nice to rework this code to make it closer from a typical shell, with dup2-style execution pipeline.

**Comment by arcanis** [comment]
Thanks @cuyl !

**Pull request merged**
