### PR TITLE
Use React.memo on function components

### PR DESCRIPTION
**Pull request by darthtrevino**
**What's the problem this PR addresses?**
This PR introduces some minor performance improvements that can be gained from using `React.memo` by default on function components. This will prevent these components from re-rendering on every render cycle unless their props change or their hooks fire internally. 

**Checklist**
- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).
- [x] I have set the packages that need to be released for my changes to be effective.
- [x] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

**Comment by arcanis** [comment]
Does it yield actual perf improvements? I was under the impression that `memo` wasn't useful except when doing heavy calculations, especially since Ink rerenders the whole viewbox anyway.

**Comment by darthtrevino** [comment]
As I understand it, there are two parts of react rendering: react code into a virtual dom, and then flushing the virtual dom into the ui (fiber). 

I tend to always use memo on function components: it's analogous to the old PureComponent class. It stops components from needlessly rebuilding vdom in the first phase. 

Even if ink is always repainting, I think you still get a little boost out of a stable virtual dom

**Comment by arcanis** [comment]
I think I'd prefer to not use `memo` by default (except where it helps) than use it everywhere (except where it's detrimental). It keeps the contribution bar a little bit lower, if that makes sense.

Also cf this thread: https://twitter.com/Vjeux/status/1083902396932059136

**Comment by darthtrevino** [comment]
That's fair, thanks @arcanis

**Pull request closed without merging**
