### PR TITLE
fix(pnp): ensure `URL` is imported on Node.js < 20

### PR DESCRIPTION
**Pull request by merceyz**
**What's the problem this PR addresses?**

Before https://github.com/nodejs/node/pull/46904 using a custom global URL class wasn't supported by `fileURLToPath`.

Closes https://github.com/yarnpkg/berry/pull/6030
Fixes https://github.com/yarnpkg/berry/discussions/5915

**How did you fix it?**

- Created a rollup plugin to ensure that the builtin URL class is always used on Node.js < v20.
- Removed all imports of `URL` since it's a global and to avoid mixing custom and builtin URL class instances.

**Checklist**
- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).
- [x] I have set the packages that need to be released for my changes to be effective.
- [x] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

**Comment by baeharam** [comment]
@merceyz 

Is there a way to install this version? I need this job to fix `yarn test`. Thanks for your work!

**Comment by merceyz** [comment]
A new release will be created soon but until then you can run

```sh
yarn set version from sources
```
https://yarnpkg.com/cli/set/version/from/sources

**Comment by baeharam** [comment]
@merceyz 

This job was released in 4.1.0, but I need 3.x.x version of berry. Is there any plan to release this job in 3.x.x version?

**Comment by pay-mazino-urek** [comment]
@merceyz 

Can I install this commit in 3.x.x version? When I install `master` version, 4.x.x is installed which I don't want.

**Pull request merged**
