### PR TITLE
fix: support fragment in tar regex

### LINKED ISSUE #5434: [Bug?]: Yarn install fails when weird hash character in package name
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Trying to install some internal packages fails with yarn 3.5.1 with the following error:

```sh
➤ YN0001: │ Error: @company/package@npm:^5.1.0: @company/package@npm:5.1.0::__archiveUrl=https%3A%2F%2Fcompany.org%2Fapi%2Fnpm%2Fnpm-mirror%2F%40company%2Fpackage%2F-%2F%40company%2Fpackage-5.1.0.tgz%23 isn't supported by any available resolver
```

As the URL implies, there is a weird `%23` as in the hash character in the end. Is this somehow related to the package or should yarn remove (trim?) all extra characters from the package name before resolving? 

### To reproduce

Couldn't find any public package that fails to install like this

### Environment

```shell
System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.20.0 - /private/var/folders/jx/6_rpw_wd31bc2sxg5brx5j780000gn/T/xfs-6f6b5695/node
    Yarn: 3.5.1 - /private/var/folders/jx/6_rpw_wd31bc2sxg5brx5j780000gn/T/xfs-6f6b5695/yarn
    npm: 8.19.4 - /opt/homebrew/opt/node@16/bin/npm
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by drodil**
**What's the problem this PR addresses?**
fixes #5434

...

**How did you fix it?**
Add support for tar resolver URLs with fragments

...

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

**Review by merceyz — CHANGES_REQUESTED** [review]
Thanks for the PR, please add a test to https://github.com/yarnpkg/berry/blob/c9455feaed19e65d6256a7129b5a88484dfdd174/packages/acceptance-tests/pkg-tests-specs/sources/protocols/npm.test.js so this doesn't happen again.

**Comment by drodil** [comment]
@merceyz I can try to do that but it might take some as there's no test for the query parameters in the URL either and it can be that it requires a lot of changes to the current way tests are set up. Any pointers on how this could be easily tested are more than welcome!

**Comment by drodil** [comment]
I mean that I can do the test so that I use URL in the version like it's allowed in `package.json`, but the problem is that I do not know the port of the package server at the time of making the environment:

```ts
 makeTemporaryEnv(
        {
          dependencies: {[`unconventional-tarball`]: `https://localhost/unconventional-tarball.tgz#fragment`},
        },
```

Any ideas?

**Comment by merceyz** [comment]
You can call [`startPackageServer`](https://github.com/yarnpkg/berry/blob/13b7f823d3b0eb1841b996a46b4742df7413ab90/packages/acceptance-tests/pkg-tests-core/sources/utils/tests.ts#L321-L740) to get the URL of the registry.

**Pull request merged**
