### PR TITLE
feat(core): support https proxy

### PR DESCRIPTION
**Pull request by merceyz**
**What's the problem this PR addresses?**

We currently only support http proxies

Fixes https://github.com/yarnpkg/berry/issues/2250

**How did you fix it?**

Replaces `tunnel` with `hpagent`

**Checklist**
- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).
- [ ] I have set the packages that need to be released for my changes to be effective.
- [x] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

**Comment by merceyz** [comment]
@suhaig If you're able to, could you test if this PR solves #2250?
You can test it using `yarn set version from sources --branch 2250` or download the bundle from the `Generating Artifacts` CI job

**Comment by suhaig** [comment]
@merceyz, it was `--branch 2252`, but it works when `caFilePath` specified and does not work when `caFilePath` not specified.

**Comment by merceyz** [comment]
Oops, my bad. So are you using a https proxy and therefor this fixes your issue? In your config you redacted even the protocol so this was just guesswork

**Comment by suhaig** [comment]
My corporate proxy URL starts with `http`. The same proxy is used for both `http` and `https` addresses. Even if guesswork, it works well :) Thank you.
Now the question: when will it released? :)

**Comment by merceyz** [comment]
I would like to understand why this fixes #2250, could you share your whole config but redact the sensitive parts only?
(i.e. `httpProxy: "http://domain.com:1234"` etc)

**Comment by suhaig** [comment]
Ok, but it's not very interesting:
```
yarnPath: ".yarn/releases/yarn-berry.cjs"
enableTelemetry: false
defaultSemverRangePrefix: ""
httpProxy: "http://domain:80"
httpsProxy: "http://domain:80"
caFilePath: "./corporate-cert.crt"
```

**Comment by merceyz** [comment]
What's the `caFilePath` for if you're not changing the registry?

**Comment by suhaig** [comment]
Because our proxy changes the certificate, so my company can look into HTTPS traffic.

**Comment by merceyz** [comment]
I'll close this for now since I don't have a way to test it

**Pull request closed without merging**
