### PR TITLE
fix(pnp): Avoid infinite loop in findApiPathFor

### PR DESCRIPTION
**Pull request by keithlayne**
**What's the problem this PR addresses?**

This is definitely a corner case.  The error only manifests when
`findApiPathFor` is called with a `paths` option that includes the empty
string when the CWD does not contain a `.pnp.js`.  The way that the
directory tree is iterated  is to use `path.dirname`, with the root (`/`) as 
the terminating case.  `path.dirname('')` returns `'.'` as does
`path.dirname('.')`, so the loop never ends.

**How did you fix it?**

The fix is to resolve the path before trying to walk the tree.

### CODE REVIEW

**Comment by arcanis** [comment]
Oh interesting! I think a better fix might be to call `ppath.resolve` on the path, otherwise the search will stop early. Can you do that and add a small test in `pnp.test.js`?

**Comment by keithlayne** [comment]
yeah, just saw your message, took a while to clone :)  Will do a test.

**Comment by keithlayne** [comment]
BTW when done what should I pick for `yarn version check -i`?  Or do you manage that more directly?

**Comment by keithlayne** [comment]
@arcanis Apparently this fix doesn't work on windows.  Plus, the integration tests seem to be timing out correctly - when you run them locally (before the fix) they time out and jest exits.  In CI it seems like (from the cancelled windows jobs) that everything runs fine, fails with a timeout, and then never terminates.  I *thought* it was fairly safe to trigger the infinite loop in Jest because of it's timeout stuff.

Anyway, this fix doesn't seem to work on windows, and I don't know of an easy way for me to debug that.  Logically though, `toPortablePath('')` just returns an empty string on both platforms, and then `ppath.resolve('')` should resolve to the working dir.  Does `path.posix.resolve` somehow have different behavior on windows?

**Comment by keithlayne** [comment]
@arcanis I think maybe the right thing to do here is:

```ts
let next = npath.toPortablePath(npath.resolve(modulePath));
```

i.e. resolve it natively before converting to a posix path.  I can't imagine what's going on in windows (can't test) but can only assume things are acting differently there with the empty string.

**Comment by arcanis** [comment]
I'm like 99% sure this is because `path.posix.relative` doesn't take into account that `process.cwd()` isn't a posix path when called on Windows. I've pushed a fix into the fslib, which I think is the right layer to normalize this kind of behavior.

> BTW when done what should I pick for `yarn version check -i`? Or do you manage that more directly?

It's faster when contributors bump the versions, this way I often don't have to checkout the branch locally 😄 Note that in this case we don't need to bump aaaall the plugins, just the affected ones + the CLI (so that a new CLI bundle gets generated). Cf my fix.

**Comment by keithlayne** [comment]
booyah.  Sorry I didn't save you any time on this.  But yeah, I was starting to think that the solution should have been at a higher level.  Thanks for figuring that out!

**Comment by arcanis** [comment]
Well, the bug was a quite devilish one! Thanks for digging in 🛠

**Pull request merged**
