### PR TITLE
Skips incompatible package building or linking

### PR DESCRIPTION
**Pull request by larixer**
**What's the problem this PR addresses?**

Packages can be os and cpu-specific. This can be specified via `os` and `cpu` properties in `package.json`. It is not safe to attempt to build such packages on an incompatible platform. This can be workaround now via `dependenciesMeta -> built`, but it would be better to not even attempt build them by default by pnp linker and to not link it by default by nm linker. Yarn 1 does not link incompatible packages at all.

**How did you fix it?**

I have adjusted both linkers to check `os` and `cpu` manifest fields. Pnp linker will not build incompatible packages, but still unplugs them as before. Nm linker will not link them at all to match the behaviour of Yarn 1 and reduce nm size on disk

### CODE REVIEW

**Comment by larixer** [comment]
@arcanis I'm not totally sure how to implement this right, I have pushed implementation which seems to work, but there are many factors that need to be taken into account. Please share your thoughts when you have a chance.

**Comment by larixer** [comment]
Probably we should link as usual for pnp, but not launch the build scripts for incompatible packages. And for the nm linker we should not link incompatible packages.

**Comment by arcanis** [comment]
I'd personally tend to avoid doing different linking on different archs, as it would lead to non-deterministic installs. What do you think @larixer? Should it be pursued to completion?

**Comment by larixer** [comment]
Switched status back to draft. The things I'm going to address:
1. For pnp linker the build scripts only should be skipped for incompatible packages
2. For nm linker the linking will be skipped, as already done in this PR
3. Fix a condition for choosing external dependencies linking, I think I have broken the corresponding `if` inside `linkEverything`

**Comment by larixer** [comment]
@arcanis The PR is ready for review

**Pull request merged**
