### PR TITLE
docs(plugins): fix target config file for plugins

### PR DESCRIPTION
**Pull request by lirantal**
I think the original statement meant to drive the user to make the change in `.yarnrc.yml` so I updated accordingly.

### CODE REVIEW

**Comment by lirantal** [comment]
@arcanis was that correct to update the html files or are writing docs in another format that then gets converted into these files? I looked around and didn't find any other source so wasn't sure.

**Comment by arcanis** [comment]
@lirantal Docs are written in the `gatsby` directory; the plugin tutorial is [here](https://github.com/yarnpkg/berry/blob/master/packages/gatsby/content/advanced/plugin-tutorial.md), for instance.

Note that there's another outdated thing on the page: we recently switched the CLI framework to a more modern one, which comes with a different API. I'll have to update this section 🙂

**Comment by lirantal** [comment]
oh so that's where it was hidden!
a big part of me assumed and prayed that no one really manually writes that HTML :D

thanks I'll update this PR and yeah I saw the diff in the CLI change between working on the berry repo itself and installing the release berry v2 version on another repo

**Comment by arcanis** [comment]
👍

**Pull request merged**
