### PR TITLE
fix(sdks): update neovim zipfile paths in TypeScript SDK

### PR DESCRIPTION
**Pull request by stephank**
**What's the problem this PR addresses?**

It appears that as of zip.vim v32 the [URL format has changed](https://github.com/neovim/neovim/blob/c0efe49e78eca3a17a5934cc283199122d081467/runtime/doc/pi_zip.txt#L105-L107). This version is included in Vim as of [v8.2.3606](https://github.com/vim/vim/commit/519cc559b08b800edc429688aece7ad6a00d41eb) and Neovim as of [v0.6.0](https://github.com/neovim/neovim/commit/c0efe49e78eca3a17a5934cc283199122d081467), I believe.

I don't have a working setup from before this change, but believe the format was `/path/foo.zip:/path/foo.zip::bar.js`, while now, browsing a zipfile in Neovim opens paths like `zipfile:///path/foo.zip::bar.js`.

**How did you fix it?**

- In `toEditorPath`, I changed the Neovim case to create `zipfile:///path...` URLs.
- In `fromEditorPath`, I added a new Neovim case (previously shared with coc-nvim) to reverse the new format.

I'm unsure about backwards compatibility. I guess we would again have to send a patch to Neovim to indicate the zip.vim version in `hostInfo` or something, but that leaves at least the released Neovim versions 0.6.0 and 0.6.1 in the dark, and just seems like a big hassle. So... yeah.

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

**Comment by arcanis** [comment]
cc @xuanduc987 @tapayne88 @cometkim, in case you find yourselves affected

**Comment by tapayne88** [comment]
Thanks for the heads-up @arcanis and nice work @stephank 👏 

I think I updated the yarn docs following the Neovim 0.6 release but this looks to be a better solution. Something I would suggest is that we can now remove the code snippet from the editor guide as it's no longer required, Vim/Neovim's builtin zip handling should be sufficient for most use cases
https://github.com/yarnpkg/berry/blob/806525b549b27fcbe080c13647011bb04693a712/packages/gatsby/content/getting-started/editor-sdks.md?plain=1#L82-L125

As far as the original handling goes, I seem to remember vim expected zip files to have the format `zipfile:/path/foo.zip::bar.js` but as you say this is now `zipfile:///path/foo.zip::bar.js`. I've done a little testing on Neovim 0.5.1 with a [minimal-ish config](https://github.com/tapayne88/dotfiles/blob/219ec51e37ee218bed5acc75776abcf0fdfeb55d/dot_config/nvim/minimal.lua) and it looks to work fine with the new URI scheme (`zipfile://`).

<details><summary>A bit more detail</summary>
<p>
I can't speak to how well this will work on windows as I _think_ neovim <0.6 is working by accident on unix systems as the unzip command issues looks a little off, specifically the path that begins `///home/...`

#### 0.5.1
```
chdir(/home/tapayne88/git/yarn-pnp-demo)
line 0: sourcing "/nix/store/ak7bj4lv8yi604kj8ifq019l5mb1fza4-neovim-unwrapped-0.5.1/share/nvim/runtime/autoload/zip.vim"
finished sourcing /nix/store/ak7bj4lv8yi604kj8ifq019l5mb1fza4-neovim-unwrapped-0.5.1/share/nvim/runtime/autoload/zip.vim
continuing in BufReadCmd Autocommands for "zipfile:*/*"
:!unzip -p -- '///home/tapayne88/git/yarn-pnp-demo/.yarn/cache/@testing-library-dom-npm-7.31.2-d66ba6a14d-54fbedd1ec.zip' 'node_modules/@testing-library/dom/types/screen.d.ts' > /tmp/nvimMXFyRj/1
```

#### 0.6.1
```
chdir(/home/tapayne88/git/yarn-pnp-demo)
line 0: sourcing "/nix/store/10k3bc68v0602pvaz6m5k420q13x83g6-neovim-unwrapped-0.6.1/share/nvim/runtime/autoload/zip.vim"
finished sourcing /nix/store/10k3bc68v0602pvaz6m5k420q13x83g6-neovim-unwrapped-0.6.1/share/nvim/runtime/autoload/zip.vim
continuing in BufReadCmd Autocommands for "zipfile:*/*"
:!unzip -p -- '/home/tapayne88/git/yarn-pnp-demo/.yarn/cache/@testing-library-dom-npm-7.31.2-d66ba6a14d-54fbedd1ec.zip' 'node_modules/@testing-library/dom/types/screen.d.ts' > /tmp/nvim0wmDfP/1
```
</p>
</details>

If you're interested there is a demo repo I've got for yarn-pnp testing - https://github.com/tapayne88/yarn-pnp-demo. I've been simply opening a zipfile in neovim as the yarn -> language-server -> neovim client pipeline _should_ now preserve the original URI, something like
```
:e  zipfile:///home/tapayne88/git/yarn-pnp-demo/.yarn/cache/@testing-library-dom-npm-7.31.2-d66ba6a14d-54fbedd1ec.zip::node_modules/@testing-library/dom/types/screen.d.ts
```

Anyway, all that to say I think this is a good change!

**Comment by arcanis** [comment]
@stephank can you check if removing the sdk snippet works for you too?

**Comment by stephank** [comment]
> @stephank can you check if removing the sdk snippet works for you too?

The snippet from this link?

> https://github.com/yarnpkg/berry/blob/806525b549b27fcbe080c13647011bb04693a712/packages/gatsby/content/getting-started/editor-sdks.md?plain=1#L82-L125

I never really added this to my vim config. 🙃

**Comment by tapayne88** [comment]
> I never really added this to my vim config. 🙃

Huh that's interesting, did you have any config to URI decode the paths coming from the LSP? Something like

https://github.com/yarnpkg/berry/blob/806525b549b27fcbe080c13647011bb04693a712/packages/gatsby/content/getting-started/editor-sdks.md?plain=1#L90-L92

I can see now that you don't necessarily need vim-rzip but would have thought you'd need to do like that somewhere 🤔

**Comment by stephank** [comment]
> Huh that's interesting, did you have any config to URI decode the paths coming from the LSP? Something like

I believe this is what I solved by sending patches to typescript-language-server, and all of it should be in 0.9.6. Before, it was using `vscode-uri` to parse and serialize all URIs that went through it, but it now leaves zipfile URIs untouched. So vim sees exactly what the hooked tsserver sends.

**Comment by tapayne88** [comment]
> I believe this is what I solved by sending patches to typescript-language-server

Yeah, that's my understanding and I think your changes have definitely improved things! I had just assumed you had a working version prior to those ts-ls changes but perhaps that's not the case? (just curious😄)

I guess that does suggest the snippet can be removed from the docs @arcanis (unless you disagree @stephank)

**Comment by stephank** [comment]
> Yeah, that's my understanding and I think your changes have definitely improved things! I had just assumed you had a working version prior to those ts-ls changes but perhaps that's not the case? (just curious😄)

Ah, no, I didn't have a working setup before. I worked on these projects together.

> I guess that does suggest the snippet can be removed from the docs @arcanis (unless you disagree @stephank)

I think so, yes. I'm not familiar with rzip, and don't know what the rest of the snippet solves. (I guess recursive zips or modifying zips is not really I thing I do from vim.) It's possible the snippet is still necessary for those who want rvim? But with these changes, everything works in stock neovim, and rvim is not necessary.

**Comment by tapayne88** [comment]
Yeah, when I created the snippet I hadn't realised vim's builtin zip handling was sufficient. The rest of the snippet just handles decoding of URI components in the filename. However, since your change to the typescript language server this isn't required any more.

**Pull request merged**
