### PR TITLE
Chore: Remove virtual dir and regenerate .pnp.js, cli, pnpify

### PR DESCRIPTION
**Pull request by vlasenko**
Remove virtual dir and regenerate .pnp.js, cli, pnpify

### CODE REVIEW

**Comment by deini** [comment]
This is beautiful 😍

**Comment by vlasenko** [comment]
@deini The main PR is here:
https://github.com/yarnpkg/berry/pull/303

This one is a chore, just execution step of everything done there

**Comment by deini** [comment]
@vlasenko Yep, saw that one earlier today, I just love the fact of all the cleanup 😂

**Comment by vlasenko** [comment]
> @vlasenko Yep, saw that one earlier today, I just love the fact of all the cleanup 😂

Haha, you are not the only one who loves this fact! 👍

**Comment by arcanis** [comment]
👯‍♀️

**Pull request merged**
