### PR TITLE
Publish tarballs to repository

### LINKED ISSUE #1664: [Feature] Publish an already packed package.
- [x] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

Currently, yarn allow to publish a packet, the publish pack itself the package, then send it.
There is currently a pack command, but there is no way using yarn to send the packed package.
Currently my workaround will be to use npm to send the package using npm publish.

But I'm not satisfied with npm publish, I'm writing a tool that operate programatically with packages managers, and npm make it hard to use it (some hacks are necessary).

Yarn used to support this kind of publish: https://classic.yarnpkg.com/en/docs/cli/publish/

**Describe the solution you'd like**

yarn npm publish could have an additional, optional, argument that allow publishing a tarball.

`yarn npm publish path_to_tarball`

**Describe alternatives you've considered**

Using npm publish as a workaround, or the old yarn.

### PR DESCRIPTION
**Pull request by Kuinox**
**What's the problem this PR addresses?**

Currently yarn allow to pack a workspace in a tarball, but not to publish this tarball.

Closes #1664 

**How did you fix it?**

- Added a method in packUtils to find the manifest in a tarball.  
- Added an optional positional argument 'tarballPath'
- Publish a tarball without a workspace is one of my use cases, so I modified some internal publish methods so they don't need workspace/project

I didn't found any tests on the publish, do you want i'll write test for this ?

I removed one trigger hook that I tought didnt make a lot of sense, but I'm not sure.  (publish.ts L155)

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I have verified that all automated PR checks pass.

### CODE REVIEW

**Comment by Kuinox** [comment]
So, I think i can add again the hook [here](https://github.com/yarnpkg/berry/pull/1692/commits/796a06027e2f0226b55b7bd2fd628641bfe01eae#diff-64a021715cb7016c9bc53e6b285dce1aL179)
But I will need to modify packUtils.genPackStream so it can return the modified manifest and the pack stream.

**Comment by Kuinox** [comment]
So I tested both and it should works, I'm a bit worried because there is 0 integration tests there.
So I fixed the issue for the hook.  
Ready for review :D

**Comment by arcanis** [comment]
Honestly, I'm not sure this is a command we really want in the core ...

- On one hand, it would certainly be useful in some cases. For example, Yarn's deploy process is creating multiple times the same archive, and being able to build them once in all the steps and reuse it rather than rebuilding would improve that quite a bit.

- On the other hand, dissociating the packing from the publishing leads to annoying ambiguities. For instance, we currently look at `publishConfig.registry` to know where to publish the package. Where should we look? The one inside the packed tarball, or the one inside the project?

So I'm still on the fence about adding this ...

**Comment by Kuinox** [comment]
Well, yarn2 support pack, but doesn't support publishing these pack, there is something off there :p.

To me, we shouldn't take in account the manifest in the tarball, some build process (angular iirc ?) create a package.json and add only usefull information in it, to make the package lighter (a yarn plugin could do this too).

**Comment by olivier-spinelli** [comment]
> On the other hand, dissociating the packing from the publishing leads to annoying ambiguities. For instance, we currently look at publishConfig.registry to know where to publish the package. Where should we look? The one inside the packed tarball, or the one inside the project?

Totally agree. I'd like to submit a safe and unambiguous way of resolving this: if the publishConfig.registry is specified then it MUST be exactly the same as the one in the packed tarball. Otherwise an error is raised and the publish is aborted.

Wouldn't that do the job?

**Comment by arcanis** [comment]
It would, but there may be more such instances in the future and I'm not a fan of keeping a list somewhere (for example what about the tarball name, version, etc?).

I think an alternative I could support, very low-effort, would be to turn this into an option (rather than an arg, which is good practice anyway), and give it an unambiguous name. For example: `yarn npm publish --data-path=path/to/package.tgz`. This would convey that the *archive* is custom, but everything else is extracted from the current configuration.

**Comment by Kuinox** [comment]
SoI close this PR.

**Comment by brandonbloom** [comment]
Sorry to comment on an old issue, but I wanted to chime in and say that I was surprised to find that this functionality didn't exist. I've used this with yarn in the past to decouple builds from publish/deploy in CI pipelines and wanted to do the same thing with berry.

Without this, I have two choices that I can think of:
1) duplicate the build work in my publish job
2) add a ton of conditional steps to my existing build job.

What I'd really like to do is to have packaging occur as part of my build and upload artifacts to the next step. Then the next step wouldn't need the source code at all, all it would do is push the packages.

**Comment by merceyz** [comment]
A PR that implements what @arcanis described here https://github.com/yarnpkg/berry/pull/1692#issuecomment-675452988 would be welcome

**Pull request closed without merging**
