### PR TITLE
fix(compat): update patch for `typescript@4.9.4`

### PR DESCRIPTION
**Pull request by merceyz**
**What's the problem this PR addresses?**

The PnP compatibility patch for TypeScript doesn't apply to `typescript@4.9.4`.

Fixes https://github.com/yarnpkg/berry/issues/5125

**How did you fix it?**

Rebased https://github.com/microsoft/TypeScript/pull/35206 onto the `4.9.4` release.

**Checklist**
- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).
- [x] I have set the packages that need to be released for my changes to be effective.
- [x] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

**Review by RDIL — APPROVED** [review]

**Comment by RDIL** [comment]
Something's not right with the CI... no clue what.

**Comment by merceyz** [comment]
`ubuntu-latest` is now 22.04 which uses OpenSSL v3 which `pem` doesn't support.
https://github.blog/changelog/2022-11-09-github-actions-ubuntu-latest-workflows-will-use-ubuntu-22-04/
https://github.com/Dexus/pem/issues/316

**Comment by espoal** [comment]
@merceyz for me it's still not working. I set the latest version of yarn with `yarn set version canary`, with ts ^4.9.4

what could I be doing wrong?

**Comment by RDIL** [comment]
No new canary has been created since the PR was merged.  I just triggered a canary build, so it should be available within an hour or so.

**Pull request merged**
