### PR TITLE
fixes pnpify --sdk generation by using json5

### PR DESCRIPTION
**Pull request by DRoet**
**What's the problem this PR addresses?**
My attempt at fixing https://github.com/yarnpkg/berry/issues/521

**How did you fix it?**
Using the `json5` library to read/write the file content, so that comments are still allowed

### CODE REVIEW

**Comment by arcanis** [comment]
Nice! You just need to add `@types/json5` to the root of the repository, and run `yarn version check -i` to bump pnpify to its next prerelease 😃

**Comment by DRoet** [comment]
> Nice! You just need to add `@types/json5` to the root of the repository, and run `yarn version check -i` to bump pnpify to its next prerelease 😃

Hmmm, whenever I run `yarn version check -i` in the root directory it doesn't seem to be doing anything.

**Comment by arcanis** [comment]
You don't see this? Once you are on this screen you just have to select "prerelease" and press enter.

image

**Comment by DRoet** [comment]
nope:

```sh
DR01@PC MINGW64 /c/Users/dr01/Desktop/code/berry (master)
$ git rev-parse HEAD
88d8396b085f3197ce3111f72287092ea5efd4c7

DR01@PC  MINGW64 /c/Users/dr01/Desktop/code/berry (master)
$ yarn --version
2.0.0-rc.8

DR01@PC  MINGW64 /c/Users/dr01/Desktop/code/berry (master)
$ yarn version check -i

DR01@PC  MINGW64 /c/Users/dr01/Desktop/code/berry (master)
$

```

**Comment by arcanis** [comment]
Aaaah got it - you made your changes directly on `master`, and that's what `yarn version check` is comparing against. So it doesn't detect any change ... because there isn't any against itself.

I'll make the bump 👍

**Comment by DRoet** [comment]
gotcha, makes sense. The prerelease stuff might be something worth adding to: https://next.yarnpkg.com/advanced/contributing ?

**Comment by arcanis** [comment]
Agreed! I just pushed a489a9ab0ac0da2716252e5b899c3b16c67a63a3 😃

**Comment by vlasenko** [comment]
@arcanis @DRoet This PR actually breaks `pnpify --sdk`, because VS Code do not understand the stringified version produced by this library. It denies to understand `single` quotes around keys. Even if we call this lib like: `${json5.stringify({...data, ...settings}, {quote: '"', space: 2})}\n`, it won't work too, because it doesn't add double quotes around properies of inner object. So I propose to rollback this patch until the better solution will be found.

**Pull request merged**
