### PR TITLE
Add an e2e test for Next with TypeScript

### PR DESCRIPTION
**Pull request by ucarion**
I open this PR per a conversation in Discord with @arcanis.

**What's the problem this PR addresses?**

Ensures that berry does not regress on supporting Next.js in combination with TypeScript.

**How did you fix it?**

By adding an e2e test that uses an `index.tsx` instead of `index.js`.

There are few things not great in my view about this PR:

1. It's not imminently clear to me how much marginal value this e2e test adds. There may be a maintenance burden to adding new e2e tests willy-nilly. That said, if this e2e test proves to be low-value, it should be easy to remove.

2. I'm not clear on why installing multiple versions of TypeScript is valuable. I sort of blindly copied this from the TypeScript e2e test.

3. It would be good to perhaps test using other webpack loaders. `raw-loader` is troublesome for TypeScript -- it doesn't seem to work with TypeScript out of the box, so maybe a different loader would be better? Open to suggestions here.

### CODE REVIEW

**Comment by merceyz** [comment]
>I'm not clear on why installing multiple versions of TypeScript is valuable. I sort of blindly copied this from the TypeScript e2e test.

That's to test the Typescript patch, you can most likely remove it from this test

**Comment by arcanis** [comment]
I prefer to avoid having too many `e2e` files - can you move your test into the existing Next workflow file? It can just be its own step, running after the no-TS build.

> It's not imminently clear to me how much marginal value this e2e test adds

The e2e tests are used to track when third-party tools make releases that are incompatible with the PnP requirements. They don't need to be very comprehensive, just to go over the main workflows. TypeScript is one of them, and its integrations have room for potential errors.

> It would be good to perhaps test using other webpack loaders. `raw-loader` is troublesome for TypeScript

For example here we're not actually testing that `raw-loader` works, but rather that adding *a* loader works. Raw-loader just happens to be a fairly simple one 😃

> That's to test the Typescript patch, you can most likely remove it from this test

This ☝️

**Comment by ucarion** [comment]
@arcanis @merceyz I've taken a shot at integrating your suggestions -- how does this PR look to y'all?

**Comment by arcanis** [comment]
Sounds good to me, thanks!

**Pull request merged**
