### PR TITLE
[node-modules] Fixes symlinks copying

### PR DESCRIPTION
**Pull request by larixer**
**What's the problem this PR addresses?**

Copying symlinks inside packages were broken in nm linker

**How did you fix it?**

This PR fixes symlinks copying by correctly computing symlink target path

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I have verified that all automated PR checks pass.

### CODE REVIEW

**Comment by arcanis** [comment]
I think the problem is that the symlink is badly cloned on Windows, so it ends up as a file that literally contains `index.js`. Since there's no `index` global function, it crashes ... probably fine to just disable the test on Windows 😕

**Comment by larixer** [comment]
> I think the problem is that the symlink is badly cloned on Windows, so it ends up as a file that literally contains `index.js`. Since there's no `index` global function, it crashes ... probably fine to just disable the test on Windows 😕
Yep, good idea, I'll continue to look in an hour.

**Comment by larixer** [comment]
> LGTM, merge at will!
> 
> Of note: I noticed that the corrupted symlink didn't get updated until after I removed my existing n_m folder - perhaps there's something to fix here as well.

Its generally how we should do this. But I'm not sure for this particular case, I think you are the first person who relies on symlinks in packages. I don't think there were any packages in npm with symlinks before. Given this, should we add smart code to fix broken symlinks generated by previous yarn versions?

**Comment by arcanis** [comment]
> Given this, should we add smart code to fix broken symlinks generated by previous yarn versions?

No need to handle it if it's just a matter of fixing corrupted symlinks, but I'm a bit worried of the case where the symlinks change targets between two versions. Will the n_m linker properly see it and update it accordingly?

**Comment by larixer** [comment]
> > Given this, should we add smart code to fix broken symlinks generated by previous yarn versions?
> 
> No need to handle it if it's just a matter of fixing corrupted symlinks, but I'm a bit worried of the case where the symlinks change targets between two versions. Will the n_m linker properly see it and update it accordingly?

The way we can handle it is to increase version inside `node_modules/.yarn-state.yml` -> `__metadata -> version`. The newer nm linker who outputs version 2 of this file, will understand that it needs to fix symlinks when upgrading from version 1. Its doable, but its additional complexity in the nm linker code. The question is if its reasonable or not to add this code to properly fix this bug.

**Comment by arcanis** [comment]
I meant versions of packages, not Yarn. For example, if has-symlinks@1.0.0 has a `symlink.js -> index.js` symlink while has-symlink@2.0.0 has `symlink.js -> index2.js`, will the symlink update?

**Comment by larixer** [comment]
> I meant versions of packages, not Yarn. For example, if has-symlinks@1.0.0 has a `symlink.js -> index.js` symlink while has-symlink@2.0.0 has `symlink.js -> index2.js`, will the symlink update?

Of course, 100%, its out of question!

**Pull request merged**
