### PR TITLE
 feat(plugin-pnp): improve yarn unplug

### PR DESCRIPTION
**Pull request by paul-soporan**
**What's the problem this PR addresses?**

PnP is a great installation strategy, but it also has its downsides, the biggest one being the fact that it's hard to view / modify the source code of a package, for debugging purposes (at least until all major editors support opening files inside Zip archives). For this, we have the `yarn unplug` command, but it also comes with its own downsides:
- having to persist the unplugged state inside the top-level manifest, which creates the risk of accidentally committing it
- not having glob support. This would be especially useful when trying to make a specific project work with PnP, which requires you to constantly add debug statements and such to the source code of specific packages. (e.g. `yarn unplug '@nuxt/*'` to unplug all packages with the `@nuxt` scope, or `yarn unplug '*'` to unplug **all** packages, in case you're tired of manually unplugging each and every one of them)

We've heard the community and we've decided to make a few improvements to `yarn unplug`, detailed below.

**How did you fix it?**

After discussions with @arcanis and the rest of the team, we've decided to:
- [x] implement glob support (e.g. `yarn unplug '*'`, `yarn unplug '@babel/*'`)
- [x] improve the behavior of `yarn unplug`, making it unplug all locators whose versions match the specified range
- [x] add an `-A,--all` flag. Without it, only dependencies referenced by workspaces are affected, while with it, all dependencies referenced by the current project are affected.
- [x] output which packages have been unplugged (+ `--json` mode)
- [ ] make it possible to unplug nested dependencies (e.g `yarn unplug next/webpack`), leveraging the resolutions parser
- [ ] not save the unplugged state by default (it will only be saved locally inside the `.yarn/install-state.gz` file), requiring the usage of the `--save` flag to persist this state inside the top-level manifest. This should greatly improve the debugging experience, making it possible to unplug a package only locally, without the risk of accidentally committing the unplugged state

I'll leave the last 2 items for @arcanis to implement, as I'll be quite busy in the next few weeks.

Note: Let's not forget to add tests for the new behavior, once we finish implementing everything.

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I have verified that all automated PR checks pass.

### CODE REVIEW

**Comment by arcanis** [comment]
We probably should merge this PR in its current state (perhaps with a few added tests); the changes I want to make to persist the install state may take a bit of time, and it'd be too bad to leave that here in the meantime.

**Comment by paul-soporan** [comment]
I totally agree - I'll rebase and add a few tests 👍

**Comment by paul-soporan** [comment]
@arcanis Finished adding the tests, the PR should be ready to be merged now (unless there's something I should change).

**Comment by arcanis** [comment]
Nice! 👍

**Pull request merged**
