### PR TITLE
Rework peer requirement and warning system

### LINKED ISSUE #5841: [Bug?]: yarn install fails during 'Post-resolution validation' after upgrade to 4.0
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

After upgrading to yarn 4 and running yarn install I get the following error:

```
➤ YN0000: ┌ Post-resolution validation
➤ YN0001: │ TypeError: Cannot read properties of null (reading 'set')
    at /.yarn/releases/yarn-4.0.0.cjs:140:118086
    at Array.map (<anonymous>)
    at sM (/.yarn/releases/yarn-4.0.0.cjs:140:118074)
    at /.yarn/releases/yarn-4.0.0.cjs:207:6475
    at Array.map (<anonymous>)
    at FAt (/.yarn/releases/yarn-4.0.0.cjs:207:6070)
    at /.yarn/releases/yarn-4.0.0.cjs:213:2771
    at Lt.startSectionPromise (/.yarn/releases/yarn-4.0.0.cjs:176:2834)
    at Lt.startTimerPromise (/.yarn/releases/yarn-4.0.0.cjs:176:3734)
    at St.install (/.yarn/releases/yarn-4.0.0.cjs:213:2697)
```

### To reproduce

This is a huge private monorepo. I'm aware that this might get closed due to no way to reproduce, but I am posting in case others have the same issue and could add more context.

Note: The doc link in this issue template to `https://yarnpkg.com/advanced/sherlock` is broken

### Environment

```shell
System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 19.9.0 - /private/var/folders/1h/8llh51vx1s1g998jrmj8_qg80000gn/T/xfs-68ee2d4f/node
    Yarn: 4.0.0 - /private/var/folders/1h/8llh51vx1s1g998jrmj8_qg80000gn/T/xfs-68ee2d4f/yarn
    npm: 9.6.3 - ~/.local/share/nvm/v19.9.0/bin/npm
```

### Additional context

_No response_

### LINKED ISSUE #5977: [Bug?]: explain peer-requirements [hash] throws error
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

running 

```
yarn explain peer-requirements p2677a
```

first threw an error, 

```
Unknown Syntax Error: Command not found; did you mean one of:

  0. yarn explain [--json] [code]
  1. yarn explain [--json] [code]

While running explain peer-requirement p6de1a
```

after yarn down and up grade it now throws 

```
The yarn explain peer-requirements command doesn't support this warning type yet.
```

### To reproduce

minimum package file
```
{
  "devDependencies": {
    "@angular-eslint/template-parser": "^15.2.1"
  },
  "packageManager": "yarn@4.0.2"
}
```

1. Just updated to 4.0.2
2. run yarn
   I got
   ```
   ➤ YN0002: │ root-workspace-0b6124@workspace:. doesn't provide eslint (p6936f), requested by @angular-eslint/template-parser.
   ➤ YN0002: │ root-workspace-0b6124@workspace:. doesn't provide typescript (p7ea97), requested by @angular-eslint/template-parser.
   ➤ YN0086: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
   ```
3. run 
   ```
    yarn explain peer-requirements p6de1a
    ```
   I got

   ```
   Unknown Syntax Error: Command not found; did you mean one of:
   
     0. yarn explain [--json] [code]
     1. yarn explain [--json] [code]
   
   While running explain peer-requirement p6de1a
   ```
4. Test no.1 downgraded to 4.0.1 - 
    - `yarn set version 4.0.1`, 
    - ran `yarn` etc. same result.
5. Test no.2 downgraded to 3.x, at first I got the same error running `yarn explain ...`, 
6. after running it without hash 
   ```
   yarn explain peer-requirement
   ```
   I got the list of peer-requirements with hashes, then `yarn explain peer-requirements p6de1a` worked.
7. Upgraded to 4.0.2, ran `yarn` etc. the message changed to
   ```
   $ yarn explain peer-requirements p6de1a
   
   The yarn explain peer-requirements command doesn't support this warning type yet.
   ```

### Environment

```shell
System:
    OS: macOS 14.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 20.8.0 - /private/var/folders/sm/mwb025n96m1g11lncvl4h2_r0000gn/T/xfs-d7d42f00/node
    Yarn: 4.0.2 - /private/var/folders/sm/mwb025n96m1g11lncvl4h2_r0000gn/T/xfs-d7d42f00/yarn
    npm: 10.1.0 - /opt/homebrew/bin/npm
```

### Additional context

_No response_

### LINKED ISSUE #6016: [Bug?]: `yarn install` warns about peer dependencies that `yarn explain peer-requirements` can't explain
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Some packages cause Yarn to trigger peer dependency warnings, but when you try to use the recommended `yarn explain peer-requirements` with the 6-letter code, it responds:

```
The yarn explain peer-requirements command doesn't support this warning type yet.
```

### To reproduce

Starting from an empty directory:

```sh
# gets version 4.0.2 right now
yarn init -2 --yes

# complains about missing @babel/core, gives code p8740a
yarn add @babel/plugin-syntax-flow@7.23.3

# responds that it doesn't recognize the code
yarn explain peer-requirements p8740a
```

### Environment

```shell
System:
    OS: macOS 13.6
    CPU: (12) arm64 Apple M2 Pro
  Binaries:
    Node: 18.18.2 - /private/var/folders/wg/zn78dyk51h5bvz0crq8x8w0h0000gp/T/xfs-47828ecd/node
    Yarn: 4.0.2 - /private/var/folders/wg/zn78dyk51h5bvz0crq8x8w0h0000gp/T/xfs-47828ecd/yarn
    npm: 9.8.1 - ~/.volta/tools/image/node/18.18.2/bin/npm
```

### Additional context

_No response_

### LINKED ISSUE #6118: [Bug?]: Problem with using workspace:^ in yarn 4.1.0
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Hi. In my development team we were using 3.2.1 yarn.
We decided to upgrade to 4.0.1, and after doing so, I wanted to test installation, so I ran yarn install.
image

after some console.log inspecting, I realized that one of our packages has workspace:^ and that is being thrown by yarn in the line specified by the crash log. I followed the exception to the website and it recommended me to open an issue so here I am. Am doing something wrong? Or is it a bug by yarn? Keep in mind, the same code was working in yarn 3.2.1 before I updated.

image

### To reproduce

I guess have the same setup ive shown in package.json

### Environment

```shell
yarn dlx -q envinfo --preset jest

  System:
    OS: Windows 11 10.0.22621
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12800H
  Binaries:
    Node: 20.11.0 - ~\AppData\Local\Temp\xfs-2c7a4d9f\node.CMD
    Yarn: 4.1.0-git.20240130.hash-943a9f0 - ~\AppData\Local\Temp\xfs-2c7a4d9f\yarn.CMD
    npm: 10.2.4 - ~\.nvm\versions\node\v20.11.0\bin\npm.CMD

i used sources to debug it
```

### Additional context

_No response_

### LINKED ISSUE #6203: [Bug]: Explaining peer warning gives incorrect advice
### Self-service

- [X] I'd be willing to implement a fix

### Describe the bug

Sometimes, due to how they are aggregated, `yarn explain peer-requirements` says peer requests cannot be all satisfied when they can.

Consider this dependency tree:

```
A --> X ==> P@^2
  --> P@1.0.0

B --> Y ==> P@^3
  --> P@1.0.0
```

where `A` and `B` are workspaces , `-->` represents a regular dependency, and `==>` represents a peer dependency.

When we install this, we get an peer warning, which, when explained, gives

```
$ yarn explain peer-requirements p6ab7e
We have a problem with p, which is provided with version 1.0.0.
It is needed by the following direct dependencies of workspaces in your project:

  ✘ x@npm:1.0.0 [0f866] (via ^2)
  ✘ y@npm:1.0.0 [10ea6] (via ^3)

Unfortunately, put together, we found no single range that can satisfy all those peer requirements.
Your best option may be to try to upgrade some dependencies with yarn up, or silence the warning via logFilters.
```

However, this advice is not correct as it is easily fixable by making `a` and `b` depend on different versions of `p`.

----

This is caused by how peer warnings are aggregated by the **provided package** which loses information on different packages that depend on it. Peer warnings should instead be aggregated by **requestee + peer request ident** which are the individual knobs that the end user can turn.

### To reproduce

```js repro
const fs = require(`node:fs/promises`);
const p = require(`node:path`);

async function makeWorkspace(path, manifest) {
  await fs.mkdir(path);
  await fs.writeFile(p.join(path, `package.json`), JSON.stringify(manifest));
}

await makeWorkspace(`./package-x`, {
  name: `x`,
  version: `1.0.0`,
  peerDependencies: {
    p: `^2`,
  },
});
await makeWorkspace(`./package-y`, {
  name: `y`,
  version: `1.0.0`,
  peerDependencies: {
    p: `^3`,
  },
});
await makeWorkspace(`./package-p`, {
  name: `p`,
  version: `1.0.0`,
});

await makeWorkspace(`./workspace-a`, {
  name: `a`,
  version: `1.0.0`,
  dependencies: {
    x: `1.0.0`,
    p: `1.0.0`,
  },
});
await makeWorkspace(`./workspace-b`, {
  name: `b`,
  version: `1.0.0`,
  dependencies: {
    y: `1.0.0`,
    p: `1.0.0`,
  },
});

const output = await packageJsonAndInstall({
  workspaces: [
    `workspace-*`,
    `package-*`,
  ],
});
const hash = output.match(/\(p[0-9a-f]{5}\)/)[0].slice(1, -1);

await expect(yarn('explain', 'peer-requirements', hash)).resolves.not.toMatch(/no single range that can satisfy all/);
```

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
  Binaries:
    Node: 21.7.0 - D:\Users\Clement\AppData\Local\Temp\xfs-cb19a917\node.CMD
    Yarn: 4.1.1 - D:\Users\Clement\AppData\Local\Temp\xfs-cb19a917\yarn.CMD
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.15.4 - C:\Program Files\nodejs\pnpm.CMD
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by clemyan**
**What's the problem this PR addresses?**

There are a number of issues with the current peer requirement and peer warning system:

----

Firstly, since v4, we lost the ability to list all peer requirements in the project and to explain missing peer dependency warnings, which is a huge degradation to DX.

----

Secondly, also since v4, transitive peer warnings are no longer displayed. The rationale given was "those are not actionable". But they *are* actionable because we have `packageExtensions`.

More importantly, there are no indication nor discoverability when this happens. Yarn exits without even a warning when transitive peer warnings can put the project in an invalid state. Even when the user somehow knows that there are transitive peer warnings, they are impossible to investigate and fix without the proper tools.

----

Thirdly, as I just reported, the peer warning aggregation is aggregating unrelated peer requests, causing `yarn explain peer-requirements` to give incorrect advice. #6203

----

Finally, the peer resolution pipeline has been refactored and added to many times over the years which make the code quite difficult to understand. This is compounded by misplaced comments and overloading terms like "peer descriptor" in the code.

----

Closes #5841
Closes #5977
Closes #6016
Closes #6118
Closes #6203

**How did you fix it?**

On the last problem, it is quite impossible to completely solve in one go, so I only took small bites and at least rewrote some of the comments to better capture the current peer pipeline. I have also unified the terminology and change variable names to use those terminology to reduce ambiguity. Maybe we should add these to the lexicon?

Let's say
- Package `A` (regular-)depends on `B`, which peer-depends on `C`
- Package `A` also depends on `C`

```
A@1.0.0 --> B@^1.0.0 (resolves to B@1.1.0) ==> C@^1.0.0
        --> C@^1.2.0 (resolves to C@1.3.0)
```

In the scope of this single level
- The package `A@1.0.0` is known as the **subject** or **requestee**
- The package `B@1.1.0` is known as the **requester**. Also called the **virtualized package** in the code because of what the pipeline is doing
- The ident `C` is known as the **peer ident** and the descriptor `C@^1.0.0` is known as the **peer descriptor**
- The descriptor `C@^1.2.0` is the **provided descriptor**. Similarly, `C@1.3.0` is the **provided locator/package**. **Provision** can refer to any of those depending on context.
  - Note that the provision is not necessarily `A`'s dependency. `A` itself could be used if its ident *were* matching, or a package can be not provided at all.

Based on those we can create some composite data structures:
- A **peer request** encapsulates a requester + peer ident.
  - If a subject does not provide to the request itself, but instead requests a peer dependency under the same ident, that subject and the new peer request it issues are both said to **forward** the original peer request.
- A **peer requirement** encapsulates a subject + peer ident + one or more peer requests. This captures the fact that a single subject that depends on multiple peer requesters can satisfy multiple peer requests at the same time
  - Note that peer requests and peer requirements is a many-to-many relationship. A peer request is included in multiple peer requirements if the requester is depended upon multiple times (which can happen due to deduplication).
  - A peer requirement is said to be a **root peer requirement** if the subject does not forward the peer requests.

----

With those concepts established, the core of this PR changes the peer requirement and peer warning system to use a tree-based structure. The nodes of the tree are either peer requests or peer requirements. A peer request's children are the requests it forwards, and a peer requirement's children are the requests it includes. Note that a tree can only ever include peer requirements and requests regarding a single peer ident.

Untitled Diagram

By storing all peer requirement nodes in `Project`, other places can easily display information on peer requirements/requests/warnings by retrieving them form the tree (using the new tree-view UI, even). This allows us to reimplement `yarn explain peer-requirements` and `yarn explain peer-requirements <hash>` to list all requirements and explain any peer requirement (even without warnings) respectively. This also fixes #6203 because the peer requirement nodes correctly group the peer requests.

image

----

To solve the discoverability problem without bringing back the clutter, I've added an additional CTA for transitive peer warnings, so all transitive peer warnings are reduced to a single line.

```
➤ YN0000: ┌ Post-resolution validation
➤ YN0002: │ workspace-b@workspace:workspace-b doesn't provide p (p427bb), requested by y.
➤ YN0086: │ Some peer dependencies are incorrectly met by your project; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
➤ YN0086: │ Some peer dependencies are incorrectly met by dependencies; run yarn explain peer-requirements for details.
➤ YN0000: └ Completed
```

A user wishing to view the transitive warnings can do so with the reimplemented `yarn explain peer-requirements` command.

----

Lastly, I don't know how much of the original peer requirement and warning system matter for BC. For now, I have recreated the data structures created by the original system, except the aggregated warnings which is the wrong abstraction as noted. I have added TODO comments to remove those code for the next major. Please advice if the original system can be safely removed in a minor.

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

**Comment by arcanis** [comment]
I'm a little worried of changes done to the peer dependency system but it looks well-researched, I don't see something obviously wrong in it, and our tests keep passing, so I think it's worth merging. Nice work!

**Comment by ndelangen** [comment]
Will this be released soon?
As far as i can tell, this isn't in `4.2.2` yet?

**Comment by SimenB** [comment]
(This is out in 4.3.0)

Thanks for your work on this!

Would it be possible to filter out the correctly supplied peer dependencies when running `explain`?

I now get the following:

> react is listed by your project with version 17.0.2 (p45da6), which doesn't satisfy what @apollo/client and other dependencies request (but they have non-overlapping ranges!).

But `@apollo/client` _is_ satisfied, so I think the text here is misleading.

Running `yarn explain peer-requirements p45da6 | wc -l` shows 793 lines of code (`react-aria-components` have many, _many_ small packages that all defines peer deps on React that yarn now lists 😅).

There is no indication in this output which dependency has the unresolved requirement (again, `@apollo/client` does _not_).

At the end of the output there is this:

>✘ Package cvpartner@workspace:. provides react with version 17.0.2, which does not satisfy all requests.
  Unfortunately, the requested ranges have no overlap

But, again, it doesn't say _which_ package is not satisfied.

Now, I can just go back to `4.2.2` and get the following warning on `install`:

>react is listed by your project with version 17.0.2, which doesn't satisfy what reflux (p99ba3) requests (^15.0.2)

Which is the correct one - after looking through the ~800 lines of output, that is indeed the only one that doesn't support the version of React provided by my project. There is no visual indication either, or anything I can `grep` for to filter.

**Comment by brianlenz** [comment]
We are seeing the same thing as @SimenB, but with `@types/react-native`. It looks like the change in `4.3.0` may be over-aggressive (and inaccurate?) in marking unsatisfied, transitive peer dependencies. We are going to stick with Yarn `4.2.2` for now until the issue is resolved so we don't see so many false positives.

**Pull request merged**
