### PR TITLE
feat: don't quote valid `IdentifierName`s in pretty json of PnP hook

### PR DESCRIPTION
**Pull request by paul-soporan**
**What's the problem this PR addresses?**

Reading the serialized state inside of the PnP hook is more painful than it has to be because all object properties are quoted even when they don't need to be, and most themes use the same color for quoted object keys and quoted object values <sup>[citation needed]</sup>.

**How did you fix it?**

Made `generatePrettyJson` skip quoting keys when it's not required.

**Checklist**

- [X] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [X] I have set the packages that need to be released for my changes to be effective.

- [X] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

**Review by merceyz — CHANGES_REQUESTED** [review]
If we don't quote them it isn't a valid JSON string anymore so I don't think we should do this.

**Comment by paul-soporan** [comment]
It's not valid JSON on master either because of trailing commas and we currently use `JSON.stringify` for the split setup anyways.

**Comment by merceyz** [comment]
I've noticed that as well and have a branch fixing it but haven't gotten around to making a PR yet

**Comment by paul-soporan** [comment]
Ah, I was intending to implement a "strict JSON mode" in a future PR (gating both of these things that make it invalid JSON behind it) so that we can use `generatePrettyJson` for `.pnp.data.json` too. In this case, do you want me to gate it behind the flag now and let you fix that issue later and make `.pnp.data.json` use it too?

**Comment by merceyz** [comment]
The reason I wanted it to be a valid JSON string is because I was working on using `JSON.parse` on it since it's supposed to be faster for V8 to parse[^1]. Sadly it turns out that using a multiline template literal is slower so I left it alone for now.

With that backstory out of the way, since the function is private we could rename it and my objection would be gone assuming the lack of quotes doesn't affect the startup time 👍 

[^1]: https://v8.dev/blog/cost-of-javascript-2019#json

**Pull request closed without merging**
