### PR TITLE
fix(git): call `getNetworkSettings` with the origin of the repo

### PR DESCRIPTION
**Pull request by merceyz**
**What's the problem this PR addresses?**

- The changes introduced in https://github.com/yarnpkg/berry/pull/2030 broke making requests to git URLs such as `git@github.com:foo/foo.git`
- Git URLs such as `git@github.com:foo/foo.git` can't be valid URL instances and thus can't be filtered on

Fixes https://github.com/yarnpkg/berry/issues/2240

**How did you fix it?**

Parse the hostname out of the git url and pass that to `getNetworkSettings `

**Checklist**
- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).
- [x] I have set the packages that need to be released for my changes to be effective.
- [x] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

**Comment by arcanis** [comment]
> Git URLs such as `git@github.com:foo/foo.git` can't be valid URL instances and thus can't be filtered on

Why are Git urls passed on to this function in the first place? They should be handled by Git, not by Yarn 🤔

**Comment by merceyz** [comment]
The git functions check if the network is enabled before executing any commands

https://github.com/yarnpkg/berry/pull/2030/files#diff-4f6fea93add5ee70f4d4374525128f44bfc0d3d8b2172b469d06dd15c0662adeL294-L296
https://github.com/yarnpkg/berry/pull/2030/files#diff-4f6fea93add5ee70f4d4374525128f44bfc0d3d8b2172b469d06dd15c0662adeL173-L174

**Comment by arcanis** [comment]
Then wouldn't a better fix be to convert, in the git utils, the repository url to an http url? I'm worried about adding support for non-http/https urls to the http module, especially since the `contains` flag can yield false positives if the matching string is anywhere else than the hostname.

**Comment by merceyz** [comment]
My initial fix was to skip invalid URLs for the `networkSettings` config and just use the globals, think we should just do that instead as I don't think it's worth it to do the extra parsing just for this

**Comment by arcanis** [comment]
We already have the repo url in both functions (as `repo`). It should only be a matter of passing `https://${repo}` instead of `normalizedRepoUrl`, the existing utils should do the rest.

**Comment by donferi** [comment]
Hi yarn team 🙋‍♀️ Is there any updates to this issue? The company I work for is trying out rc-2 but currently can’t install from a git (ssh) private repository because of this.

**Comment by merceyz** [comment]
@donferi Hey, I've rebased the PR and changed the fix to parse out the hostname, you can test it with
```
yarn set version from sources --branch 2295
```

**Comment by donferi** [comment]
@merceyz Worked perfectly fetching them.

Question semi-related: Is there a way I can disable the packaging step when fetching a package from git?

We commit the `/dist` files and would like yarn not to do anything but only clone it. Some of our packages are failing when trying to build because of different node/npm versions, etc. Plus it has to pull down all the `devDependencies` which have more `git` references which also try to build.

**Comment by merceyz** [comment]
> Question semi-related: Is there a way I can disable the packaging step when fetching a package from git?

See https://github.com/yarnpkg/berry/discussions/2808#discussioncomment-662002

**Pull request merged**
