### PR TITLE
Add VSCode support for Stylelint to PnPify tool.

### PR DESCRIPTION
**Pull request by phyllisstein**
**What's the problem this PR addresses?**

Currently, Berry breaks support for [the VSCode Stylelint plugin](https://marketplace.visualstudio.com/items?itemName=stylelint.vscode-stylelint) in much the same way that it caused issues with ESLint and TSC.

**How did you fix it?**

This change updates the SDK support script in `@yarnpkg/pnpify` to generate a PnP wrapper for Stylelint and point the project's VSCode config file to the script. It also updates the `compat` plugin so that a Stylelint dependency, [`postcss-syntax`](https://github.com/gucong3000/postcss-syntax), can require some additional packages which it currently only includes in its `devDepdendencies`. (PR addressing the issue in that repo to follow.)

### CODE REVIEW

**Comment by arcanis** [comment]
Sounds good, but can you open the PR on PostCSS-Syntax before I merge this one?

Also, looking at their README, I think that *optional* peer dependencies might be a better fit than regular dependencies (since they ask their users to add the various modules themselves).

**Comment by 7rulnik** [comment]
@arcanis seems that @phyllisstein had opened PR into postcss-syntax  https://github.com/gucong3000/postcss-syntax/pull/46

May we merge this PR?

**Comment by phyllisstein** [comment]
Pardon the radio silence here. I wound up dropping back down to Yarn Classic in my project, then got slammed with onboarding for a new gig. I'll make time this weekend to take another look.

**Comment by 7rulnik** [comment]
@phyllisstein @arcanis I rebased this PR on master in https://github.com/yarnpkg/berry/pull/1263

**Comment by arcanis** [comment]
Thank you both! 😃

**Comment by phyllisstein** [comment]
Thanks for picking up my slack. Onboarding in quar is no small thing. 😩

**Pull request merged**
