### PR TITLE
fix(interactive-tools): fetch suggestions in batches

### LINKED ISSUE #2392: [Bug] upgrade-interactive with a lot dependencies incorrectly shows "No upgrades found"
- [ x ] I'd be willing to implement a fix

`yarn upgrade-interactive` with ~120 packages needs ages until it ends and then it shows (incorrectly) "No upgrades found".
I think this is because you try to fetch all suggestions at once. When I load the suggestions in chunks of 10, everything works correctly. I will add a PR which fixes it for me.

**Environment if relevant (please complete the following information):**

 - OS: windows 10
 - Node version v15.6.0
 - Yarn version 2.4.0

### PR DESCRIPTION
**Pull request by PutziSan**
**What's the problem this PR addresses?**

closes #2392
...

**How did you fix it?**

Load the suggestions for upgrade-interactive in chunks of 10

...

**Checklist**

- [ x ] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [ x ] I have set the packages that need to be released for my changes to be effective.

- [ x ] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

**Comment by arcanis** [comment]
That seems unlikely to be the right fix 🤔 We already limit the network concurrency, there should be no need to do it again here.

**Comment by PutziSan** [comment]
This fix workes for me. Maybe the network concurrency was not the real problem or it is windows related. I will do later some investigation

**Comment by PutziSan** [comment]
Am I correct in assuming that the network concurrency is controlled by [this config](https://github.com/yarnpkg/berry/blob/master/packages/yarnpkg-core/sources/Configuration.ts#L326-L330):
```
  networkConcurrency: {
    description: `Maximal number of concurrent requests`,
    type: SettingsType.NUMBER,
    default: Infinity,
  }
```

Do you change the default value somewhere for the interactive-tools? @arcanis

**Comment by PutziSan** [comment]
see https://github.com/yarnpkg/berry/issues/2392#issuecomment-764464388 `networkConcurrency: 10` in `.yarnrc.yml` seems to do basically the same.

**Pull request closed without merging**
