### PR TITLE
fix workspace foreach --all

### PR DESCRIPTION
**Pull request by missing1984**
**What's the problem this PR addresses?**

Fix https://github.com/yarnpkg/berry/issues/1066
...

**How did you fix it?**
Compare cwdWorkspace with topLevelworkspace and exclude it if necessary.
...

### CODE REVIEW

**Comment by arcanis** [comment]
Thanks @missing1984! In light of https://github.com/yarnpkg/berry/issues/1066#issuecomment-607230842 I think we should rather fix the documentation than `foreach`, does that sound ok to you?

**Comment by missing1984** [comment]
> Thanks @missing1984! In light of [#1066 (comment)](https://github.com/yarnpkg/berry/issues/1066#issuecomment-607230842) I think we should rather fix the documentation than `foreach`, does that sound ok to you?

* I was struggling with this issue as my intuition told me workspace root should be excluded by default. Lerna and other monorepo tools have similar functionality that works this way. Would that be better to keep the behavior somewhat consistent?
* I am running this as an npm script in my workspace root(I am assuming this is a typical use case of foreach). i.e. `'publish': 'yarn workspaces foreach npm publish'` it seems odd that current root is included.

Let me know what do you think @arcanis :)

**Comment by arcanis** [comment]
> I was struggling with this issue as my intuition told me workspace root should be excluded by default. Lerna and other monorepo tools have similar functionality that works this way. Would that be better to keep the behavior somewhat consistent?

The Yarn behavior is defined this way because it's easy to filter out packages you don't want to cover, but more difficult (due to the implementation) to add packages from outside the current "scope". When you factor in nested workspaces, I think the current behavior is the one that makes the most sense.

> I am running this as an npm script in my workspace root(I am assuming this is a typical use case of foreach). i.e. 'publish': 'yarn workspaces foreach npm publish' it seems odd that current root is included.

This is very subjective. I personnally wouldn't expect running `yarn workspaces foreach` to exclude the very first workspace of the project - the root itself.

For publish scripts it doesn't make much sense indeed, but fortunately it's very easy to workaround: just create a `release` script in all your publishable workspaces that call `yarn npm publish`. You can even use constraints to automate that if you wish.

**Comment by missing1984** [comment]
Call `yarn npm publish` from workspace root? is this command smart enough to loop through all its children and call `release`?

**Comment by missing1984** [comment]
closed. I will file a new pr to fix the doc

**Pull request closed without merging**
