### PR TITLE
fix(core): determine if a module is a builtin using `module.isBuiltin`

### PR DESCRIPTION
**Pull request by zouguangxian**
**What's the problem this PR addresses?**

`builder plugin` may output `node:process` instead of `process` in the generated file.
When executing `yarn.`, it will report an error like:
```
This plugin cannot access the package referenced via node:process which is neither a builtin, nor an exposed entry
```

** Environment
```
❯ yarn tsc --version
Version 5.3.2
```

...

**How did you fix it?**

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

**Review by merceyz — CHANGES_REQUESTED** [review]
Node.js exposes a [`module.isBuiltin`](https://nodejs.org/dist/latest-v20.x/docs/api/module.html#moduleisbuiltinmodulename) function that can handle this for us, could you change the implementation to use that instead?

Please add a test to https://github.com/yarnpkg/berry/blob/f3775aaec22dd05c83b9a144a2c3aa52e8774c21/packages/acceptance-tests/pkg-tests-specs/sources/features/plugins.test.ts.

**Comment by zouguangxian** [comment]
> Node.js exposes a [`module.isBuiltin`](https://nodejs.org/dist/latest-v20.x/docs/api/module.html#moduleisbuiltinmodulename) function that can handle this for us, could you change the implementation to use that instead?
> 
> Please add a test to https://github.com/yarnpkg/berry/blob/f3775aaec22dd05c83b9a144a2c3aa52e8774c21/packages/acceptance-tests/pkg-tests-specs/sources/features/plugins.test.ts.

Is it possible for you to figure out how to use `module.isBuiltin` to handle this? Is the current implementation the most simple?

**Comment by zouguangxian** [comment]
@merceyz Is it possible for you to review this PR?

**Comment by adrian-gierakowski** [comment]
would be great to have this merged as there are currently 3 open issues that this would fix:

https://github.com/yarnpkg/berry/issues/6135
https://github.com/yarnpkg/berry/issues/5417
https://github.com/yarnpkg/berry/issues/5637

**Comment by adrian-gierakowski** [comment]
@zouguangxian just wanted to say thank you as this patch works for me!

**Comment by jkowalleck** [comment]
@arcanis could you maybe rebase or merge in latest master, and have the CI/CT run again?

**Comment by jkowalleck** [comment]
@merceyz  @arcanis @zouguangxian ,
could you maybe rebase or merge in latest master, and have the CI/CT run again?

**Comment by jkowalleck** [comment]
@zouguangxian could you add the following to the PR description? 
```text
fixes #6135
fixes #5417
fixes #5637
```

**Comment by jkowalleck** [comment]
the following is a backwards-compatible "fix" of the plugin compiler: https://github.com/yarnpkg/berry/pull/6356 
This compiler should enable plugins to be runnable without this patched yarn-core.

**Comment by jkowalleck** [comment]
> **What's the problem this PR addresses?**
> 
> `builder plugin` may output `node:process` instead of `process` in the generated file. When executing `yarn.`, it will report an error like:

shoud be fixed via https://github.com/yarnpkg/berry/pull/6356
the next version of yarn plugin builder/bundler should include a feature that solves this behavior for you.

**Review by merceyz — APPROVED** [review]

**Review by merceyz — APPROVED** [review]

**Pull request merged**
