### PR TITLE
More possible styles

### PR DESCRIPTION
**Pull request by LitoMore**
Our current `configuration.format()` function does not support multiple styles like `bgYellow and black`.

By using [chalk-pipe](https://github.com/LitoMore), we can create a colorful style both have `bgYellow` and `black`.

We could create a formatted text like:

```javascript
configuration.format('yarnpkg/berry', 'blue.underline');
configuration.format(' ERROR ', 'bgRed.black.bold');
```

### CODE REVIEW

**Comment by arcanis** [comment]
Hey! That seems interesting - the main concern I have is that it would add a dependency to what appears to be a relatively unknown package for a feature that we don't need at the moment.

Given the [recent news](https://www.theregister.co.uk/2018/11/26/npm_repo_bitcoin_stealer/) I'm a bit more wary of the possible consequences of this kind of things, so I think we'll not want to merge it. That's not to say that the package or your PR are malicious, just that the value/risk ratio isn't high enough to be worth potential complications.

Does that make sense?

**Comment by LitoMore** [comment]
Yes, good point. If we pin `chalk-pipe` to `2.0.0` there is still a security risk?

Alternatively, if you guys interested in this feature but don't want any new dependencies, I can use another way of no using any new dependencies to finish this feature.

**Comment by arcanis** [comment]
Tbh I don't think we need more colors ... 🤐

That being said, something I wanted to do for some time but never got the time to get right was to add support for [hyperlinks](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda). Would you be interested to help with that? The idea I have would be to allow to click on a package name/version and go directly to its page on the Yarn repository. That would be dope!

It might require some plumbing to be done in the `Resolver` interface to add a new method that would allow resolvers to point a `Ident` / `Locator` to a remote location (so the npm locator would return the url to the Yarn index, while the Github resolver would point to the repository's GitHub page).

**Comment by LitoMore** [comment]
> Tbh I don't think we need more colors ... 🤐

OK, I'm going to close this pull request.

> That being said, something I wanted to do for some time but never got the time to get right was to add support for hyperlinks. Would you be interested to help with that? The idea I have would be to allow to click on a package name/version and go directly to its page on the Yarn repository. That would be dope!
> 
> It might require some plumbing to be done in the Resolver interface to add a new method that would allow resolvers to point a Ident / Locator to a remote location (so the npm locator would return the url to the Yarn index, while the Github resolver would point to the repository's GitHub page).

No problem! Let's get start with it!

**Pull request closed without merging**
