### PR TITLE
Adds a patchfile for fsevents

### PR DESCRIPTION
**Pull request by arcanis**
**What's the problem this PR addresses?**

FsEvents isn't aware of the virtual filesystem (`$$virtual`, more details at the end of this post), and that breaks Webpack when requiring files from a workspace that lists peer dependencies.

**How did you fix it?**

As a short-term fix I've implemented the fix in `fsevents` via our new `patch:` protocol. I wonder if we could convince the `fsevents` maintainers to merge the change upstream? (cc @paulmillr / @pipobscure)

**What is this `$$virtual` thing?**

First [read that](https://next.yarnpkg.com/advanced/lexicon#virtual-package). Now, as the article says:

> Virtual packages [...] are now implemented through a virtual filesystem layer. This circumvents the need to create hundreds of confusing symlinks, improving compatibility with Windows and preventing issues that would arise with third-party tools calling realpath

The way we do this by injecting a `fs` layer that applies the following algorithm:

- Find occurances of `/$$virtual/<whatever>/<number>/`
- Replace them by `'../'.repeat(number)`

So for example, `/foo/$$virtual/abcdef/0/hello` becomes `/foo/hello`, and `/foo/$$virtual/abcdef/1/hello` becomes `/hello`. This technic allows us to generate an infinity of paths for a given package.

### CODE REVIEW

**Comment by paulmillr** [comment]
Could you get the PR to our fsevents repo? We will discuss it there!

**Comment by pipobscure** [comment]
Though I have to say that fsevents seems like the worst possible layer to do this.

**Comment by arcanis** [comment]
Damn, for some reasons `fsevents` just doesn't seem to work on our GitHub Actions, even though you actually use it in your own tests 🙁

**Comment by arcanis** [comment]
Oh interesting - FSEvents 2.x works on GitHub Actions, but not 1.x 🤔

**Comment by arcanis** [comment]
Errata: I had a typo in the variable name that was causing `undefined` to be sent to FsEvents, triggering a segfault. For some reason it still worked on my computer (the segfault's ways are mysterious indeed), but that's why it failed once on CI. Now everything's passing!

**Comment by arcanis** [comment]
Merging for now, will open a PR against FSEvents later.

**Pull request merged**
