### PR TITLE
chore(compat): update extensions list

### PR DESCRIPTION
**Pull request by merceyz**
**What's the problem this PR addresses?**

Updates the extensions list to include
- https://github.com/tj/consolidate.js/pull/339
- https://github.com/vuejs/vue-loader/pull/1853
- https://github.com/salesforce-ux/scss-parser/pull/43
- https://github.com/salesforce-ux/query-ast/pull/25
- https://github.com/reduxjs/redux-thunk/pull/251

Closes https://github.com/yarnpkg/berry/issues/3150

**Checklist**
- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).
- [x] I have set the packages that need to be released for my changes to be effective.
- [x] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

**Comment by chenyulun** [comment]
Please withdraw your this this change, `vue-loader@15.11.1` supports `@vue/compiler-sfc@^2.7.0`.

**Comment by chenyulun** [comment]
packages/yarnpkg-extensions/sources/index.ts 
```diff
[`vue-loader@<=16.3.3`, {
    peerDependencies: {
-    '@vue/compiler-sfc': `^3.0.8`,
+      '@vue/compiler-sfc': `^2.7.0 || ^3.0.8`,
      webpack: `^4.1.0 || ^5.0.0-0`,
    },
    peerDependenciesMeta: {
      '@vue/compiler-sfc': optionalPeerDep,
    },
  }]
```

**Comment by merceyz** [comment]
You're welcome to open a PR that limits the range that this PR uses and add a new entry for versions < 15.11.1.

**Comment by chenyulun** [comment]
Are you sure `vue-loader@16` doesn't support `@vue/compiler-sfc@^2.7.0`?

**Pull request merged**
