### PR TITLE
test(plugin-compat): add test for built-in patches

### PR DESCRIPTION
**Pull request by paul-soporan**
**What's the problem this PR addresses?**

There are no tests for the built-in patches.

**How did you fix it?**

I added a test for the built-in patches.

The test tests all of the candidates inside the provided ranges.

The test ranges are:
- the ranges that the patches are made to support
- `latest`
- extra tags (e.g. `beta`, `dev`, `next`)

Note: The test currently fails for `typescript@3.1.6`, `typescript@3.6.5`, and `typescript@beta`. This is expected, as the patch is currently broken for those versions.

### CODE REVIEW

**Comment by arcanis** [comment]
My main worry is that, by experience, network access on CI are often very flaky and can hide useful signals 🙁 Can we make the tests non-failing in case of network connectivity failures (I'm not sure that Jest supports a "Warning" API)?

**Comment by paul-soporan** [comment]
🤔 Couldn't find anything similar to a Warning API in Jest.

**Comment by paul-soporan** [comment]
@arcanis Changed the test to only check for `Cannot apply hunk` error messages. This way, errors are caught inside the `catch` block, so network failures should make the tests pass.

**Comment by arcanis** [comment]
Great 👍 One other problem though: it adds 20mns of run time ...

image

I think it should be put inside its own parallel build, and have its trigger modified to only run when `typescript.patch.ts` is modified (no need for it to be scheduled, since it should already be covered by the TS E2E test).

**Comment by arcanis** [comment]
I think to merge it we'll need to remove from the ranges the versions that don't already compile. I tried to tweak the commit hashes to get a full coverage, but couldn't find a sensible set.

**Comment by paul-soporan** [comment]
Landed in #1557.

**Pull request closed without merging**
