### PR TITLE
Fix normalizeRepoUrl

### PR DESCRIPTION
**Pull request by FrozenKiwi**
`normalizeRepoUrl` uses a different regex compared to the `gitPatterns` regex used in `isGitUrl`.  It is missing the 0-9 bit, which means that Urls that are correctly marked as git urls in `isGitUrl` fail when being processed by `lsRemote`

This fix fixes that so that an address that passes isGitRepo will also successfully be parsed by normalizeRepoUrl

This can be tested by doing:
```yarn add @openzeppelin/cli --dev```
This command installs Web3-js@1.2.2 which listed `"scrypt-shim": "github:web3-js/scrypt-shim",` as a dependency.  (Not in package.json or anywhere easy to find mind, that would be searchable and we wouldn't want that)

**How did you fix it?**

Add 0-9 to normalizeRepoUrl, installed openzeppellin.  Swore at computer a great deal.  One of those two actions may have done it, not sure which.

### CODE REVIEW

**Comment by arcanis** [comment]
The tests are failing, can you investigate? The diff is weird, why is it detecting the `Z` as being removed and added? Maybe you left an invisible character there?

**Comment by FrozenKiwi** [comment]
I'll double-check that.  The test error though might be a false positive, the error is

`Snapshot name: `gitUtils should properly normalize GitHubOrg/foo2bar.js 1`

If there is a 2 in the name, then the previous regex would not have normalized that?  Or is it being incorrectly normalized now?

**Comment by arcanis** [comment]
I'd have think so to, but apparently the snapshots were returning the right result before, and not not ... that's weird given that I don't see anything wrong in your diff, but better investigate to understand what happens  🤔

**Comment by deini** [comment]
@arcanis I believe @FrozenKiwi is correct, the snapshot was wrong. It was not returning the right result before, it was actually wrong 😕. 

I think we just need to update the snapshot and this should be good to go.

**Comment by arcanis** [comment]
Oops, I misread the output 😅 Yes you're right, let's just fix the snapshot 👍

**Pull request merged**
