### PR TITLE
Implements .env file support

### LINKED ISSUE #4718: Add support for .env file
Hi,

I am referring to an already existing issue which was closed, imho, without a proper resolution:
https://github.com/yarnpkg/berry/issues/2724

There was a pull request which was eventually rejected, with a proposed alternative solution (see one of the first messages from @paul-soporan):
https://github.com/yarnpkg/berry/pull/3938

Now I would really love to try and implement the proposal myself, unfortunately I do not have enough time and knowledge on my end. However with some hints and support I would be more than happy to help: is anybody willing to support this?

Many thanks!

### PR DESCRIPTION
**Pull request by arcanis**
**What's the problem this PR addresses?**

A common need is to provide environment values into the environment via `.env` files. There's been a couple of issues and attempts at implementation already, which all were decently upvoted. I myself could have used it once or twice 😄

Props to @jj811208 for his implementation in #4835 - I wanted to make the configuration a little more generic (allowing to have multiple environment files, and to possibly disable it altogether), but it was a appreciated start.

Fixes #4718 
Closes #4835 (Supercedes it)

**How did you fix it?**

A new setting, `injectEnvironmentFiles`, lets you define files that Yarn will load and inject into all scripts. It only affects subprocesses - Yarn itself still uses `process.env` for its checks, so you can't for example set `YARN_*` values and expect them to be applied to the current process (use the yarnrc file for that instead).

The `injectEnvironmentFiles` setting has a few properties:

- It defaults to `.env`
- Nothing will be injected if it's set to an empty array or null
- The paths inside may be suffixed by `?` - in that case, Yarn won't throw if the file doesn't exist

The idea with this last property is to allow for simple user configuration (imagine, with the example below, that the project also has a gitignore with `.env.*`):

```
injectEnvironmentFiles:
  - .env
  - .env.${USER}?
```

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

**Comment by daniluk4000** [comment]
Will this allow to use any variables from .env in .yarnrc.yml?

For example:

```yml
injectEnvironmentFiles:
  - .env

npmScopes:
  myScope:
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_TOKEN:-}" #From .env
    npmRegistryServer: "https://customgitlab/api/v4/packages/npm"
```

**Comment by arcanis** [comment]
I forgot to add a test case covering it but I think it should.

**Comment by belgattitude** [comment]
> Nothing will be injected if it's set to an empty array or null

Worth to mention that

```yml
injectEnvironmentFiles: []  # <-- works
injectEnvironmentFiles: null # <-- Internal Error: ENOENT: no such file or directory, open '/home/sebastien/github/nextjs-monorepo-example/null'
```

**Comment by belgattitude** [comment]
Added some concerns here: https://github.com/yarnpkg/berry/pull/5544#issuecomment-1613661101

Myself I'd recommend to make it 'opt-in'. It will create issues with few projects (ie nextjs...)

**Comment by hanzelkatomas** [comment]
May I ask which version will be this released?

**Comment by lukeapage** [comment]
I was trying it out, thanks. Its worth noting that if you specify a env file that does not exist, you get an error, which means the use-case of .env.user that is git ignored is bad dx (the user needs to create an empty env file in order to run yarn install)

**Comment by arcanis** [comment]
> I was trying it out, thanks. Its worth noting that if you specify a env file that does not exist, you get an error, which means the use-case of .env.user that is git ignored is bad dx (the user needs to create an empty env file in order to run yarn install)

It doesn't error if you suffix the path with a question mark (ie `.env.user?` won't throw if `.env.user` is missing).

**Comment by lukeapage** [comment]
Perfect, thanks - that works.

I just discovered it also errors when I run the command to setup my editor

```
yarn dlx @yarnpkg/sdks vscode

Internal Error: ENOENT: no such file or directory, open 'C:\Users\xxxx\AppData\Local\Temp\xfs-e4f23b26\dlx-12060\.env'
Error: ENOENT: no such file or directory, open 'C:\Users\xxxx\AppData\Local\Temp\xfs-e4f23b26\dlx-12060\.env'
```

which must be a bug?

**Comment by SimpleCreations** [comment]
For anyone having trouble with using env variable substitution in `injectEnvironmentFiles` field itself, and finding this PR, I've opened a bug report here: https://github.com/yarnpkg/berry/issues/6679

**Pull request merged**
