### PR TITLE
ci: add gulp e2e test

### PR DESCRIPTION
**Pull request by Daniel-McCarthy**
**What's the problem this PR addresses?**

The Gulp package is still missing from the list of completed E2E tests required by #368.

**How did you fix it?**

I added an E2E test that installs gulp to a project as a dev dependency and tests with two short scripts.
One creates a simple default task that should run successfully when running "gulp", validating that the dependency installed and is able to run.

The next creates a public task that can be run with the "gulp <taskname>" CLI argument, and validates that we're able to import and use the gulp API by making use of the src() function to load the script file in.

I look forward to any suggestions for how to expand or improve E2E coverage for Gulp. Thanks for your time!

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

**Comment by merceyz** [comment]
Ref https://github.com/gulpjs/gulp/issues/2621

**Comment by arcanis** [comment]
Nice, thanks! Interestingly the test seems to pass, unlike what https://github.com/gulpjs/gulp/issues/2621 suggests 🤔 cc @bhanubais

**Review by merceyz — CHANGES_REQUESTED** [review]
Should be added to the readme and compat table, see https://github.com/yarnpkg/berry/pull/2958 and https://github.com/yarnpkg/berry/pull/2983 for reference

**Comment by Daniel-McCarthy** [comment]
> Nice, thanks! Interestingly the test seems to pass, unlike what [gulpjs/gulp#2621](https://github.com/gulpjs/gulp/issues/2621) suggests 🤔 cc bhanubais

No problem, just happy to find a way to help!

I was able to get this E2E test for 4.0.2 like mentioned in that issue as well as 4.0.0. If there's another edge case to cover for their workflow it will be interesting to see what the discrepancy is.

**Pull request merged**
