### PR TITLE
fix: change JailFS to CwdFS and improve CwdFS

### PR DESCRIPTION
**Pull request by paul-soporan**
**What's the problem this PR addresses?**

It's not currently possible to have a single folder for patches at the root level of the project, because patch paths are resolved using the `parentFs`, which is a `JailFS` targeting the workspace folder in the case of workspaces.

**How did you fix it?**

I added a new feature to `JailFS`: levels. They represent the maximum number of levels the Jail can be escaped by paths.

Example for `new JailFS(path, {levels: 1})`:
- `text.txt` - works
- `../text.txt` - works
- `../../text.txt` - nope, the FS has to climb too many levels to resolve this path

I also added a new static method (`computeLevels`) on the `JailFS` class, used to compute the levels between 2 paths.

I also made the `JailFS` in the `WorkspaceFetcher` (the `packageFs`) use the new levels feature, so that patches at the root of the project can be accessed from any workspace.

I also added tests and updated the PnP hook.

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I have verified that all automated PR checks pass.

### CODE REVIEW

**Comment by arcanis** [comment]
I'm not sure I follow the use case, can you describe more what you want to unlock that isn't possible currently?

**Comment by paul-soporan** [comment]
Let's take our repository for example:

We use `@strictsoftware/typescript-plugin-monorepo` inside the `gatsby` workspace, but we had to patch it because it wasn't compatible with TypeDoc's new API.
I initially wanted to put the patch file inside a `.patches` folder at the root of the project, but that wasn't possible because `plugin-patch` uses [`parentFetch.packageFs`](https://github.com/yarnpkg/berry/blob/8dc90c245bc2f5c06f33c736d100e16a92e1ead7/packages/plugin-patch/sources/patchUtils.ts#L132) to read the content of the patch files.
The `WorkspaceFetcher`'s [`packageFs`](https://github.com/yarnpkg/berry/blob/8dc90c245bc2f5c06f33c736d100e16a92e1ead7/packages/yarnpkg-core/sources/WorkspaceFetcher.ts#L22) is a `JailFS` targeting the workspace cwd, which means that it can't access any other paths inside the project.
This means that, currently, each workspace has to have its own patches folder because it can't access patch files stored outside its folder.

I consider this as a bug, since I can't think of a good reason why this should be the case. It makes sense for the workspace packageFs to be based on the workspace's cwd and be jailed, but not jailed from the entire project. Also, giving it access to the entire project doesn't have any security implications, since Yarn owns both the project and the individual workspaces.

Even if this problem didn't exist, it still makes sense for `JailFS` to have this feature. `JailFS`'s purpose is to sandbox everything to a single folder, but that folder is currently hardcoded as the target of the `JailFS`. With levels, we can sandbox everything to a folder's parent while still keeping the target as the folder.

Note: If we implement this, it would also be possible in the future to implement a `--save` flag to `yarn patch-commit`, that would store all patches in something like `.yarn/patches`.

**Comment by arcanis** [comment]
That makes sense, but

> Even if this problem didn't exist, it still makes sense for `JailFS` to have this feature. `JailFS`'s purpose is to sandbox everything to a single folder, but that folder is currently hardcoded as the target of the `JailFS`. With levels, we can sandbox everything to a folder's parent while still keeping the target as the folder.

This is already possible by using `new CwdFS('workspace-path', {baseFs: new JailFS('workspace-root')})`, isn't it? The purpose of JailFS is to jail, so I'm not sure a level option makes sense semantically - I would prefer to instead compose layers as needed.

That being said, I feel like a simpler solution would be to just turn:

```ts
if (parentFetch.localPath) {
  return {packageFs: new JailFS(sourcePath, {baseFs: sourceFs}), releaseFs: effectiveParentFetch.releaseFs, prefixPath: PortablePath.root, localPath: sourcePath};
} else {
  return {packageFs: new JailFS(sourcePath, {baseFs: sourceFs}), releaseFs: effectiveParentFetch.releaseFs, prefixPath: PortablePath.root};
}
```

Into:

```ts
if (parentFetch.localPath) {
  return {packageFs: new CwdFS(sourcePath, {baseFs: sourceFs}), releaseFs: effectiveParentFetch.releaseFs, prefixPath: PortablePath.root, localPath: sourcePath};
} else {
  return {packageFs: new JailFS(sourcePath, {baseFs: sourceFs}), releaseFs: effectiveParentFetch.releaseFs, prefixPath: PortablePath.root};
}
```

This way third-party packages would still be jailed, but local workspaces would have enough leeway to reach the root of the project.

**Comment by paul-soporan** [comment]
Right, I totally forgot about `CwdFS` 🤦. I'll remove the levels part and use it instead.

**Pull request merged**
