### PR TITLE
feat(pnp): better builtin not found error with considerBuiltins disabled

### PR DESCRIPTION
**Pull request by paul-soporan**
**What's the problem this PR addresses?**

The builtin PnP resolver in `enhanced-resolve` uses `considerBuiltins: false` and resolves builtins separately, but only if the Webpack application runs inside a NodeJS context. This can sometimes lead to cryptic errors - `Your application tried to access fs but it isn't declared in your dependencies`.

**How did you fix it?**

I've added a new branch to the `pnpapi.resolveToUnqualified` smart error reporting, which reports a different, more verbose, kind of error in case a builtin is not found and `considerBuiltins` is set to `false`.

I've also bumped `pnpapi.versions.std`, since:

1) I had to create a new category for the test I added in `pnpapi.test.js`.
2) There are already at least 3 changes since the last `std` bump (ancestor breaking the chain in missing peer dependency errors, preserving trailing slashes, and now this).

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [ ] I have verified that all automated PR checks pass.

### CODE REVIEW

**Comment by arcanis** [comment]
Good idea 👍

That said, the `std` namespace is more from a public API interface (for example adding a new function, or a new parameter, or changing a return type) - I'm not sure there's really a need to bump it here 🤔

**Comment by paul-soporan** [comment]
I think I agree with this, but it's still a bit weird that the `VERSIONS` field only contains integers instead of semver ranges. We should at least add a mention that it is only bumped on breaking changes.

**Comment by paul-soporan** [comment]
Ignore that comment, I now realize that it's not actually for breaking changes only, but for any signature changes.

**Comment by arcanis** [comment]
I made a few tweaks:

- I moved the changelog into the main one (otherwise I suspect few will find it)

- I kept the same error code (semantically, the reason why the resolution failed doesn't change from the fact that the underlying problem is an undeclared dependency error; using a different error code could lead to code leveraging the API to meet weird behaviours if they don't special-case this error code).

- I reworded a bit the message

**Comment by arcanis** [comment]
All green ✅ really good idea, it was a bit difficult to know what was going on 👍

**Pull request merged**
