### PR TITLE
fix npm tag resolver when dedupe

### PR DESCRIPTION
**Pull request by goloveychuk**
**What's the problem this PR addresses?**
Fixes `Registry failed to return tag "8.4.1"` when running `yarn dedupe`
If I add 
`console.log(descriptor, locator.reference)`
it logs
```
{
  identHash: 'c463d28440264a050b6c82da90fae465d199a53c829a9fe2e382b672d4cbe014f84892bf0c630287a36347a4e407d33459c9581068c99d313332886ced75b781',
  scope: null,
  name: 'node-gyp',
  descriptorHash: '899f4448539abee8008ed64335a3b2bfb86e39a574e1267d2582a99b0865c3b00672068397645824a04ed0141f7f43c439ae8248539b250f8c76e24831ed0b94',
  range: 'npm:latest'
} 
npm:8.4.1::__archiveUrl=https%3A%2F%2Fregistry.com%2Fartifactory%2Fapi%2Fnpm%2Fnpm-repos%2Fnode-gyp%2F-%2Fnode-gyp-8.4.1.
```
I guess it's self explanatory 

...

**How did you fix it?**
Uses Semver resolver instead of tag resolver

...

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

**Review by merceyz — CHANGES_REQUESTED** [review]
Thanks for the PR, could you add a test to https://github.com/yarnpkg/berry/blob/1860cf48865b515a783e5ad48e34a059a120d2fc/packages/acceptance-tests/pkg-tests-specs/sources/commands/dedupe.test.ts?

**Comment by goloveychuk** [comment]
@merceyz I tried, but not sure how to mock yarn.lock resolution

**Comment by goloveychuk** [comment]
@merceyz added test

**Comment by goloveychuk** [comment]
Can we merge while it's fresh?

**Review by merceyz — APPROVED** [review]
LGTM though I see some of the other resolvers are also using `this.getCandidates` so @arcanis could you take a look as well?

**Comment by goloveychuk** [comment]
Any update?

**Comment by arcanis** [comment]
I think it'd make sense to use `opts.resolver` rather than `this` everywhere, but I'd prefer to test it for some time in a RC-like release to be sure. In the meantime it should be fine to merge this specific change.

**Pull request merged**
