### PR TITLE
fix(npm-cli): count all instances of ignored advisories

### LINKED ISSUE #5104: [Bug?]: Ignoring NPM audit advisories fails for packages included multiple times
### Self-service

- [X] I'd be willing to implement a fix

### Describe the bug

The new `npmAuditIgnoreAdvisories` feature for `yarn npm audit` (#4356) doesn't work if a vulnerable package is included multiple times (i.e., due to multiple dependency chains).

### To reproduce

```js repro
await packageJsonAndInstall({
    dependencies: {
        'query-string': '^7.1.1',
        'micromatch': '^3.0.5',
    }
})

const result = yarn('npm', 'audit', '--recursive', '--ignore', '1085054');

expect(result).resolves.not.toThrow();
```

(This repro seems to work locally, but I've had trouble getting reliable results in the playground.)

### Environment

```shell
System:
    OS: macOS 13.0.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 14.20.1 - /private/var/folders/j5/l20bwyp12yb180ql522y2t3w0000gn/T/xfs-9ff94d1f/node
    Yarn: 4.0.0-rc.32.dev - /private/var/folders/j5/l20bwyp12yb180ql522y2t3w0000gn/T/xfs-9ff94d1f/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v14.20.1/bin/npm
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by B4ckslash**
**What's the problem this PR addresses?**

When a package was used in multiple dependency chains, ignoring the relevant advisory via `--ignore` or `npmAuditIgnoreAdvisories` only reduced the vulnerability count by 1, whereas every chain including the affected package counted towards the vulnerability count separately. Therefore `yarn npm audit --recursive` exits with a non-zero exit code, even though all found advisories were marked as ignored. This broke our CI pipeline, which relies on the exit code of the audit run to check if any vulnerabilities are present.

Closes #5104 

**How did you fix it?**

Instead of reducing the vulnerability count by 1 per ignored advisory, it now gets reduced by the number of all affected paths of the ignored advisory entry.

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

**Comment by B4ckslash** [comment]
I selected the packages that need a release as best I could, but I am not 100% sure that the list is complete. If a declined package needs to be updated as well, let me know and I will update the file accordingly.

**Comment by B4ckslash** [comment]
@merceyz any idea why that specific windows integration test would exceed the timeout in some tests?

**Comment by arcanis** [comment]
Windows sometimes timeouts, we just retry it, it's fine as long as the failing tests don't look related to your changes.

The change seems globally fine, but can you add an extra test to avoid regressions?

**Comment by B4ckslash** [comment]
I guess I can, but given that there is basically no infrastructure around testing `yarn npm audit` that's gonna take a while. Just from a quick look around the integration tests I'd have to:
* extend the integration test package server to handle audit requests,
* add some fake packages to said server 
* add fake advisories for the new fake packages
* write the actual tests  

Could you perhaps greenlight this PR and I pinky-promise to create another PR with the tests? I understand if that's not an option, but otherwise this fix will take a fair while before being ready.

**Review by merceyz — APPROVED** [review]
LGTM!

---

Re https://github.com/yarnpkg/berry/pull/5194#issuecomment-1380974102
Yeah, you shouldn't have to setup all the infrastructure required to test this.

**Comment by B4ckslash** [comment]
So, uh.. how does this get merged then? :D

**Comment by B4ckslash** [comment]
@merceyz sorry to ping you like this, but can this get merged?

**Comment by merceyz** [comment]
I would merge this but the (unrelated) failing Netlify build is stopping me.

**Pull request merged**
