### PR TITLE
[node-modules] Improve deduplication efficiency by tracking ancestor dependencies

### PR DESCRIPTION
**Pull request by larixer**
**What's the problem this PR addresses?**

The deduplication efficiency is still poor both size-wise and performance-wise in `master`

**How did you fix it?**

I have rewritten hoisting algorithm to hoist dependencies from the whole tree into current root node to improve performance and added ancestor dependencies tracking to improve deduplication efficiency. This has simplified algorithm in some areas (checks) and sophisticated in another areas (node cloning), but generally it is now far superior than the one used in `master` both size-wise and performance-wise. It is not yet as perfect as it can be, but it is still a good checkpoint IMO.

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
@larixer In https://github.com/babel/babel/pull/11167, the size of all the `node_modules` folders is 7.8GB, vs ~1GB with Yarn 1 + lerna.

Let me know when I can test this PR!

**Comment by larixer** [comment]
@nicolo-ribaudo Sure, I will

The difference in size is certainly above what I have expected, I will test on babel repo the deduplication efficiency, since on my repo it was only 18% worser (10% due to native package installation by v2 for the cpu and os variants that are different from current OS and CPU and 8%, due to v1 and npm have bug when they quite often violate peer dependency promise in certain situations)

**Comment by nicolo-ribaudo** [comment]
I'm computing the `node_modules` total size with this command:
```
du -s node_modules codemods/*/node_modules eslint/*/node_modules packages/*/node_modules | tr -cd '0-9\n' | xargs | tr ' ' '+' | bc
```

With yarn 1 + lerna I'm getting `1012845`KB (989 MB) ([this branch](https://github.com/babel/babel/tree/next-8-dev)), while with yarn 2 I get `8139216`KB (7.76 GB) ([this PR](https://github.com/babel/babel/pull/11167)).

**Comment by larixer** [comment]
@nicolo-ribaudo Currently on this PR I have:
```
➜  babel git:(yarn-2-compat) ✗ du -s node_modules codemods/*/node_modules eslint/*/node_modules packages/*/node_modules | tr -cd '0-9\n' | xargs | tr ' ' '+' | bc
1191192
```
Could you give it a shot please?

**Comment by nicolo-ribaudo** [comment]
Somehow I get way less (644720), but all the tests are passing :+1:

Also, this _feels_ faster (I don't know if it's true), because the loading bar appears immediately instead of after a few seconds.

**Comment by larixer** [comment]
@nicolo-ribaudo Yes, it is much faster, now the hoisting takes 1 second for babel. And I'm still going to improve that in next PRs :)

**Comment by larixer** [comment]
@nicolo-ribaudo Oh, also the whole thing is much faster thanks to @arcanis PR:
https://github.com/yarnpkg/berry/pull/997
and another one by @crubier will soon be merged:
https://github.com/yarnpkg/berry/pull/997

**Comment by nicolo-ribaudo** [comment]
OMG I can't believe my eyes :heart_eyes: 

This is with an empty cache:
https://travis-ci.com/babel/babel/jobs/291806125

- 2m to download from the registry
- 18.92 SECONDS TO LINK

I guess that the `node_modules` cache isn't necessary anymore :smile:

**Comment by arcanis** [comment]
🚀

**Comment by larixer** [comment]
@nicolo-ribaudo Sorry, this PR happened to be broken. I have run `selfCheck` function to check hoisting tree, it generated string, but I forgot to show or throw this string and thought all is well, but in reality it detected errors.

**Comment by nicolo-ribaudo** [comment]
No worries, I will test the other PR when it doesn't have the "in progress" label :+1:

**Pull request merged**
