### PR TITLE
fix(nm): pnp should be a prod dep of nm

### PR DESCRIPTION
**Pull request by zkochan**
**What's the problem this PR addresses?**

Currently when using the nm package directly, there is compilation error because pnp is not in the deps:

image

**How did you fix it?**

...

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

**Review by RDIL — APPROVED** [review]

**Comment by larixer** [comment]
Stop, guys @zkochan and @RDIL , it doesn't make sense. `@yarnpkg/nm` doesn't use anything from `@yarnpkg/pnp` except types. Have you tried to figure out deeper before just adding `@yarnpkg/pnp` as a prod dependency?

**Comment by larixer** [comment]
In other words the compiled code of `@yarnpkg/nm` has no imports from `@yarnpkg/pnp` at all, it does not makes sense to me, that `@yanrpkg/pnp` is a production dependency in this case, what do you think?

**Comment by arcanis** [comment]
Fwiw I personally have no qualms with it being a regular dependency, my thinking being that regular deps are meant to be all the deps required for a package to work properly once installed by users, whether it's at runtime or typecheck.

Anecdotically, it's the same interpretation we follow in `@yarnpkg/extensions`:

- https://github.com/yarnpkg/berry/blob/master/packages/yarnpkg-extensions/sources/index.ts#L163
- https://github.com/yarnpkg/berry/blob/master/packages/yarnpkg-extensions/sources/index.ts#L878
- https://github.com/yarnpkg/berry/blob/master/packages/yarnpkg-extensions/sources/index.ts#L56-L68

**Comment by larixer** [comment]
> Fwiw I personally have no qualms with it being a regular dependency, my thinking being that regular deps are meant to be all the deps required for a package to work properly once installed by users, whether it's at runtime or typecheck.

What is your objective point here, except your sole opinion?

> Anecdotically, it's the same interpretation we follow in @yarnpkg/extensions:

We could have used `devDependencies` in this case as well, so I don't see how this can be considered as a counterpoint at all. 

Let's discuss seriously.

**Comment by larixer** [comment]
I think in this case the `@yarnpkg/pnp` should be declared in `peerDependencies` instead. I cannot find a better specification for `package.json` fields then from here:
https://docs.npmjs.com/cli/v8/configuring-npm/package-json#peerdependencies 
and assume the majority of the people rely on the meanings documented there.

Read the section about `peerDependencies` and compare with this case. `@yarnpkg/nm` does not `require` `@yarnpkg/pnp` it just expresses compatibility on the interface level, that's why `@yarnpkg/pnp` should be a peer dependency.

**Comment by zkochan** [comment]
Compatibility is already guaranteed by the types. Not compatible code will not compile. I have not yet seen any types declared as peer dependencies. It would worsen the DX. Especially as Yarn doesn't automatically install the peer deps.

**Comment by larixer** [comment]
> Compatibility is already guaranteed by the types. Not compatible code will not compile.

Of course not compatible code will not compile, but you don't know with which version of the package it is compatible. That's why peer dependency expresses the version of the package it is compatible with.

> I have not yet seen any types declared as peer dependencies. 

Can't be a point in discussion.

> It would worsen the DX. Especially as Yarn doesn't automatically install the peer deps.

It depends on the tools you use and how you use them. Having dependencies declared as production that are really not production can worsen your DX too, think of extra install time and extra disk space consumed by an application in the cloud.

**Comment by zkochan** [comment]
The file that I need doesn't use pnp at all, so if you choose to make it a peer, it would be nice to move the hoist function to a separate package.

**Pull request merged**
