### PR TITLE
feat(logs): collapsed logs by default in Gitlab CI

### PR DESCRIPTION
**Pull request by mr-wildcard**
**What's the problem this PR addresses?**
Context: Gitlab CI logs only.

I find that yarn is a bit too verbose while installing dependencies. The noise produced by the logs can be reduced by collapsing yarn step's logs by default in Gitlab CI job logs.

<details>
 <summary>Current state of Yarn output:</summary>

yarn_gitlab_logs

</details>
...

**How did you fix it?**
Added `[collapsed=true]` to sections start when `process.env.GITLAB_CI` is truthy.

...

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

**Comment by arcanis** [comment]
If there's a problem in the middle of an install, can we cancel the collapsing?

**Comment by mr-wildcard** [comment]
> If there's a problem in the middle of an install, can we cancel the collapsing?

would it be an "ok" test if :
- I add `[collapsed=true]` in my `.yarn/releases/yarn-berry.cjs`
- then a `"postinstall": "exit 1"` in one of my workspace?

**Comment by mr-wildcard** [comment]
@arcanis 
I did the following tests : 
- added `[collapsed=true]` in my `.yarn/releases/yarn-berry.cjs`
- added a non-existing version of a package in one of my workspace to make resolution step fail

<details>
<summary>unfortunately, Gitlab let the block of logs collapsed even if a command exited with a non-zero code.</summary>

Aug-09-2021 11-44-19

</details>

I saw several proposals in gitlab issues to improve this, but for now, not being able to know from which script the error comes from is bad DX..

**Comment by arcanis** [comment]
Indeed, https://gitlab.com/gitlab-org/gitlab/-/issues/290225 would be nice to have 😕 

That being said, other CI providers are currently configured as auto-folded, so there's no reason to not do that for Gitlab as well, if only by consistency. Thanks! 👍

**Pull request merged**
