### PR TITLE
fix(www): responsive issues on detail view

### PR DESCRIPTION
**Pull request by Haroenv**
**What's the problem this PR addresses?**

before: 
Screenshot 2020-02-04 at 16 16 19

**How did you fix it?**

in v1 the sidebar is after the readme, and I feel like that made more sense

The "files" tab floats left, so the sidebar needs to float right to make sense.

### CODE REVIEW

**Comment by arcanis** [comment]
This is basically a revert of #877 right?

I think I prefer the current design on mobile - the previous one was a bit difficult to read with the half-width. Regarding the readme, I honestly always read at the one from GitHub anyway and almost never at the one on the registry - so I'd prefer to have registry-only informations (such as dependencies, versions, repository, etc) visible on first sight.

There is one problem with the current design though that we should look into - if we open the "files" tab from a package, this is what we currently get:

image

Your PR fixes that, but I'd prefer to keep the rest of the mobile layout if possible.

**Comment by Haroenv** [comment]
Not a revert, just a reorder of the columns, now the aside is showing first, but in classic we had the readme showing first.

**Comment by Haroenv** [comment]
cc @Ayc0

**Comment by arcanis** [comment]
Hm this is what I get on the preview - is it expected?

image

**Comment by Haroenv** [comment]
no, this must have been an error!

**Comment by Haroenv** [comment]
the response css part of this is quite different than v1 was, so it's quite confusing. I think I've made it work now, but let's wait on the preview

**Comment by Ayc0** [comment]
I'm working on a reorganization of this page on desktop & mobile but I didn't have the time to push it and to create a PR

**Comment by Haroenv** [comment]
Can we merge this while waiting for more reorganisation later? The file browser is misaligned now, without my fix

**Comment by arcanis** [comment]
Merging 👍 I might make a PR latter on to put back the details before the readme though ...

**Pull request merged**
