### PR TITLE
docs: Add @liuli-util/yarn-plugin-changed plugin

### PR DESCRIPTION
**Pull request by rxliuli**
**What's the problem this PR addresses?**

Avoid that yarn workspaces foreach will execute commands in all modules every time. It implements the cache function of yarn workspaces foreach based on git (committed) and file hash (not yet submitted).

...

**How did you fix it?**

...

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [ ] I have set the packages that need to be released for my changes to be effective.

- [ ] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

**Comment by arcanis** [comment]
Note that https://github.com/yarnpkg/berry/pull/3459 will seemingly implement the same feature

**Comment by rxliuli** [comment]
> Note that #3459 will seemingly implement the same feature

I took a look and it was doing very similar things, but each developer always had a slightly different idea. Due to the use of monorepo, some of our modules will depend on other modules, so we must build the modules that it depends on before building certain modules. We always declare the setup command in the module being used, and then run `yarn && in the root directory yarn setup:all` to initialize all dependencies, but the build cache only exists locally and is not written to git. If I need to publish, I will write other plug-ins or cli to implement functions.

I have researched some other plugins before building the plugin, but they still can’t meet my needs, so I built my own

- ultra-runner
- yarn.build
- yarn plugin changed

**Comment by jdanil** [comment]
Hi @rxliuli, just to confirm some things...

> Due to the use of monorepo, some of our modules will depend on other modules, so we must build the modules that it depends on before building certain modules.

Is this something that is already handled by the `--topological` and `topological-dev` options?
https://yarnpkg.com/cli/workspaces/foreach#options

I'm also not super clear why file hashes would be necessary if you are already using git to diff changes.

**Comment by rxliuli** [comment]
> Hi @rxliuli, just to confirm some things...
> 
> > Due to the use of monorepo, some of our modules will depend on other modules, so we must build the modules that it depends on before building certain modules.
> 
> Is this something that is already handled by the `--topological` and `topological-dev` options? https://yarnpkg.com/cli/workspaces/foreach#options
> 
> I'm also not super clear why file hashes would be necessary if you are already using git to diff changes.

Because not all files are submitted to git, such as some files that are being modified and tested locally but not submitted, this part needs to use hashFiles to calculate the difference

**Pull request closed without merging**
