### PR TITLE
feat(plugin-npm): export makePublishBody

### PR DESCRIPTION
**Pull request by merceyz**
**What's the problem this PR addresses?**

While looking over https://github.com/babel/babel/pull/12138, specifically the source for the plugin https://github.com/nicolo-ribaudo/yarn-plugin-babel-release-tool, I noticed [it uses `makePublishBody`](https://github.com/nicolo-ribaudo/yarn-plugin-babel-release-tool/blob/b4bdc912bec2b8386ac44db8b4065e9aeebc2c9f/sources/utils/npm-publish.ts#L24-L103) from `@yarnpkg/plugin-npm-cli` which isn't exported, so @nicolo-ribaudo had to copy it. We should export that method to allow plugin makers to use it.

cc @nicolo-ribaudo 

**How did you fix it?**

Export `npmPublishUtils.makePublishBody` in `@yarnpkg/plugin-npm`

**Checklist**
- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).
- [x] I have set the packages that need to be released for my changes to be effective.
- [x] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
:heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: 

I didn't want to ask, but this would definitely help!

**Comment by nicolo-ribaudo** [comment]
Wasn't this released in 2.3.3? The last version of `plugin-npm` is 2.3.0 :thinking:

**Comment by nicolo-ribaudo** [comment]
Oh nvm, it will be in 2.4.0. Sorry!

**Comment by merceyz** [comment]
Yeah, it was a small patch release to fix a hoisting bug, sorry.

ref https://github.com/babel/babel/pull/12172

**Pull request merged**
