### PR TITLE
fix(pnp): pick up changes to the `fs` module

### PR DESCRIPTION
**Pull request by merceyz**
**What's the problem this PR addresses?**

When using PnP it's not possible for the program to patch the `fs` module and have `require` use it.

Fixes https://github.com/yarnpkg/berry/issues/2050
Fixes https://github.com/streamich/fs-monkey/issues/208
Closes https://github.com/yarnpkg/berry/pull/3464

**How did you fix it?**

Added a `DynamicFS` that allows changing the `baseFs` at any point. It starts out using the `defaultFsLayer` and when/if the `fs` module is patched by PnP it is changed to a `NodeFS` with a live binding to the `fs` module.

Credit to @arcanis for the suggestion

**Checklist**
- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).
- [x] I have set the packages that need to be released for my changes to be effective.
- [x] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

**Comment by wood1986** [comment]
It works perfectly. When will you release?

**Comment by wood1986** [comment]
It works on my fs-monkey-bug repo. But it seems not working on my private repo. Will update you

**Comment by wood1986** [comment]
> It works on my fs-monkey-bug repo. But it seems not working on my private repo. Will update you

I think the not working issue in my private repo has nothing with your fix. You should be good to merge

**Comment by wood1986** [comment]
Thanks!! When will you release?

**Comment by merceyz** [comment]
Just started the build so in about 10 minutes https://github.com/yarnpkg/berry/actions/runs/1288578500
```sh
yarn set version berry && yarn set version canary
```

**Pull request merged**
