### PR TITLE
Add mdx-js/loader

### PR DESCRIPTION
**Pull request by flex-jonghyen**
**What's the problem this PR addresses?**

https://github.com/mdx-js/mdx/pull/1967
...

**How did you fix it?**

Add react as peer dependency of @mdx-js/loader

...

**Checklist**

- [ ] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [ ] I have set the packages that need to be released for my changes to be effective.

- [ ] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
`mdx-js/loader` is framework agnostic, it can be used with `react`, `vue`, `preact`, `emotion`, etc.
It is probably not a good idea to force `peerDependency` on `react`.

**Comment by arcanis** [comment]
Last I checked @mdx-js/loader worked fine without peer dependency (with the caveat that they don't support something like Babel's [`absoluteRuntime`](https://babeljs.io/docs/en/babel-plugin-transform-runtime#absoluteruntime), which forces the packages containing the mdx files to depend on React; imo they should fix that but that's a separate matter).

I'll close this PR for now since it doesn't contain a repro to make sure we're talking about the same thing.

**Comment by merceyz** [comment]
> imo they should fix that but that's a separate matter

I fixed it for them but they rejected it https://github.com/mdx-js/mdx/pull/1300

**Comment by ChristianMurphy** [comment]
> which forces the packages containing the mdx files to depend on React; imo they should fix that but that's a separate matter

Most of these comments seem targeted at MDX 1?
MDX 2 doesn't depend on `react` anymore (https://mdxjs.com/blog/v2/)

> On the runtime side, we can now compile JSX away to normal JavaScript and no longer need framework-specific code to glue them together with MDX. Now any JSX runtime, whether [classic or automatic](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html), is supported. This means MDX can be used with React, Preact, Vue, Emotion, Theme UI, Ink, you name it, plus anything that’s yet to be invented!

The `jsxImportSource` option can be used to configure the path, and can be a bare specifier or an absolute path.
But there is included/packaged version of `react` for `mdx` to be absolutely pointed at.

---

Discussion on improving how mdx resolves dependencies is definitely welcome, feel free to pop by https://github.com/mdx-js/mdx/discussions and start a thread.
And while PRs are always welcome (thanks @merceyz and @flex-jonghyen ❤️ )
I'd highly recommend discussing major changes to dependency resolution and the reasons behind them before opening a PR.

**Comment by arcanis** [comment]
> Most of these comments seem targeted at MDX 1?
> MDX 2 doesn't depend on `react` anymore (https://mdxjs.com/blog/v2/)

Hm that's quite possible - I used `@mdx/react` via Docusaurus, and it seems to be configured for MDX 1 indeed 🤔

(ping @Josh-Cena; no action required, just figured you might be interested since we discussed about it earlier)

**Comment by Josh-Cena** [comment]
> Hm that's quite possible - I used `@mdx/react` via Docusaurus, and it seems to be configured for MDX 1 indeed 🤔

Yeah, I'm aware that the dependencies of MDX v1 are quite messy (it also depends on Babel which _could_ be a performance bottleneck when our site is currently built with esbuild-loader), and that v2 cleans them up a great deal. Would be really looking forward to an upgrade 😄 (Won't be in Docusaurus v2 though)

https://github.com/facebook/docusaurus/issues/4029

**Pull request closed without merging**
