### PR TITLE
feat: support auth in proxy url

### PR DESCRIPTION
**Pull request by Leksat**
**What's the problem this PR addresses?**

Adds support for proxy URLs containing auth credentials. For example, `http://<username>:<password>@proxy.com:1234`

Closes https://github.com/yarnpkg/berry/issues/3684

**How did you fix it?**

It's really two lines of code. Take the credentials from the URL and pass them to the `tunnel` library.

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

**Comment by Leksat** [comment]
@arcanis `windows-latest w/ Node.js 17.x` failed with a timeout. Could you please restart it? Previous time it worked.

**Comment by arcanis** [comment]
Thanks!

**Comment by arcanis** [comment]
Upgrading to RC should be perfectly fine. RCs are just a way to indicate we may still land a couple of breaking changes; in terms of stability, they're at least as good as stable builds.

**Comment by jaunusa** [comment]
Good to know, I was wondering why my container crashes while running `yarn install` (rc.18) in a kubernetes environment. So in that case I'll trust you and will search for a different reason ;)
Thank you for the reply

**Pull request merged**
