### PR TITLE
Fix doctor not emitting nonzero exit code on failure

### LINKED ISSUE #2521: [Bug] `yarn dlx @yarnpkg/doctor` doesn't emit a nonzero exit code when it fails
- [x] I'd be willing to implement a fix

**Describe the bug**

When running `yarn dlx @yarnpkg/doctor` on a workspace with unmet transitive peer dependencies, I expected it to fail with a nonzero exit code, but the exit code was 0, indicating success. Haven't yet investigated if this is `doctor` not emitting the expected exit code or `dlx` swallowing it.

Not 100% sure if this is unintended, so feel free to close if it is and I'll reopen as a feature request. My intuition is it's a bug because it's inconsistent with other Yarn functionality that logs "Failed with errors", and anyone that wants to get the report while swallowing the exit code can just suffix the command with `|| true`

**To Reproduce**

Take any package that would fail `doctor`, run `doctor`, and check the exit code with `echo $?`.

Unsure how to write this in Sherlock, sorry.

**Screenshots**

image

**Environment if relevant:**

 - OS: macOS 11.2.1
 - Node version: 12.19.1
 - Yarn version: 2.4.0

**Additional context**

I'd like to integrate `doctor` into our CI to put us on the path towards eventually adopting PnP, but would like to avoid having to parse the output for the text `Failed with errors`.

### PR DESCRIPTION
**Pull request by sargunv**
**What's the problem this PR addresses?**

Resolves #2521. 

**How did you fix it?**

Captured the report from `StreamReport.start()` and returned its exit code in the command's `execute` method.

**Checklist**
- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).
- [x] I have set the packages that need to be released for my changes to be effective.
- [x] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

**Review by merceyz — APPROVED** [review]

**Review by paul-soporan — APPROVED** [review]

**Comment by paul-soporan** [comment]
Thanks!

**Comment by benatshippabo** [comment]
@paul-soporan any chance we can push this patch to npm?

**Comment by merceyz** [comment]
We're preparing for a release so it will be soon™

**Comment by benatshippabo** [comment]
So I think I found a bug with version `3.0.0-rc.2`, when there is a mising peer dependency, it no longer lists the missing peer dependency and instead crashes with an error message:

```
➤ YN0000: ┌ /Users/btea/git/repo/packages/access/package.json
➤ YN0001: │ Error: Invalid property type: ArrayLiteralExpression
    at buildJsonNode (/Users/btea/.npm/_npx/8344/lib/node_modules/@yarnpkg/doctor/lib/cli.js:167:19)
    at async checkForUnmetPeerDependency (/Users/btea/.npm/_npx/8344/lib/node_modules/@yarnpkg/doctor/lib/cli.js:187:26)
    at async processManifest (/Users/btea/.npm/_npx/8344/lib/node_modules/@yarnpkg/doctor/lib/cli.js:227:17)
    at async processWorkspace (/Users/btea/.npm/_npx/8344/lib/node_modules/@yarnpkg/doctor/lib/cli.js:244:5)
    at async /Users/btea/.npm/_npx/8344/lib/node_modules/@yarnpkg/doctor/lib/cli.js:311:29
    at async StreamReport.startTimerPromise (/Users/btea/.npm/_npx/8344/lib/node_modules/@yarnpkg/doctor/node_modules/@yarnpkg/core/lib/StreamReport.js:219:20)
    at async /Users/btea/.npm/_npx/8344/lib/node_modules/@yarnpkg/doctor/lib/cli.js:298:25
    at async Function.start (/Users/btea/.npm/_npx/8344/lib/node_modules/@yarnpkg/doctor/node_modules/@yarnpkg/core/lib/StreamReport.js:132:13)
    at async EntryCommand.execute (/Users/btea/.npm/_npx/8344/lib/node_modules/@yarnpkg/doctor/lib/cli.js:285:24)
```

**Comment by arcanis** [comment]
It's more likely there's a field somewhere in your package.json that has an unexpected type. Can you try removing fields one by one until you identify the failing syntax? You can also go faster and edit `buildJsonNode` (cf stacktrace) to log the field name and its type.

**Comment by benatshippabo** [comment]
I created a minimal example with the default package.json https://github.com/benatshippabo/yarn-doctor-bug and a missing peer dependency that reproduces the bug

**Comment by benatshippabo** [comment]
Okay I created an issue for this with a reproduction using Sherlock

**Pull request merged**
