### PR TITLE
Updates to the latest TS patch

### PR DESCRIPTION
**Pull request by arcanis**
**What's the problem this PR addresses?**

https://github.com/typescript-eslint/typescript-eslint/issues/1592

**How did you fix it?**

https://github.com/microsoft/TypeScript/pull/35206/commits/bba19af4c7264c6e4232ffc8d0f5a141860e9fe1

Test it with:

```
yarn set version from sources --branch 1205
yarn install
```

### CODE REVIEW

**Comment by regevbr** [comment]
@arcanis sadly this causes OOM error...
Do you have access to a windows machine to test it out?

**Comment by regevbr** [comment]
the last stack trace from the OOM error indicated that it exited at while using the __rest method
```js
    if (options && options.plugnplay === false) {
      const {
        plugnplay
      } = options,
            rest = __rest(options, ["plugnplay"]); // Workaround a bug present in some version of Node (now fixed)
      // https://github.com/nodejs/node/pull/28078
```

**Comment by regevbr** [comment]
I realized from your code that you only applied the patch to typescript 3.9.
Trying to install it returns `Cannot apply hunk #1` (you have a misspell in your code) that originates from the apply.ts file in plugin-patch/sources/tools

**Comment by regevbr** [comment]
So the patch doesn't really patch ts3.8 so the issue still persists.
Trying to install @next fails to apply the patch: `Cannot apply hunk #1`
@arcanis can you please advise?

**Comment by regevbr** [comment]
@arcanis is there something I can help with here?

**Comment by regevbr** [comment]
@arcanis I can confirm this now works well in windows with ts3.8! thanks!

**Comment by arcanis** [comment]
Perfect, thanks! 🙂

**Pull request merged**
