### PR TITLE
Improve navigation of website (specially on mobile)

### PR DESCRIPTION
**Pull request by Ayc0**
### Main structure

- reduce the size of menu item
  - takes less space
    - width: 300px -> 260px
    - padding: 1.5em -> 1em
  - more readable
- [use fewer borders](https://twitter.com/steveschoger/status/897849211110273024)
- unify marker of top nav and of side menu
- add hover behavior
- [avoid using text justify](https://designforhackers.com/blog/justify-text-html-css/)

Before | After
-|-
image | image
image | image
image | image
image | image

### Improve mobile website

- reduce padding of document: 2em -> 1em (only on mobile)
- fix z-index issue with main navigation
- make sub navigation scrollable instead of taking a lot of place on the page
(the padding are set to cut the text and so to highlight that this div is scrollable)
- add shadow on main nav
- use `x` in menu toggle when is open
- center and use a gray color for the content on the menu toggle
- avoid cutting title in their middle

Before | After
-|-
image | image
image | image
image | image

### CODE REVIEW

**Comment by arcanis** [comment]
Nice, especially the mobile changes! On desktop I have a few comments:

---


---

The new bottom border on the header looks a bit awkward on the home page: 

image

---

The borders don't merge well on the Getting Started page (before, it was doing the right transition):

image

---

The content left margin needs to be adjusted for the new navigation width:

image

**Comment by andreialecu** [comment]
Thoughts on: https://github.com/yarnpkg/berry/issues/785 ?

**Comment by Ayc0** [comment]
@arcanis I reverted the background of the editor and the styling of the top bar + sidebar to remove the line on the home page + to link the 1st item to the top bar

image

image

**Comment by Ayc0** [comment]
@andreialecu I want to improve other pages, but will do in another PR

**Comment by arcanis** [comment]
Awesome! Thanks @Ayc0 👍

**Pull request merged**
