### PR TITLE
feature(shell): simple integer arithmetic in scripts

### PR DESCRIPTION
**Pull request by bgotink**
**What's the problem this PR addresses?**

I've got a couple of packages with simple arithmetic the scripts section, e.g.

```json
"scripts": {
  "test": "ng e2e --port $((RANDOM + 1024))"
}
```

The idea is to use a random port to prevent problems if the user has an angular app running on the default port or if they have other e2e tests running at the same time.

**How did you fix it?**

Add support for `$RANDOM` and the simple `+`/`-`/`*`/`/` arithmetic into the yarn shell.

BASH arithmetics are a bottomless pit of features, with `(( ))` and `$(( ))`, assignment operators, even allowing for C-style for-loops

```bash
count=10
for ((i = 0; i < count; i++)); do
  echo 'Why?'
done
```

This PR only introduces the very basic operators in `$(( ))`, as those are probably the most useful for one-line scripts.

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [ ] I have verified that all automated PR checks pass.

### CODE REVIEW

**Comment by arcanis** [comment]
Can you add a line to the Changelog? I can't edit your PR

**Comment by 7rulnik** [comment]
BTW you can set 0 port and system will choose free random port

**Comment by bgotink** [comment]
> Can you add a line to the Changelog? I can't edit your PR

That's weird, I always check this box

screenshot of this PR's "allow edits by maintainers" checkbox

I've added a line to the changelog

> BTW you can set 0 port and system will choose a free random port

I didn't realise that'd also work for the angular CLI, thanks!
For this specific example that'd work, though for other scripts we'll still need calculations

**Comment by arcanis** [comment]
Perhaps VSCode didn't clone the branch properly ... editing through the GH interface seems to have worked 🤔

**Pull request merged**
