### PR TITLE
Add --no-progress to legacy flags

### PR DESCRIPTION
**Pull request by SandersAaronD**
**What's the problem this PR addresses?**

The --no-progress flag is sometimes used in build systems to suppress the progress bar from yarn 1. This causes builds upgraded to yarn 4, or builds that cover multiple repositories with different yarn versions, that use --no-progress to fail. If added to the legacy flags, those builds will warn about the deprecated flag but not fail.

--no-progress is undocumented, but definitely present in yarn classic.

**How did you fix it?**

- Added --no-progress to legacy flags so that builds that receive --no-progress will warn but not error

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [ ] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

**Comment by arcanis** [comment]
We tend to only add legacy flags for cloud providers (individual users should migrate their projects rather than rely on legacy flags that aren't supported). What's the situation where this flag is required?

**Comment by SandersAaronD** [comment]
> We tend to only add legacy flags for cloud providers (individual users should migrate their projects rather than rely on legacy flags that aren't supported). What's the situation where this flag is required?

Drone builds for a series of related projects specifies --no-progress, which makes the upgrade path for them difficult. Since --no-progress errors in yarn 4, we have to either atomically upgrade all project builds at once (which isn't feasible), do a possibly complicated and flaky yarn version check around the flag in all related builds, or -- I guess -- remove the flag from the builds and accept that terminal output for all our yarn 1 projects is messed up until we get them upgraded, which also isn't really an option.

I'd think it should be a legacy flag simply to make the upgrade path smoother, but it's not my call. We are a cloud provider, if that's a deciding factor, although this workflow isn't user-facing.

**Comment by SandersAaronD** [comment]
I have no idea why some of the automated checks are dying for this, think it's a project issue. Can't really devote more time to this PR so I'm marking it ready, if it's not good as-is probably reject it.

**Comment by arcanis** [comment]
I think for consistency we'll avoid adding that flag. The CLIs are quite different between v1 and v2+, so `--no-progress` likely won't be the only case where using different arguments based on the implementation will be necessary.

**Pull request closed without merging**
