### PR TITLE
feat(compat): update patch for typescript 4.3

### PR DESCRIPTION
**Pull request by merceyz**
**What's the problem this PR addresses?**

The PnP patch for TypeScript doesn't apply to typescript@>=4.3.1-rc

Closes https://github.com/yarnpkg/berry/issues/2799
Closes https://github.com/yarnpkg/berry/issues/2938

**How did you fix it?**

Rebased https://github.com/microsoft/TypeScript/pull/35206 onto 4.3.2

**Checklist**
- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).
- [x] I have set the packages that need to be released for my changes to be effective.
- [x] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

**Comment by sirreal** [comment]
👍  I was able to upgrade to TypeScript 4.3.2 when using the build from this branch. `tsc` appeared to work as expected.
```
yarn set version from sources --branch merceyz/fix/typescript-4.3
yarn up typescript
```

I'm using the node-modules linker.

**Comment by jtbandes** [comment]
These changes seem to break bundling typescript for the browser, because of the dynamic `require("module")` call which won't work in the browser.

More details on similar issues at https://github.com/microsoft/TypeScript/issues/39436

I guess one can probably work around it by further patching TypeScript during bundling to remove the `getPnpTypeRoots` logic, so I'll be trying that next...

**Comment by SimenB** [comment]
Will there be a release of this similar to how there was one for typescript@4.2 (in yarn 2.4.1)?

**Comment by arcanis** [comment]
Yes, I just released 2.4.2 which includes this fix.

**Comment by SimenB** [comment]
Wonderful, thank you!

**Pull request merged**
