### PR TITLE
Fixes tgz file normalization

### PR DESCRIPTION
**Pull request by arcanis**
**What's the problem this PR addresses?**

When a tgz is converted into a zip, Yarn doesn't normalize the files order. As a result, the output may be different depending on how a pack got generated. In a case I saw in the wild, a repository was being built by Yarn 1 or Yarn 3 depending on whether Corepack was installed (a separate bug), which caused checksum mismatches.

**How did you fix it?**

Yarn will now sort the files before writing them into the zip archives.

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

**Comment by merceyz** [comment]
> was being built by Yarn 1

Hm, Yarn 1 is supposed to sort the entries before it packs them https://github.com/yarnpkg/yarn/pull/8142

**Comment by arcanis** [comment]
> > was being built by Yarn 1
> 
> Note that Yarn 1 is supposed to sort the entries before it packs them [yarnpkg/yarn#8142](https://github.com/yarnpkg/yarn/pull/8142)

You can reproduce this issue with [DataDog/snowplow-javascript-tracker](https://github.com/DataDog/snowplow-javascript-tracker); packing this repository yields the following results with 1.22.15 (which includes this PR) and 3.2.3: https://gist.github.com/arcanis/2992eb9f1fef78ae7455bf1e8cb131ca

**Comment by merceyz** [comment]
Indeed they aren't the same but it's still sorted (just differently) so it should be stable.

**Comment by arcanis** [comment]
I opened https://github.com/yarnpkg/berry/pull/5049 to fix the Corepack issue - it should in theory be enough, so perhaps we can close this for now, which is more symptomatic than the real origin.

**Pull request closed without merging**
