### PR TITLE
fix: don't print the peerDependencies footer if all warnings are discarded

### PR DESCRIPTION
**Pull request by paul-soporan**
**What's the problem this PR addresses?**

We still printed the `Some peer dependencies are incorrectly met` footer even if all peer dependency warnings were discarded via log filters.

**How did you fix it?**

Made it only print the footer if at least a single peer dependency warning is printed.

**Checklist**

- [X] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [X] I have set the packages that need to be released for my changes to be effective.

- [X] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

**Comment by arcanis** [comment]
It feels a little complex, just to remove one entry 😕 I'd prefer to give it its own code and let people hide it if them want.

**Comment by paul-soporan** [comment]
> It feels a little complex, just to remove one entry

I don't feel it's that complex, it's just that I took the code of `startTimer{Promise,Sync}` and pasted it into `startSection{Promise,Sync}` minus a few parts. We could perhaps have a `startWhateverImpl` function so that both could share the same code?

> I'd prefer to give it its own code and let people hide it if them want.

I agree with making them have the same code as the peer dep warnings, but I'd prefer them to only be shown when relevant, since that's also what we do with things like the `Project validation` section, since that's the only fully correct solution.

**Comment by paul-soporan** [comment]
@arcanis What do you think about https://github.com/yarnpkg/berry/pull/3616/commits/8e626922edc13432191418d4efbf2a9830fd0432? I reimplemented the `startTimer`s using `startSection` and extracted the common code to a `startTimerImpl`. I feel like this removes the extra complexity, what do you think?

**Comment by arcanis** [comment]
Yep! 👍

**Comment by merceyz** [comment]
Should this have closed https://github.com/yarnpkg/berry/issues/3300?

**Pull request merged**
