### PR TITLE
Adds a brotli polyfill

### PR DESCRIPTION
**Pull request by arcanis**
**What's the problem this PR addresses?**

I'm experimenting with running Yarn in-browser via StackBlitz, but they don't currently support Brotli decoding (cc @d3lm).

**How did you fix it?**

Trying to use a polyfill when `brotliDecompressSync` isn't set.

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

**Comment by merceyz** [comment]
Assuming they support gzip It would result in a smaller bundle to use that instead of a Brotli polyfill
```
Master          1,91 MB (2 006 852 bytes)
gzip            2,07 MB (2 175 741 bytes)
Brotli polyfill 2,38 MB (2 499 088 bytes)
```

**Comment by d3lm** [comment]
Yea that's right, brotli is currently not supported but this is on my todo list! As @merceyz suggested you could use gzip via `zlib` or use the `brotli` polyfill that you're already using.

Out of curiosity, is there anything else you're running into that doesn't work? I think it would be great to use StackBlitz for yarn for demos and what not.

**Comment by arcanis** [comment]
It generally works pretty well! You can check my [playground](https://stackblitz.com/edit/node-kd4s7n). In particular fs and network are of no problem, and PnP works just fine. On the perf side, downloads seem fast but the zip conversions seem quite slow - it's weird since it's wasm, so I'd (perhaps naively) expect them to run inside the native browser wasm sandbox 🤔

> Out of curiosity, is there anything else you're running into that doesn't work? I think it would be great to use StackBlitz for yarn for demos and what not.

Current notes:

- I had to move the project into a subfolder to avoid the default package manager running.
- Since we can't configure the default PATH, an `init.js` file is needed to point `/bin/yarn` to our copy.
- Sometimes the command hang; removing the zip worker helped, but I had it happen once randomly after this.
- StackBlitz' save protocol sends all files on each save - with a 2MB file in the project, it's very very slow
- Opening the `yarn.js` file causes StackBlitz to crash

**Comment by arcanis** [comment]
@d3lm Out of curiosity, do you have an idea what could make wasm that slow?

**Comment by d3lm** [comment]
Some questions I have:
- What do you mean by workers don't work? Is that Node's `worker_threads`?
- Is that zip worker coming from yarn and instead of using Node's `zlib` you use a WASM module for uncompressing zip?

> Out of curiosity, do you have an idea what could make wasm that slow?
I'd have to take a look and see get some more information. WASM is generally pretty fast and also calls from JS <-> WASM are pretty cheap so it really depends on what it does and how it's implemented. Maybe you can tell me a bit more or point me to some code and I could have a look.

> StackBlitz' save protocol sends all files on each save - with a 2MB file in the project, it's very very slow
Yes, that's true. We need to improve this and it's good feedback!

> Opening the yarn.js file causes StackBlitz to crash
Yes, I have noticed that too and it's because of the syntax highlighting. It also takes a bit on local to fully highlight the entire file, except that on local it does that in a separate process (the extension host if you use VSC). Right now we don't run the syntax highlighter in a separate thread which causes the main thread to lock up if you open large files. We are aware of this and we are working on a lot of UI / editor improvements to make this experience much smoother.

**Comment by arcanis** [comment]
> What do you mean by workers don't work? Is that Node's `worker_threads`?

Yep; we run the zip conversion in a worker ([here](https://github.com/yarnpkg/berry/blob/master/packages/yarnpkg-core/sources/tgzUtils.ts#L48-L50)), and StackBlitz hangs when executing this part of the code. Modifying it to instead do the [zip conversion](https://github.com/yarnpkg/berry/blob/master/packages/yarnpkg-core/sources/worker-zip/Worker.ts#L16-L22) in the same thread seems to make it work.

> Is that zip worker coming from yarn and instead of using Node's zlib you use a WASM module for uncompressing zip? Or maybe I just misunderstood.

For compressing zip (which we generate after downloading the tgz from the remote registry) we use a WASM zlib/libzip (so that we can guarantee a deterministic output, which we can't do with the native zlib whose output may vary per system). For decompression we use the Node zlib (since it's always deterministic).

> I'd have to take a look and see get some more information. WASM is generally pretty fast and also calls from JS <-> WASM are pretty cheap so it really depends on what it does and how it's implemented. Maybe you can tell me a bit more or point me to some code and I could have a look.

I'll double-check, but the slow function seemed to be [`convertToZip`](https://github.com/yarnpkg/berry/blob/master/packages/yarnpkg-core/sources/tgzUtils.ts#L44-L53). While workers are disabled so some slowdown is expected, it also happens when fetching a single package (so workers wouldn't do much).

**Comment by d3lm** [comment]
Interesting. I don't think it's the workers and I expect the culprit to be somewhere else. There are many other tools which use worker threads quite heavily, suck as Next.js or Astro, SvelteKit etc. and I don't see any particular slowdown. In fact, spinning up a worker thread in WebContainer is equally fast as on local. It would be interesting to find out why it's hanging and why that WASM zlib library is slow. It's hard to tell without looking more closely into it.

But for your information, brotli is definitely on my todo list and I will probably work on this in the near future. I can't promise a specific timeline but it definitely has a higher priority on my end.

**Comment by d3lm** [comment]
Also I saw [here](https://github.com/yarnpkg/berry/blob/e04d01f4c477d945fedfd90d4bc1efcedf3548ac/packages/yarnpkg-core/sources/worker-zip/Worker.ts#L7) that you're sending the buffer via a `postMessage`. You might wanna try to transfer an ArrayBuffer instead and re-create the buffer backed by that same array buffer on the other end. This avoids copying the data to the worker, cause otherwise it will be a structural clone.

**Comment by merceyz** [comment]
Closing as brotli is now supported in StackBlitz.
Ref https://github.com/stackblitz/webcontainer-core/issues/339#issuecomment-1794565438.

**Pull request closed without merging**
