### PR TITLE
feat(fslib): add bigint support

### PR DESCRIPTION
**Pull request by merceyz**
**What's the problem this PR addresses?**

`@yarnpkg/fslib` is missing support for `bigint` stats

Fixes https://github.com/yarnpkg/berry/issues/2232

**How did you fix it?**

Implement support for `bigint` stats

**Checklist**
- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).
- [x] I have set the packages that need to be released for my changes to be effective.
- [x] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

**Comment by franciscofabian** [comment]
This works for me!

**Comment by iamacup** [comment]
I think this pull request needs a bit more attention – I don’t think this is a feature – its fixing a huge breaking bug – the documentation on the YARN website states that berry should be used for new projects – new projects are likely on the latest version of Node (15.x) – which, at time of writing, yarn berry does not work on at all – this pull request fixes it.

It’s a big deal, is all I am saying, and I think it needs a bit more love because right now the ‘new user experience’ is horrible – yarn 2 is broken if you follow the instructions on the yarn website :(

**Comment by merceyz** [comment]
> I don’t think this is a feature – its fixing a huge breaking bug

It's adding functionality to the `@yarnpkg/fslib` package which by definition is a feature, it just so happens to fix the PnP hook which has been forwarding these options to functions that didn't support it this whole time

> yarn berry does not work on at all

Yarn 2 works perfectly fine, it's PnP that doesn't work correctly on Node 15, the `node-modules` linker has no issues

**Comment by merceyz** [comment]
Closed on accident

**Comment by iamacup** [comment]
My apologies, i did not realise this was limited to only projects with hooks - turns out all of mine have them - i thought it was all blanks. Thanks

**Pull request merged**
