### PR TITLE
Add error code advisory to CLI output (#1068)

### PR DESCRIPTION
**Pull request by rlue**
This commit is intended to help newcomers diagnose errors or warnings
by expanding CLI output to explain how to recognize error codes
and where to find documentation about them online.

This added line of CLI output can be disabled via a new
`errorCodeAdvisory` configuration option.

### CODE REVIEW

**Comment by rlue** [comment]
WARNING: I have not actually tested these changes, as I don't know how to run a locally compiled version of it (or compile it to begin with, for that matter). Looking forward to feedback and guidance, if you can spare the time.

Also completely unfamiliar with the test suite and which tests, if any, need to be modified/added.

**Comment by rlue** [comment]
So to get tests passing, I've had to modify the jest snapshots for the following two tests:

* [`packages/acceptance-tests/pkg-tests-specs/sources/commands/install.test.js`](https://github.com/yarnpkg/berry/blob/master/packages/acceptance-tests/pkg-tests-specs/sources/commands/install.test.js)
* [`packages/acceptance-tests/pkg-tests-specs/sources/commands/constraints/query.test.js`](https://github.com/yarnpkg/berry/blob/master/packages/acceptance-tests/pkg-tests-specs/sources/commands/constraints/query.test.js)

The corresponding snapshots ([install](https://github.com/yarnpkg/berry/blob/master/packages/acceptance-tests/pkg-tests-specs/sources/commands/__snapshots__/install.test.js.snap) / [query](https://github.com/yarnpkg/berry/blob/master/packages/acceptance-tests/pkg-tests-specs/sources/commands/constraints/__snapshots__/query.test.js.snap)) both include CLI output for warning / error cases, and the changes in this PR caused the new output to differ from the snapshots.

**I made this modifications by hand, rather than deleting and re-running jest. Is that okay?**

I presume I should add two more test cases here so that jest can verify that the  `errorCodeAdvisory` config option actually does what it's supposed to.

**Any advice on this point? _E.g.,_ can I use `makeTemporaryEnv` to set yarn config values, and if so, how?**

**Comment by arcanis** [comment]
I'd strongly prefer to keep the terminal output lean. I understand the message can be disabled, but from my perspective this message will only be beneficial to a limited and ever-decreasing amount of people (since once they know about it they don't need to see it again), which isn't great.

I think a better solution would be to add hyperlinks on the error codes, so that they can be command-clicked to jump directly to the error message. This is for example what Jest is now doing to enable quick jump-to-file.

**Comment by arcanis** [comment]
As for testing your PR, you can just run `yarn` in the repository: it uses the actual TypeScript sources, so you'll see your changes live. More on that in the [contribution guide](https://yarnpkg.com/advanced/contributing).

**Comment by rlue** [comment]
> I'd strongly prefer to keep the terminal output lean.

Fair enough, and thanks a ton for your feedback and guidance. My main concern here is discoverability, and I don't think terminal hyperlinks fix that. Case in point (from the proposal you linked above, emphasis mine):

> The hyperlink feature should be used for providing convenient quick access to a target URI, but (at least by default) should not be the only means of **figuring out** the target.

It's about enabling users to figure out how things work. Discoverability is the difference between software that requires expertise and software that cultivates it. IMO, this is especially important for a package manager, which serves as the point-of-entry to an ecosystem for new users, and thus is one of the most visible sources of UI patterns for other packages to follow.

I spent a day debugging an issue, and by the end, the only reason I learned about error codes was that I filed an issue here and you responded to tell me about them. If I hadn't gone to the trouble of filing that issue, or if you had been swamped with other things, I _still_ wouldn't know about them.

Is there another way yarn could meet newcomers halfway? Maybe just including error messages verbatim in the error codes docs?

**Comment by arcanis** [comment]
> Is there another way yarn could meet newcomers halfway? Maybe just including error messages verbatim in the error codes docs?

You mean not just the error code, but the whole message too? I'd love that, the problem is to find ways to extract the messages from the documentation. It would require to parse the files' AST to detect the `ReportError` instances and link the error codes to the messages.

I'm also working on #1092 to add an Algolia-based search engine to the website - this will make it much easier to find information when you don't know where to look for.

**Comment by rlue** [comment]
> You mean not just the error code, but the whole message too?

Yes. I mean that I saw

```
➤ YN0002: │ rc-animate@npm:2.10.3 doesn't provide react@^15.0.0 || ^16.0.0 requested by rc-util@npm:4.20.1
```

and in hindsight, I should have googled for `yarn "YN0002"` but what I actually googled was `yarn "doesn't provide" "requested by"`. Now I know better, of course, but I don't think I'm the only one out there who would make this mistake, and so it would help a lot if the error code docs came up for that query.

However, I can appreciate the technical challenges you outlined above, and that doing it manually would be tedious and prone to falling out of sync as new errors are added or existing ones are modified. :\\

**Pull request closed without merging**
