### PR TITLE
fix(core): prevent hangs due to degenerate lockfile diff

### LINKED ISSUE #4405: [Bug]: Yarn 3.2.0 hangs when diffing lockfiles due to endless-loop bug in `diff` package
### Self-service

- [X] I'd be willing to implement a fix

### Describe the bug

When I `yarn install --immutable` inside a container as part of my CI process, Yarn detects that the lockfile would be updated and attempts to show me the diff before exiting with an error.

For the particular lockfile that I am using with my project, the diff never completes: yarn runs forever, using 100% CPU, until I kill it.

### To reproduce

I have isolated the problem to the `diff` [package](https://www.npmjs.com/package/diff), a dependency of Yarn, and filed [an issue](https://github.com/kpdecker/jsdiff/issues/364) with the maintainer of that package, including a [self-contained reproduction](https://gist.github.com/xeger/88f96eaf6f8980bb148c5d5d874b2a80) that does not depend on yarn.

### Environment

```shell
System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (4) x64 unknown
  Binaries:
    Node: 16.14.2 - /tmp/xfs-5c2a3254/node
    Yarn: 4.0.0-rc.3.git.20220426.hash-67ce47fc6 - /tmp/xfs-5c2a3254/yarn
    npm: 8.5.0 - /usr/local/bin/npm
```

### Additional context

I am at an impasse: I can't upgrade my project to Yarn 2/3 as long as those tools are unstable and prone to disrupt my development workflow. It seems like Yarn's attempt to provide a UI nicety (colorized diffs) is making it fundamentally unstable.

The hang happens both with `diff@4.0.1` (used by `yarn@3.2.0`) and the most recent build, `diff@5.0.0` -- so a simple upgrade of `diff` will not suffice to fix the issue.

Short of fixing the underlying bug, I'm not sure how the Yarn team could proceed. Personally, I don't need the diff in the environments where this hang occurs -- or ever. A `.yarnrc.yml` flag to disable diffs would be an adequate workaround for me.

I'm happy to attempt whatever feature the team decides is appropriate. Personally, I'm not sure I trust the `diff` package enough at this point to depend on it for a tool that is a core part of my software development lifecycle. I appreciate that yarn's goal is to run with no dependencies on the OS, however, and it seems that Yarn patches also use `diff` -- so perhaps the Yarn team can provide some help to the maintainer of `diff`.

### PR DESCRIPTION
**Pull request by xeger**
**What's the problem this PR addresses?**

This limits the max edit length for jsdiff, keeping it from taking "forever" with very large lockfiles that have substantial changes. It keeps `yarn install --immutable` from hanging when the prior lockfile was substantially different from the computed lockfile, and thereby fixes #4405.

...

**How did you fix it?**

The fix relies on a new `maxEditLength` option for jsdiff, which is available in jsdiff@5.1.0.

If the max edit length is exceeded, jsdiff returns `undefined` and `Project.ts` simply skips the verbose diff output.
...

**Checklist**

- [X] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [X] I have set the packages that need to be released for my changes to be effective.

- [X] I will check that all automated PR checks pass before the PR gets reviewed.
    - CAVEAT: one failing job that I'm stumped on; marked ready to review to gain advice

### CODE REVIEW

**Comment by arcanis** [comment]
That looks good to me, thanks! Until the package is properly released we can try using it with a git protocol (cc @kpdecker)

**Comment by xeger** [comment]
FWIW @arcanis I'm not sure git protocol ("diff": "git@github.com:kpdecker/jsdiff.git"`) will work for this case, since the lib requires transpilation + bundling. I will experiment with using `patch:` protocol.

**Comment by arcanis** [comment]
> FWIW @arcanis I'm not sure git protocol ("diff": "[git@github.com](mailto:git@github.com):kpdecker/jsdiff.git"`) will work for this case, since the lib requires transpilation + bundling. I will experiment with using `patch:` protocol.

I think we can just upgrade to the newly published 5.1!
https://github.com/yarnpkg/berry/issues/4405#issuecomment-1134098112

Although as a trivia, Yarn runs the `prepack` script when cloning repositories. So even if there's transpilation, if the repository is well configured, it should be possible to use git deps 🙂

**Comment by xeger** [comment]
I don't know 100% that the build will go green, but the one failing job seemingly has nothing to do with my PR - a typescript package's checksum has begun failing. I experimentally freshened it using the latest from npmjs.org -- hopefully this isn't some obscure supply chain attack!

**Comment by arcanis** [comment]
> The only difference between the two is that one is better compressed than the other, otherwise their content is identical. Same thing happens on `master` though this suddenly changing is worrying.

Hm perhaps you installed TS 4.7 in a project which had a compression set to `0`, which led to the package being added as such into the global cache; then when you upgraded it into the Yarn repo it pulled the `0`-compression archive from the global cache and put it in the local one.

However this shouldn't be possible because we [append a cache key](https://github.com/yarnpkg/berry/blob/master/packages/yarnpkg-core/sources/Cache.ts#L76-L83) to the global path, and the compression level is part of it 🤔

**Comment by merceyz** [comment]
Yeah, that shouldn't be possible, besides the size difference isn't enough for that to be the case.
```diff
-11 652 885 bytes
+11 654 629 bytes
```

**Pull request merged**
