### PR TITLE
fix(npm): stale metadata cache issue

### LINKED ISSUE #5989: [Bug?]:  No candidates found in corporate environment
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

`yarn install` leads to 

```
➤ YN0000: · Yarn 4.0.1
➤ YN0000: ┌ Resolution step
➤ YN0082: │ @typescript-eslint/scope-manager@npm:6.13.1: No candidates found
➤ YN0000: └ Completed in 9s 219ms
➤ YN0000: · Failed with errors in 9s 235ms
```

install with 1.22.19 works
yarn config gives me 

```
├─ npmRegistryServer
│  ├─ Description: URL of the selected npm registry (note: npm enterprise isn't supported)
│  ├─ Source: /home/myuser/code/myproject/.yarnrc.yml
│  └─ Value: 'https://artifactory.mycompany.net:443/artifactory/api/npm/npm'
```

`yarn npm info  @typescript-eslint/scope-manager` gives me (excerpt)
```
{
    "name": "@typescript-eslint/scope-manager",
    "description": "TypeScript scope analyser for ESLint",
    "dist-tags": {
        ...
        "latest": "6.13.1",
        ...
    },
    "versions": [
        "3.5.0",
         ...
        "6.13.1",

    ],
    "time": {
        ...
        "6.13.1": "2023-11-28T09:36:31.088Z",
        ...
    },
    "dist": {
        "tarball": "https://artifactory.mycompany.net:443/artifactory/api/npm/npm/@typescript-eslint/scope-manager/-/scope-manager-6.13.1.tgz",
        "shasum": "58c7c37c6a957d3d9f59bc4f64c2888e0cac1d70",
        "integrity": "sha512-BW0kJ7ceiKi56GbT2KKzZzN+nDxzQK2DS6x0PiSMPjciPgd/JRQGMibyaN2cPt2cAvuoH0oNvn2fwonHI+4QUQ=="
    },
    "type": "commonjs"
}
```

### To reproduce

I cannot provide, as this only occurs in my company repo I think

### Environment

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (12) x64 Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz
  Binaries:
    Node: 20.10.0 - /tmp/xfs-d62f7f1e/node
    Yarn: 4.0.1 - /tmp/xfs-d62f7f1e/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by arcanis**
**What's the problem this PR addresses?**

We now keep the package metadata in cache. To avoid missing new packages being released we have a check so that we only accept the cached metadata if 1/ the request asks for a semver version (not a range), and 2/ the requested version is found inside the cached metadata. In theory this means that whenever a dependency asks for a version we didn't cache, we assume something new got published, and we refetch it.

However, to prevent fetching the package metadata many times for many different versions or ranges, we also have an in-memory metadata cache where we store the cached metadata once we extracted them from either the disk or the network.

This may lead to memory cache corruption issues when two versions from the same package are resolved if one exists in the cached metadata but the other doesn't. In that case, the first package will pass the check for "is this version inside the cached metadata", get stored in the in-memory cache, and be reused for further resolutions (even if those resolutions would have failed this check). This is because the disk cache and the memory cache are the same.

Fixes #5989

**How did you fix it?**

I separated the in-memory cache into two buckets: the disk cache, and the network cache. This ensures that the disk cache gets properly ignored when retrieving versions we don't know, rather than be mistakenly assumed to be what the network fetched.

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

**Comment by derHodrig** [comment]
This should be included in 4.3.1, correct?
The issue still persists.

1. Publish package to self hosted gitlab
2. try to install this package >> no candidates found
3. delete the metadata folder
4. try to install again > works

so from that perspective, it doesnt seems to be included or does not work.

**Comment by arcanis** [comment]
Please open an issue *with a reproduction*. We can't fix what we can't see.

**Comment by ds1371dani** [comment]
I am using version 4.4.1 and still have this issue

**Comment by merceyz** [comment]
@ds1371dani See the comment above yours.

**Comment by ds1371dani** [comment]
https://github.com/yarnpkg/berry/issues/6477 here you go

**Pull request merged**
