### PR TITLE
fix(nm): Fixes nm linker `link:` dependencies mistreatment as inner workspaces

### PR DESCRIPTION
**Pull request by larixer**
**What's the problem this PR addresses?**

Fixes: #6056 

**How did you fix it?**

The nm linker erroneously regarded `link:` dependencies as an inner workspace when they pointed to some of the parent directories of a real workspace. I have added an additional check to not regard a soft link a workspace if it uses a `link:` protocol.

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

**Comment by joshhunt** [comment]
FWIW - I verified myself this fixed the issue in my repro. Thanks!

image

**Comment by larixer** [comment]
@joshhunt Happy new year :) Thank you for confirmation!

**Review by merceyz — COMMENTED** [review]
Fix looks good but could you add a test as well?

**Comment by joshhunt** [comment]
@larixer @merceyz I'm really keen to get this fixed, and am more than happy to contribute tests myself. Would that be welcome?

I presume they would be another integration test in `packages/acceptance-tests/pkg-tests-specs/sources/node-modules.test.ts`. Any pointers for the right test case would be appreciated - I presume this bug also relies on the hoisting behaviour of a sub-package depending on a different version of a package from the workspace root? I should be able to take inspiration from the existing cases, but if you have pointers that would be appreciated 🙌

**Comment by larixer** [comment]
@joshhunt Yeah, I'd appreciate if you could add a test. You are right, the test must be added there. After adding a test you should execute `yarn build:cli` to build Yarn bundle, because integration tests as far as I remember are run against the bundle, not against the source code. After that you can run your test via `yarn test:integration node-modules -t "<some_text_from_your_test_description>"`

**Comment by joshhunt** [comment]
@larixer Test https://github.com/yarnpkg/berry/pull/6089 ! 🥳

**Review by merceyz — APPROVED** [review]

**Pull request merged**
