### PR TITLE
remove pnpPath config option

### LINKED ISSUE #309: [Bug] @berry/pnpify ignores pnpPath
**Describe the bug**

@berry/pnpify ignores pnpPath config option

**To Reproduce**

I don't think this is needed - it's apparent from looking at the source
Check out Additional context

**Additional context**

https://github.com/yarnpkg/berry/blob/a5cadd6309126ba0b04ea821fa37fa312b05fcd9/packages/berry-pnpify/sources/generateSdk.ts#L32

generateSdk looks for `.pnp.js` at the root of the project instead of asking yarn for the `pnpPath`

### PR DESCRIPTION
**Pull request by Teoxoy**
closes #309

Removes `pnpPath` config option.

**Why**

> Although the location of the PnP file is technically configurable, I'm not sure we really want to support storing it elsewhere than in the project root 🤔
The primary problem (and that's similar for microsoft/vscode-languageserver-node#496) is that it would require the PnPify binary (and any other tool that would want to add some specific PnP integration) to add the Yarn core into its dependencies (to parse the configuration). That sounds a bit overkill for a fringe use case.

from https://github.com/yarnpkg/berry/issues/309#issuecomment-515917750

### CODE REVIEW

**Comment by Teoxoy** [comment]
I forgot to remove [this test](https://github.com/yarnpkg/berry/blob/master/packages/acceptance-tests/pkg-tests-specs/sources/features/projectDetection.test.js).

@arcanis Should I remove the test or modify it so that it looks for some other config option?

**Comment by arcanis** [comment]
Hm - modify it so that it targets `cacheFolder` instead (`.yarn/cache`)

**Comment by Teoxoy** [comment]
@arcanis How do I generate a new snapshot for `config.test.js`?

**Comment by arcanis** [comment]
```
$> yarn test:integration config -u
```

**Comment by Teoxoy** [comment]
@arcanis Any issues with this PR?

**Comment by arcanis** [comment]
Nope! Our website build workflow was broken, so I wanted to fix that before landing this. Should be fine now - checking whether the PR can be merged and if it's green it ships 👍

**Pull request merged**
