### PR TITLE
docs: add edit on github link to doc pages

### PR DESCRIPTION
**Pull request by andreialecu**
**What's the problem this PR addresses?**

This adds an `Edit this page on Github` link to markdown based documentation pages.

It should make it easy for people to contribute improvements, grammar fixes, etc, to the docs.

**How did you fix it?**

Added logic to parse out the absolute file path of an article and transform it to a github url that links to the specific page.

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

**Comment by andreialecu** [comment]
Preview:

Screenshot 2021-03-23 at 12 09 07

**Comment by arcanis** [comment]
Nice! Design-wise, what do you think about moving it inside the title? Ie instead of:

image

Have:

image

**Comment by andreialecu** [comment]
I thought about that, but it wouldn't look right on small (mobile) screens. 🤔

Adding it below was the simplest to make it work well everywhere.

I could add a media query for it though and revert to current behavior on smaller screens.

**Comment by andreialecu** [comment]
Also, depending on how long titles are, it may also break on larger screens if it was added there.

Let me know and I can change it though.

**Comment by arcanis** [comment]
A media query to use an icon (or break it on a following line) would be the best imo. Or perhaps even hide it altogether - people on mobile are unlikely to edit the doc via the GH interface anyway 🤔

**Comment by andreialecu** [comment]
Done. I used plain `flex` instead of media queries.

On small screens it wraps if it doesn't fit:

Screenshot 2021-03-23 at 13 33 34

On bigger screens:

Screenshot 2021-03-23 at 13 33 44

**Comment by andreialecu** [comment]
I just noticed a problem with the table of contents. Fixing it.

**Comment by andreialecu** [comment]
Fixed.

**Comment by arcanis** [comment]
Nice, thanks!

**Pull request merged**
