### PR TITLE
consolidate virtual packages when resolution yields the same dependency list

### PR DESCRIPTION
**Pull request by lroling8350**
**What's the problem this PR addresses?**
A package may have a peer dependency while being included as a standard dependency in other packages. When this occurs, it leads to multiple virtual packages which could potentially resolve to a single virtual package (when all peer dependencies resolve to the same instance). The added test case highlights a set of packages that can result in duplication this PR address.
...

**How did you fix it?**
During virtualization of packages, the new virtual descriptors are grouped by the package locator used to created virtualized package. Also, a mapping of the virtual descriptors to dependent packages is created as dependencies are replaced with virtual packages. Once virtualization is complete, each descriptor group is then checked to see if any virtual packages are "equivalent". Virtual packages are equivalent if their peer dependencies resolved to the same package descriptor. If any duplicates are found, the mapping of virtual descripts to dependent packages is used to update the dependency references. Since consolidation could lead to new virtual packages that are now "equivalent" another pass is made until no more consolidation occurs.
...

### CODE REVIEW

**Comment by arcanis** [comment]
Hey @lroling8350! First of all congratulations, I'm really impressed. This feature is something I had on mind some times ago but never found the time to implement, and after carefully reviewing it I can say that your approach is exactly in line with what I would have done. I take it the surrounding code was clear enough to properly understand its architecture?

I've made a few changes, but nothing too serious. It was mostly useful to me to get a better picture of the changes - sometimes the PR diff is too abstract and I need to actually see the changes in my editor. The most interesting changes are:

- I reverted the test in `Project.test.ts` - in general I prefer tests that validate the behavior of the install to be stored in our acceptance tests (unit tests being meant to exclusively test the JS API itself). I replaced them by three new tests in `pnp.test.ts`.

- I moved `getWithDefault` into `miscUtils` so that it can be reused elsewhere. There are multiple places where this logic is used, and by looking at your helper I figured it would make sense to clean that a little bit.

- The builder didn't need to be released again so I reverted its bump. No big deal 🙂

Thanks again, if everything is green after my changes I'll merge that tomorrow and release!

**Comment by lroling8350** [comment]
Thank you so much for reading through this PR in a timely manner and also, making all the small changes. I tried my best to keep the code consistent with what is there. I reviewed your changes to keep in mind for any future enhancements. Last night i couldn't find the miscUtils folder and felt like something had to exist, it's what i get for late night programming. 

The v2 code base is amazing to read through.  I'm still wrapping my head around most of it but the core resolution logic is pretty manageable and the consistency in naming and terminology makes it pretty easy to pick up. You all have done great job isolating concerns. The fact i only had to touch one function to implement this enhancement was great. The run-yarn.js to setup develop mode is also a great feature to play around with things without having to build down to js everytime i changed something. 

I have been working with pnp in a mono repo with react native since about May. We have had several "hacks" in yarn and on post install to make it all work. Most of the hacks deal more around metro bundler which is outside of yarn's control but this enhancement and one or two more i'll propose before submitting requests would allow me to remove all yarn specific hacks.

**Comment by arcanis** [comment]
That sounds exciting! React Native is one of the main compatibility issue that remains, and @larixer is currently working on improving that by adding fallback support for `node_modules`. But if we could also make it work directly with PnP it would be fantastic!

**Comment by lroling8350** [comment]
I have it working directly with PnP. The one caveat is the native code benefits from the npm packages being unzipped and in node_modules. I got around this by using the rn config to find out which packages have native code and just unzipping them to disc. The only caveat is transitive dependencies with native code. I don't believe react native can handle this to begin with. I'm also wondering if a linker plugin can solve this.

**Comment by arcanis** [comment]
Interesting - which bundler do you use? The regular Metro? At the moment the main issue we have is to make the Haste map it uses aware of the files inside the zip (even for non-native modules). We've been discussing on [Discord](https://discord.gg/yarnpkg) how we could make that happen, feel free to join if you want to chat sometime!

**Pull request merged**
