### PR TITLE
ci: test storybook@next

### PR DESCRIPTION
**Pull request by merceyz**
**What's the problem this PR addresses?**

The current latest release of storybook (6.1.18) has an undeclared dependency that we could have caught earlier

cc @gaetanmaisse 

**How did you fix it?**

Test the `next` version of storybook

**Checklist**
- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).
- [x] I have set the packages that need to be released for my changes to be effective.
- [x] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

**Comment by merceyz** [comment]
The stuff failing now was introduced in https://github.com/storybookjs/storybook/pull/13808 cc @shilman

**Comment by shilman** [comment]
@merceyz sorry about that. @gaetanmaisse and I are on it--thanks for your patience! 🙏

**Comment by gaetanmaisse** [comment]
I fixed the error currently throwing on `master` a few days ago (https://github.com/storybookjs/storybook/pull/13916) and thought @shilman cherry-picked it to `master` but it looks like there was a misunderstanding, so I made a PR to fix `master` (https://github.com/storybookjs/storybook/pull/13991), I think it will be merged and released in the next 24h.

I don't really know what to think about using `next` in your E2E as this branch can be quite unstable... I don't want to give you some extra work/failing runs... we have the same E2E test on our side and we clearly neglected it for the last PRs merged on `master`, it's on us 😞

**Comment by merceyz** [comment]
> I don't really know what to think about using next in your E2E as this branch can be quite unstable... I don't want to give you some extra work/failing runs

That's fine and kind of the point of the e2e test, to catch issues as soon as possible, besides our CI has been red for months so nothing new there

**Pull request merged**
