### PR TITLE
Change portable path format to get rid of /mnt

### PR DESCRIPTION
**Pull request by vlasenko**
This PR changes portable path format to more convenient for usage inside berry, e..g without `/mnt` prefix. This makes algorithms doing path splitting on segments and then reassembling path from segments happy.

### CODE REVIEW

**Comment by arcanis** [comment]
Nice! It seems like the Windows tests are legit broken, though - can you try to run `yarn test:integration commands/stage` to see if you can reproduce?

**Comment by vlasenko** [comment]
@arcanis Yes, I'm looking now

**Comment by vlasenko** [comment]
@arcanis Integration tests pass now

**Comment by arcanis** [comment]
All good 👍

**Pull request merged**
