### PR TITLE
Upgrades Chalk

### PR DESCRIPTION
**Pull request by arcanis**
**What's the problem this PR addresses?**

We were behind by a major, better keep up-to-date with upstream. Practically, I hope this will fix the issue where the terminal colors aren't printed on GitHub Actions.

**How did you fix it?**

Manual upgrade.

### CODE REVIEW

**Comment by arcanis** [comment]
This is why we don't have colors:
https://github.com/chalk/supports-color/issues/106
https://github.com/actions/virtual-environments/issues/218

**Comment by nicolo-ribaudo** [comment]
Sorry to ask in an old merged PR, but is there any plan to revert this now that https://github.com/chalk/supports-color/issues/106 has been fixed? (I'm currently manually working this around with `YARN_ENABLE_COLOR=0` since it beaks `|`)

**Comment by arcanis** [comment]
You mean the check on `GITHUB_ACTIONS`? Yep, that sounds something we'll want to fix 👍

**Comment by nicolo-ribaudo** [comment]
Yup that one.

**Pull request merged**
