### PR TITLE
feat(fslib): export `@yarnpkg/libzip`

### PR DESCRIPTION
**Pull request by merceyz**
**What's the problem this PR addresses?**

`ZipFS` depends on `@yarnpkg/libzip` and requires the user to provide an instance of `libzip` but `@yarnpkg/fslib` doesn't export it so the consumer needs to install it themselves which is unnecessary overhead.

**How did you fix it?**

- Default `libzip` to `getLibzipSync`
- Export `@yarnpkg/libzip` from `@yarnpkg/fs`

**Checklist**
- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).
- [x] I have set the packages that need to be released for my changes to be effective.
- [x] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

**Comment by arcanis** [comment]
Wouldn't that cause the sync copy of libzip to be included even if an application on uses the async version?

**Comment by merceyz** [comment]
No, it should only include https://github.com/yarnpkg/berry/blob/f14390aad02c8fe04d05975b15eb7e24997069c2/packages/yarnpkg-libzip/sources/async.ts#L6-L8

**Comment by paul-soporan** [comment]
> Default libzip to getLibzipSync

**Comment by merceyz** [comment]
That is a possibility

**Pull request closed without merging**
