### PR TITLE
Allow symlinks in MountFS

### PR DESCRIPTION
**Pull request by thatsmydoing**
**What's the problem this PR addresses?**

Yarn shouldn't care if zips in the cache are symlinks or not. The only reason it doesn't work is that finding the mount point skips zips if they're not regular files. This used to be supported until it was removed for "performance" reasons in https://github.com/yarnpkg/berry/pull/1474. The bulk of the logic in the linked PR involves resolving the real path of the symlink but I don't think that's needed for this?

Resolves https://github.com/yarnpkg/berry/issues/3514

**How did you fix it?**
I switched the check to use `stat` from `lstat`.

**Checklist**

- [X] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [X] I have set the packages that need to be released for my changes to be effective.

- [x] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

**Review by merceyz — CHANGES_REQUESTED** [review]
> This used to be supported until it was removed for "performance" reasons in https://github.com/yarnpkg/berry/pull/1474

Removing support for symlinks wasn't the goal of that PR and since no tests failed the regression wasn't spotted.

Please add a test so we can avoid future regressions, I see the linked issue contains one which can be added to https://github.com/yarnpkg/berry/blob/e20f8369510e2c1c9e82cae2bef7d96e05dbffed/packages/acceptance-tests/pkg-tests-specs/sources/pnp.test.js

**Comment by thatsmydoing** [comment]
I've added the tests. The acceptance tests were timing out on windows so I just excluded them. For some reason, the unit test works though so I'm just letting it run unconditionally.

**Comment by hansottowirtz** [comment]
Side note: I'm getting this error on Vercel when setting `YARN_CACHE_FOLDER=node_modules/.yarn-cache`:

> YN0001: │ Error: While persisting /vercel/path0/node_modules/.yarn-cache/node-gyp-npm-9.3.1-43540bab9c-b860e9976f.zip/node_modules/node-gyp/ -> /vercel/path0/node_modules/node-gyp ENOENT: no such file or directory, scandir '/vercel/path0/node_modules/.yarn-cache/node-gyp-npm-9.3.1-43540bab9c-b860e9976f.zip/node_modules/node-gyp'

I hope this PR will also fix that, if not I'll make a new issue.

**Comment by thatsmydoing** [comment]
@merceyz are there any other changes you want me to make?

**Comment by hansottowirtz** [comment]
@merceyz Sorry for pinging, but could this be merged or are there any blockers?

**Comment by hansottowirtz** [comment]
@thatsmydoing would you be able to rebase on master?

**Comment by hansottowirtz** [comment]
@arcanis Any way this could be merged?

**Comment by gabrielrussoc** [comment]
Hey @thatsmydoing @merceyz -- is this safe to be merged?

**Comment by hansottowirtz** [comment]
@thatsmydoing I have asked on the Discord, and the Yarn team would need permissions to update your fork: https://discord.com/channels/226791405589233664/1297852972713377863

**Pull request closed without merging**
