### PR TITLE
Automatic discovery of types for Berry packages

### PR DESCRIPTION
**Pull request by vlasenko**
This PR adds automatic discovery of types by `ts-loader` for packages inside Berry monorepo. It does so by loading `berry-pnpify` while creating Webpack config.

### CODE REVIEW

**Comment by arcanis** [comment]
LGTM

@vlasenko it seems to break some pnpify tests

**Comment by vlasenko** [comment]
@arcanis Thanks for noticing. This is fixed now. All builds pass, except OS X Node 8, again failed because of timeout in acceptance tests

**Comment by vlasenko** [comment]
Btw, do you happen to know why Azure Pipelines didn't send email to me, because of failing build?

**Comment by arcanis** [comment]
No idea, I think we use the default parameters 🙁

**Pull request merged**
