### PR TITLE
style(eslint): better eslint config

### PR DESCRIPTION
**Pull request by paul-soporan**
**What's the problem this PR addresses?**

ESLint currently uses very few rules and some common styles across the codebase aren't enforced.

Disclaimer:
Some of these styles differ from my own opinions (I'd personally go with Prettier + Airbnb) and some of them don't. My intention isn't to enforce my own styles, but to enforce consistency and to make use as much as possible of ESLint's auto-fix functionality to make up for the lack of Prettier. :smile: (I know what's your opinion about Prettier, but I still think it can do things ESLint can't):
I went as much as I could with how the majority of the existing code is styled (e.g. backticks, arrow parens as needed, generic array type).
Feel free to merge what you agree with and remove what you don't agree with.

**How did you fix it?**

- I enabled `eslint:recommended`, as it's mostly about code quality and helping catch bugs.
Note:  I fixed `no-useless-escape` in a separate commit so that it can be more easily reverted, just in case :P.

- I enabled some extra rules. Bonus: many of them are autofixable
The rules I added fall into 3 categories:
	1) Code Style and Consistency (e.g. `arrow-parens`, `@typescript-eslint/quotes`, `@typescript-eslint/type-annotation-spacing`)
	2) Less verbose code (e.g. `dot-notation`, `object-shorthand`, `no-unneeded-ternary`)
	3) Rules that help catch bugs (e.g. `no-constant-condition` and most of `eslint:recommended`)

Some suggestions into what else could be enabled (I didn't enable them myself yet, as I'm not sure if what @arcanis thinks about them):
- [`@typescript-eslint/consistent-type-definitions`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/consistent-type-definitions.md) - I personally prefer interfaces, but I've seen that the existing code sometimes uses types and sometimes interfaces
- [`no-return-await`](https://eslint.org/docs/rules/no-return-await) - the current code is full of `return await`s, but they are generally bad for performance
- [`no-extra-parens`](https://eslint.org/docs/rules/no-extra-parens#options) - If we do enable it, we should use the `@typescript-eslint` variant
- [`no-else-return`](https://eslint.org/docs/rules/no-else-return) - I personally think that the flow of the code is better without the `else`
- [`prefer-destructuring`](https://eslint.org/docs/rules/prefer-destructuring) - I didn't enable it yet because I think there are some places where we don't use Array destructuring

I would've also enabled `@typescript-eslint/recommended` if it didn't include so many rules about type correctness. Judging by the amount of `@ts-ignore`s and non-null assertions already present in the codebase, I think it's too late for that 😄.

What do you think @arcanis? I hope I didn't go too far with this PR, I just want not to have to worry about code style as much :P.

### CODE REVIEW

**Comment by arcanis** [comment]
That sounds reasonable overall! However I'd prefer not to use `extends` (instead inlining the rule definitions that we use). It's difficult otherwise to know what's enabled, and there's a risk they could change and lead to impractical upgrades.

> [`@typescript-eslint/consistent-type-definitions`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/consistent-type-definitions.md) - I personally prefer interfaces, but I've seen that the existing code sometimes uses types and sometimes interfaces

Generally I tend to use `type` when the type doesn't make sense to extend (or a fixed set of alternatives), and `interface` when there's polymorphism involved.

> [`no-return-await`](https://eslint.org/docs/rules/no-return-await) - the current code is full of `return await`s, but they are generally bad for performance

I really dislike how they're worse for performances; I find it better for lisibility to clearly annotate async calls with await 🙁 Maybe it should just be transformed by Babel? ...

> [`no-else-return`](https://eslint.org/docs/rules/no-else-return) - I personally think that the flow of the code is better without the `else`

Would have to check the actual diff, but I'd tend to be skeptical about this one 🤔

> [`no-extra-parens`](https://eslint.org/docs/rules/no-extra-parens#options) - If we do enable it, we should use the `@typescript-eslint` variant

Sounds good; maybe in a separate diff?

> [`prefer-destructuring`](https://eslint.org/docs/rules/prefer-destructuring) - I didn't enable it yet because I think there are some places where we don't use Array destructuring

Same!

**Comment by paul-soporan** [comment]
I created a separate `@yarnpkg/eslint-config` package so we can organize the rules more easily. What do you think? I can revert this change if you don't agree.

**Comment by arcanis** [comment]
Good idea 👍

**Comment by paul-soporan** [comment]
Going to mark this as ready once I organize the rules a bit better.

**Comment by paul-soporan** [comment]
I've had a change of mind. I don't really have time to organize the rules right now, and there's no need to until we want to make the config more modular in the future. I think this PR is ready for now.

**Comment by arcanis** [comment]
🚀

**Pull request merged**
