### PR TITLE
Some small updates to grammar

### PR DESCRIPTION
**Pull request by accidentaldeveloper**

### CODE REVIEW

**Comment by arcanis** [comment]
Sounds good in essence, the changes just have to be moved into `packages/gatsby` instead of `doc`! Cf [our contribution documentation](https://yarnpkg.github.io/berry/advanced/contributing#writing-documentation) for more information 😃

**Comment by accidentaldeveloper** [comment]
Ah, thank you for directing me to the right folder. I had a feeling that they might be generated files!

**Comment by arcanis** [comment]
I'm going to close it for now, but feel free to reopen a new one at your convenience. Thanks! 😊

**Comment by accidentaldeveloper** [comment]
Thanks @arcanis , I've been a little busy but I will get to it soon.

**Pull request closed without merging**
