### PR TITLE
docs: improve Plug'n'Play documentation

### PR DESCRIPTION
**Pull request by bcdady**
Edit plugnplay.md for grammar and readability

**What's the problem this PR addresses?**
Enhances Plug'n'Play documentation

**How did you fix it?**
Manual editing along with a bit of help from grammarly

### CODE REVIEW

**Comment by Bosch-Eli-Black** [comment]
Looks nice 🙂

**Comment by bcdady** [comment]
@merceyz, @arcanis, @paul-soporan, or @larixer - Are there any additional iterations you'd suggest for this PR, or would you review and consider approval as is?
Thanks in advance!

**Comment by bcdady** [comment]
Hi @merceyz, @arcanis, @paul-soporan, and @larixer - I've still not seen any PR feedback or progress on this. Is there anyone else I should reach out to?
Is the lack of activity / feedback an indication that this isn't a priority and I should just delete the request?
I look forward to your advice. Thanks!

**Comment by arcanis** [comment]
Hey @bcdady! Sorry, I'm the one who tends to review these PRs but I didn't get much time this past month, and it was still in my backlog 😅 I'll take a look asap

**Pull request merged**
